### ISSUE TITLE
[Fix] Phases

### ISSUE THREAD

**Issue by hfatima1** [lisphilar/covid19-sir#1005]
I am working on  covsirphy==2.21.0. Initially, with the same data a few months ago I did S-R trend analysis and it divided my data into 31 phases. Now, with the same code and same file, when I run S-R trend analysis, instead of 31 phases, it divides my data into 9 phases. The problem isn't 9 phases but the fact that it creates problem with simulation In next phases when i try to analyse medicine, lockdown and vaccine scenerio

**Comment by lisphilar** [comment]
Please clarify the followings.
- Codes
- When did you get 31 phases?
- When did you get 9 phases?
- Images yo got if available
- Python version
- OS version

At the next time please use bug-fix issue template, editting the template (not remove the template).

**Comment by lisphilar** [comment]
Please create a new issue with details, if necessary.
