### ISSUE TITLE
[Question] new database

### ISSUE THREAD

**Issue by elmedianikhadija** [lisphilar/covid19-sir#1048]
hello,
 please,  i want to use new database for my analysis,  how i can do it ?

**Comment by lisphilar** [comment]
Hello @elmedianikhadija ,
Did you try `DataLoader.read_csv()` and `DataLoader.read_dataframe()`?
https://lisphilar.github.io/covid19-sir/markdown/LOADING.html

**Comment by geeky-programer** [comment]
I am using the functionality of DataLoader.read_csv(). If this procedure is followed there is no cleaning function that can be used on the pandas' object.
And there is no inclusion of the infected column in data.load phase and there is a problem using the ExampleData(). function

**Comment by lisphilar** [comment]
Dear @geeky-programer ,
Please use `df = pd.read_csv(); (data cleaning); DataLoader().read_dataframe(df)` at this time.

Note that `JHUData` class (parent class of `ExampleData`) calculates Infected = Confirmed - Recovered - Fatal automatically and internally. Could you provide me with the details of the problem?

With #1064, I plan to create `DataEngineer` class, which handles all of data reading, data cleaning and calculation of Infected.

**Comment by geeky-programer** [comment]
The output of both of these df = pd.read_csv(); (data cleaning); DataLoader().read_dataframe(df),Does not contain the Infected column and the data is not cleaned properly.

I have followed the steps as described in https://lisphilar.github.io/covid19-sir/markdown/LOADING.html 
and the steps for loading from CSV files. There maybe a bug, please check the workflow. 

Are there any other functions or classes I can make use of to create good data to feed the models at this point in time?

Thank you very much for your response. And great effort on the compartmental models.

**Comment by lisphilar** [comment]
Thank you for your response and could you share the codes and CSV file (or some lines with the column names of the data)?

**Comment by geeky-programer** [comment]
![Screenshot 2022-06-29 at 09 06 28](https://user-images.githubusercontent.com/23580744/176373541-d570e638-f3f1-4c4c-9233-98ef65da7c61.png)

**Comment by lisphilar** [comment]
Thank you for the details!
Just to confirm, did you try `DataLoader().jhu()` instead of `ExampleData(data)`?
Because you have actual records of COVID-19 and an instance of `JHUData` returned by `DataLoader().jhu()` calculates Infected internally.

**Comment by lisphilar** [comment]
With #1090, I'm writing some new classes, including `DataEngineer`. I didn't have much time to update the pull request these days, but I plan to merge it this week or next Saturday/Sunday.

**Comment by geeky-programer** [comment]
Ok. Much appreciate the work. Thank you

**Comment by lisphilar** [comment]
Dear @geeky-programer ,
Sorry for the delay, but I'm preparing documentations of the class `DataEngineer` (available with only development versions at this time). After completiong of writing notebooks, I will release the next stable version and update documentation (GitHub page).
