### ISSUE TITLE
Error in find change points with CovsirPhy 2.5.4-alpha

### ISSUE THREAD

**Issue by SM-ins** [lisphilar/covid19-sir#116]
Dear Lisphilar,
Thankyou for the updates.As You have  made a single scenario phase of India,we are unable to predict the future data...,I am getting following error now while executing predicting model.

ind_scenario.clear()
ind_scenario.add_phase(days=7)
ind_scenario.simulate().tail(7).style.background_gradient(axis=0)

NameError: Initial value of Susceptible must be specified in @y0_dict.

Please check it once...,if possible..

Thankyou.

**Comment by lisphilar** [comment]
Dear Rakesh,
Thank you for your feed-back.
I changed the code to fix #110 in GitHub, but new error occurred as you mentioned. I will fix this issue today and update the package in PyPI.

By the way, please edit "summary", "Codes and outputs" section etc. in the issue template. I think this is more useful for you.

**Comment by SM-ins** [comment]
Thanks...,i did the mentioned..

With regards,
Rakesh

**Comment by SM-ins** [comment]
> Dear Rakesh,
> Thank you for your feed-back.
> I changed the code to fix #110 in GitHub, but new error occurred as you mentioned. I will fix this issue today and update the package in PyPI.
> 
> By the way, please edit each "summary", "Codes and outputs" section etc. in the issue template. I think this is more useful for you.

Dear Lisphilar,
Please let me know how to divide the different phases in case of scenario matter as per own need.Kindly help me if possible.

With regards,
Rakesh

**Comment by lisphilar** [comment]
Dear Rakesh,
Thank you. I created issue #118 because this includes a new bug.

**Comment by lisphilar** [comment]
Dear Rakesh,
I fixed this issue in version 2.5.4
Please kindly confirm it.
Thank you!
