### ISSUE TITLE
[Revise] pyproject.toml contains obsolete dependencies

### ISSUE THREAD

**Issue by fpgmaas** [lisphilar/covid19-sir#1161]
## Summary of request

Not all dependencies listed in pyproject.toml are still actively used. I used [deptry](https://fpgmaas.github.io/deptry/) to scan the repository, and it returned the following output:

Output:

```
Warning: Failed to find corresponding package name for import `mpl_toolkits` in current environment.
pyproject.toml contains obsolete dependencies: ['better-exceptions', 'descartes', 'funcparserlib', 'mapclassify', 'scikit-learn', 'tabulate']
```

scikit-learn is incorrectly marked, which I have added as a [bug report](https://github.com/fpgmaas/deptry/issues/29) to the `deptry` project. The others indeed seem to be no longer actively required.

**Comment by fpgmaas** [comment]
`better-exceptions` was also marked as obsolete erroneously, since `deptry` does not support try-catch blocks yet, and it's only imported within a try-catch block. Added as a bug report to `deptry` as well.

**Comment by fpgmaas** [comment]
Thanks for your extensive feedback, and thanks for considering to add `deptry` as a development dependency! 

I have processed your proposed changes, and I have added the `deptry` configuration to `pyproject.toml`. In addition, I have added `scikit-learn` to the list of dependencies to ignore, since I have no solution for that problem yet, so this is now the [advised](https://github.com/fpgmaas/deptry/issues/29) workaround.

The parsing of try/except blocks is now added in `deptry` 0.2.1, so it no longer erroneously marks `better-exceptions` as a obsolete dependency.

**Comment by lisphilar** [comment]
Thank you for updating and I merged your pull request. This will be included in the next stable release.

I ran `deptry .` and I got the following message.

```Bash
Warning: Failed to find corresponding package name for import `mpl_toolkits` in current environment.
Succes! No obsolete dependencies found.
```

I created a issue for the warning https://github.com/fpgmaas/deptry/issues/34
"Succes" could be changed with "Success"?

**Comment by lisphilar** [comment]
With #1163, this was included in the test workflow.

**Comment by lisphilar** [comment]
With https://github.com/fpgmaas/deptry/issues/34, the warning was removed at deptry version 0.2.3. We will use version 0.2.3 with #1170.

@fpgmaas ,
Thank you a lot for your support!! :)
We can close this issue and I will contiue to follow the releases of your package.
