### ISSUE TITLE
[Fix] Running the unit tests clutters the project directory

### ISSUE THREAD

**Issue by fpgmaas** [lisphilar/covid19-sir#1173]
## Summary

Running the unit tests with `make test` clutters the project directory. Maybe it's possible to have these files downloaded to a separate directory, and delete them when pytest finishes or aborts? Maybe with the use of `try/finally`?

## Codes

```Python
make test
git status
```

## Outputs

```
?? covid_japan_metadata.csv
?? japan.csv
?? ne_10m_admin_1_states_provinces/
```

## Environment

- CovsirPhy version: master branch
- Python version: 3.9
- Installation: not applicable
- System: WSL Mac OS

**Comment by lisphilar** [comment]
Thank you for raising.
To avoid downloading files many times, I think downloaded files should be saved in "input" directory. With the current .gitignore configuration, this directory is not the target of `git statsus`. I will fix this with a pull request.

**Comment by lisphilar** [comment]
With #1178, `japan.csv" and "covid_japan_metadata.csv" created with `JapanData` class and test workflow will be moved to "input" directory from top directory.

Regarding "ne_10m_admin_1_states_provinces/", I have one idea. Because this is from [Natural Earth](https://github.com/nvkelso/natural-earth-vector) and published under [Public Domain](https://www.naturalearthdata.com/about/terms-of-use/), will it be better to include it in `covsirphy` as [geopandas does](https://github.com/geopandas/geopandas/tree/main/geopandas/datasets)?

**Comment by fpgmaas** [comment]
I think that sounds like a good solution!

**Comment by lisphilar** [comment]
Thank you and I will try to imprement it :)

Note:
- Add a script of downloading/updating the dataset to stable version publish workflow
- Save the file in covsirphy/gis/natural_earth directory with README.md (to explain the data source)
- Ensure `covsirphy` to include the dataset with pyproject.toml (using "include" option?)
- `covsirphy.gis.geometry._Geometry._natural_earth()` will read the saved files internally (with relative path from covsirphy directory?)
- Explain the workflow and data source in documentation

**Comment by lisphilar** [comment]
Because the dataset of the data source will be updated irregularly, the dataset will not be included in CovsirPhy. As a quick solution, the directory to save the files will be changed to "covsirphy/gis/Natural_Earth" directory.

**Comment by lisphilar** [comment]
@fpgmaas 
Solution was changed, but I tried to solve this issue. Any ideas or could you confirm that the files will not be created?

**Comment by fpgmaas** [comment]
Can confirm that the files are not showing up in `git status` after running `make test`. So the issue seems resolved!

**Comment by lisphilar** [comment]
Thank you for confirmation!
I will close this issue for release.
