### ISSUE TITLE
[Revise] Deptry 0.2.5 uses modified configuration

### ISSUE THREAD

**Issue by fpgmaas** [lisphilar/covid19-sir#1174]
## Summary

Deptry [0.2.5](https://github.com/fpgmaas/deptry/releases/tag/0.2.5) adds new functionality to identify missing or transitive dependencies. The `ignore_dependencies` is deprecated, and replaced with `ignore_obsolete`, `ignore_missing` and `ignore_transitive`. 

For this purpose, the configuration in `pyproject.toml` should be altered.

## Code

```toml
[tool.deptry]
ignore_obsolete = [
'tabulate'
]
ignore_directories = [
    'input.py', 'tests', '.venv'
]
```

**Comment by fpgmaas** [comment]
Optionally, we could pin the deptry dependency to a fixed version in this early phase of deptry's development.

**Comment by lisphilar** [comment]
Thank you!!
I will merge your pull request after replacing ">0.2.5" with "0.2.6" to fixt the version temporarily.
