### ISSUE TITLE
Failed in addition of past phase manually

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#118]
> Dear Rakesh,
> Thank you for your feed-back.
> I changed the code to fix #110 in GitHub, but new error occurred as you mentioned. I will fix this issue today and update the package in PyPI.
> 
> By the way, please edit each "summary", "Codes and outputs" section etc. in the issue template. I think this is more useful for you.

Dear Lisphilar,
Please let me know how to divide the different phases in case of scenario matter as per own need.Kindly help me if possible.

With regards,
Rakesh

_Originally posted by @SM-ins in https://github.com/lisphilar/covid19-sir/issues/116#issuecomment-660466109_

**Comment by lisphilar** [comment]
In version 2.5.3, an easy way to add past phase manually is the following.
"""Python
scenario = cs.Scenario(jhu_data, population_data, "India")
scenario.clear(include_past=True)
scenario.add_phase(end_date="01Jul2020")
```
However, this couses "ValueError: @start_date is Future, but @end_date is Past."

I will create a method to add a past phase without ValueError.

**Comment by SM-ins** [comment]
Dear @lisphilar ...,

Thank You...,Please let me know after creating it..

**Comment by lisphilar** [comment]
Dear Rakesh,
I fixed this issue in version 2.5.4
Please kindly confirm it with the following codes.

```Python
scenario = cs.Scenario(jhu_data, population_data, country="India")
scenario.remove()
scenario.add_phase(end_date="01May2020")
scenario.add_phase(end_date="01Jun2020")
scenario.add_phase()
scenario.summary()
```
or,
```Python
scenario.remove()
scenario.add_phase(days=30)
scenario.add_phase(days=30)
scenario.add_phase()
scenario.summary()
```

When `end_date` and `days` are not specified, the end date of the new phase will be the last date of the records.

Thank you!

**Comment by lisphilar** [comment]
`Scenaro.remove()` removes all past and future phase.

**Comment by SM-ins** [comment]
Dear Lisphilar,

Thank you so much for the help me..,both are working..,but there is one
more issue the starting date(17th Feb) and end date(14th July) is
fixed..,how can I change this as per my need...,please help if possible..

With regards,
rakesh

**Comment by lisphilar** [comment]
Dear Rakesh,
Thank you!
I created a new issue #126 to enable us to change the start date of phases.

I think the issue for end date is fixed in the latest version 2.5.4

Please use the following codes.
```Python
scenario = cs.Scenario(jhu_data, population_data, country="India")
scenario.remove()
scenario.add_phase(end_date="01May2020")
scenario.add_phase(end_date="01Jun2020")
scenario.summary()
```
`scenario.add_phase()` without `end_date`/`days` arguments will set the end date of the last past phase.

**Comment by SM-ins** [comment]
Thank you @lisphilar/covid19-sir
<reply@reply.github.com>  for
your response.But i am getting following error after executing above code:-

Name error:- name 'scenario'  is not defined.

Please check it once...



nnnsdkhhjsfn

nrio' is not defined

: name 'sceanrio' is not defined

**Comment by lisphilar** [comment]
Dear Rakesh,
`NameError: name 'sceanrio' is not defined` means that variable `scenario` was not defined.

You may performed `ind_scenario = cs.Scenario(jhu_data, population_data, country="India")` and please replace `scenario` with `ind_scenario`

**Comment by SM-ins** [comment]
Dear @lisphilar ,
Thanks for the response,i did as you mentioned:-

ind_scenario = cs.Scenario(jhu_data, population_data, country="India")
ind_scenario.remove()
ind_scenario.add_phase(end_date="01May2020")
# Change the start date of 1st phase
ind_sceanrio.change(phase="1st", start_date="01May2020")

but again I am getting same error as"ind_scenario is not defined".

**Comment by lisphilar** [comment]
Dear Rakesh,
Thank you.
Because this codes is for #126, I will reply you in #126
