### ISSUE TITLE
[Revise] deptry 0.2.9 is available

### ISSUE THREAD

**Issue by fpgmaas** [lisphilar/covid19-sir#1181]
`deptry` 0.2.9 is available. It has a few improvements over the currently used version:

- It adds a check for development dependencies that should be regular dependencies
- The argument `ignore_directories` is replaced with `exclude`, similar to e.g. configuration in `black`. This is because it also handles files, and not only directories.

I will open a PR soon, with the version fixed to `0.2.9` so the CI/CD pipeline won't break when a new version is released with changes that are not backwards compatible. Although I hope that will happen less often from now on.

**Comment by lisphilar** [comment]
Thank you! Your pull request was merged without any issues.
