### ISSUE TITLE
India scenario analysis: KeyError when Scenario.param_history()

### ISSUE THREAD

**Issue by SM-ins** [lisphilar/covid19-sir#125]
Dear @lisphilar ,

Initialy the code,i.e.  _ = ind_scenario.param_history(targets=["rho", "sigma"]).T was working but now it's throwing following error..,please help me if you wish..

KeyError: '@targets must be selected in Population, Rt.'

With regards,
Rakesh

**Comment by lisphilar** [comment]
Dear Rakesh,
Thank you for your information.
Please confirm that you have done `ind_scenario.estimate(cs.SIRF)` before ` _ = ind_scenario.param_history(targets=["rho", "sigma"]).T`

FYI:
Please edit or fill in the blanks of **each** section of issue template. Please kindly refer to the format of #106 and #126

**Comment by lisphilar** [comment]
I will change the error statement if `Scenario.estimate()` has not been performed.
Before: "KeyError: '@targets must be selected in Population, Rt.'"
After: "KeyError: Scenario.estimate() must be done in advance."

**Comment by lisphilar** [comment]
This will be included in "2.5.4-epsilon.75.125.126.130.133" and "2.6.0"
