### ISSUE TITLE
Code running problem

### ISSUE THREAD

**Issue by SM-ins** [lisphilar/covid19-sir#128]
Dear Lisphilar,

i was trying to run  ind_scenario.estimate(cs.SIRF) but it has been running since more than half an hour but I am not able to get the 
output..,5 phases got finished within 5 minutes but the 1st phase has got stuck..,initially there was no any such problem but now it has occurred.....

Main scenario: perform parameter estimation>
Running optimization with 4 CPUs...
	6th phase with SIR-F model finished 53 trials in 2 min 21 sec.
	2nd phase with SIR-F model finished 41 trials in 1 min 35 sec.
	4th phase with SIR-F model finished 33 trials in 1 min 38 sec.
	3rd phase with SIR-F model finished 32 trials in 1 min 59 sec.
	5th phase with SIR-F model finished 44 trials in 1 min 26 sec.
Please help me out if possible.

With regards,
Rakesh

**Comment by lisphilar** [comment]
Dear Rakesh,
Sorry for your inconvenience and this is a fatal error.

1. Please share the result of `ind_scenario.summary()` with me to reproduce the error in my environment.

2. Please try `ind_scenario.estimate(cs.SIRF, timeout=30, reset_n_max=1)`
This will limit the running time more tightly. (Default: timeout=60, reset_n_max=3)

**Comment by SM-ins** [comment]
Dear Lisphilar,

No need to be sorry dear,it's okey...,please find the result of the mentioned below:-

	Type	Start	End	Population
1st	Past	17Feb2020	20Mar2020	1339000000
2nd	Past	21Mar2020	10Apr2020	1339000000
3rd	Past	11Apr2020	01May2020	1339000000
4th	Past	02May2020	17May2020	1339000000
5th	Past	18May2020	31May2020	1339000000
6th	Past	01Jun2020	20Jul2020	1339000000

I tried ind_scenario.estimate(cs.SIRF, timeout=30, reset_n_max=1)..,but now new error is coming:-

<Main scenario: perform parameter estimation>
Running optimization with 4 CPUs...
	6th phase with SIR-F model finished 28 trials in 1 min 9 sec.
	4th phase with SIR-F model finished 14 trials in 0 min 58 sec.
	2nd phase with SIR-F model finished 14 trials in 1 min 7 sec.
	3rd phase with SIR-F model finished 13 trials in 1 min 10 sec.
	5th phase with SIR-F model finished 17 trials in 0 min 48 sec.


ZeroDivisionError: float division by zero

**Comment by SM-ins** [comment]
Dear @lisphilar ,

Now it's working..,i made some adjustment in phases..,sorry for troubling you too much...

With regards,
Rakesh

**Comment by lisphilar** [comment]
Dear Rakesh,
Great!
How did you find the way to adjust phase information?
This will be helpful to automate the process with this package.

**Comment by SM-ins** [comment]
Dear @lisphilar/covid19-sir
<reply@reply.github.com> ,

Thanks..,,actually whenever i was  taking 6 phases in case of India then
the first phase was getting stuck every time..,so reduced it to 5 phase and
minimise the gaps between the start date and end date of consecutive
phases..,then it ran but still I think that it's not the proper way...what
do you think...??

With regards,
Rakesh

**Comment by lisphilar** [comment]
Dear Rakesh,
Thank you for your discussion.
This needs further investigation with the latest version.

**Comment by SM-ins** [comment]
Dear Lisphilar,

You are welcome.
