### ISSUE TITLE
[Question] how to set data range with `Dynamics()` and `Dynamics.from_data()`

### ISSUE THREAD

**Issue by shik-design** [lisphilar/covid19-sir#1301]
### Checkbox

- [X] I agree to follow [code of conduct](https://lisphilar.github.io/covid19-sir/CODE_OF_CONDUCT.html) and to engage in discussion actively.
- [x] I agree to create a new issue with the other templates if developers request.

### Question

```
dyn_act = cs.Dynamics.from_data(model=cs.SIRModel, data=actual_df, name="None")
dyn_act.register().tail()
```

where will I run the above codes with `date_range=("01Jan2022", "30Jun2022")`

### What tried

```python
import covsirphy as cs
print(cs.__version__)


dyn_act = cs.Dynamics.from_data(model=cs.SIRModel, date_range=("01Jan2022", "30Jun2022"), data=actual_df, name="None")
dyn_act.register().tail()
```
```


### Additional Context

_No response_

**Comment by lisphilar** [comment]
We have two solutions.

1. Subset `actual_df` with `pandas.DatetimeIndex`
```Python
dyn_act = cs.Dynamics.from_data(model=cs.SIRModel, data=actual_df["2022-01-01":"2022-06-30"], name=None)
dyn_act.register().tail()
```

2. Initialize `Dynamics` instance without `.from_data()` class method
```Python
dyn_act = cs.Dynamics(model=cs.SIRModel, date_range=("01Jan2022", "30Jun2022"), name=None)
dyn_act.register(data=actual_df).tail()
```

Note that `Dynamics.from_data()` calls `Dynamics(...)` and `Dynamics.register(...)`, setting the min/max dates of `actual_df` as the date range automaticallly.
https://github.com/lisphilar/covid19-sir/blob/dfbac351ee3e2508678681b9a64c871fa24c319a/covsirphy/dynamics/dynamics.py#L115-L142

**Comment by shik-design** [comment]
Thanks a lot
