### ISSUE TITLE
[Docs] remove warning on README for using covsirphy with Google Colab

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#1314]
### Checkbox

- [X] I agree to follow [code of conduct](https://lisphilar.github.io/covid19-sir/CODE_OF_CONDUCT.html) and to engage in discussion actively.

### Suggested improvement of documentation

Confirm we can use `covsirphy` with Google Colab which uses Python 3.8, and remove the following warning on README.

Warning
We cannot use covsirphy on Google Colab, which uses Python 3.7. [Binder](https://mybinder.org/) is recommended.

Refer to https://github.com/googlecolab/colabtools/issues/2165

**Comment by lisphilar** [comment]
@mehrdadbn9
Could you try issues #1314 and #1304 if you have time?

**Comment by mehrdadbn9** [comment]
@lisphilar 
i would check if i could do  any help, i will let you know
