### ISSUE TITLE
[Docs] update the last year in citation, 2020-2022 to 2020-2023

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#1356]
### Checkbox

- [X] I agree to follow [code of conduct](https://lisphilar.github.io/covid19-sir/CODE_OF_CONDUCT.html) and to engage in discussion actively.

### Suggested improvement of documentation

"2020-2022" in the citation of `covsirphy` library and Japan-specific dataset should be updated to "2020-2023".

**Comment by mehrdadbn9** [comment]
hi if  suggestion is acceptable i can do it, i love to start contribute so when this issue confirmed assign me thanks

**Comment by lisphilar** [comment]
Thank you and I assigned you to this issue!

**Comment by deepgohil** [comment]
I would like to solve this issue.

**Comment by lisphilar** [comment]
@deepgohil 
Thank you for your pull request and I will merge #1357 (update in citation) after test.

@mehrdadbn9 and @deepgohil 
Please also update README.md: "Citation" section, `covsirphy/__citation__.py` and `docs/conf.py` file.

**Comment by mehrdadbn9** [comment]
#1364
