### ISSUE TITLE
Bug_IND_Scenario: error in get population value in Kaggle

### ISSUE THREAD

**Issue by SM-ins** [lisphilar/covid19-sir#137]
Dear Lisphilar,

A new problem has arised in case of executing  ind_scenario = cs.Scenario(jhu_data, pop_data, "India")
ind_scenario.records().tail().....,i am getting following error:-

KeyError: 'Please register population value for (country=India, province=None)

Please help me out if possible..

With regards,
Rakesh

**Comment by lisphilar** [comment]
Dear Rakesh,
Thank you very much!
I confirmed issue in Kaggle Notebook and fixed it in version 2.5.4-zeta.
