### ISSUE TITLE
[Bug] Wrong vaccination data

### ISSUE THREAD

**Issue by eguidotti** [lisphilar/covid19-sir#1373]
### Checkbox

- [X] I agree to follow [code of conduct](https://lisphilar.github.io/covid19-sir/CODE_OF_CONDUCT.html) and to engage in discussion actively.
- [X] I agree to create a new issue with the other templates if this is not a bug.
- [X] I used [the latest version of covsirphy](https://lisphilar.github.io/covid19-sir/markdown/INSTALLATION.html).

### Summary

Hi @lisphilar, I'm integrating your data in COVID-19 Data Hub and I've found an issue with the vaccination data.

Below I plot the `Vaccinated_1st` for `Location=Domestic` from your file: https://github.com/lisphilar/covid19-sir/blob/main/data/japan/covid_jpn_total.csv

![vacc](https://user-images.githubusercontent.com/24247667/222132746-5f8dd854-051b-4f69-92c0-49163dc82082.png)

It seems that the data are a mix of cumulative/non-cumulative counts (?)
For instance, on `2022-10-10` the number of people with 1 dose is 9744650, but on `2022-10-11` it is 857. And then on `2022-10-16` it is again 9745232.

How should I proceed? Thanks a lot!

### Reproducible example script

```python
This is an issue about the data, not the code
```

### The current outputs

```python
See picture above
```

### Environment

```markdown
This is an issue about the data, not the code
```

### Package manager (required if installation issue)

Others (commented)

### Platform (required if installation issue)

Others (commented)

### Additional Context

This is an issue about the data, not the code

**Comment by lisphilar** [comment]
Thank you for your kind notive.
Vaccinated_1st and Vaccinated_2nd were NON-cumulative values. Vaccinated_3rd counts were cumulative values.
With #1381, I converted Vaccinated_1st and Vaccinated_2nd to cumulative values.
(The last date is 04Feb2023. I will update the dataset in a day.)

**Comment by lisphilar** [comment]
Data updated. The number of cases: to 05Mar2023, Vaccinated: to 02Mar2023 per primary sources.

Additional infomation:
The primaly source has the number of cases with 4th/5th vaccine shots in Japan. Our dataset will provide the data with #1382.

**Comment by eguidotti** [comment]
Mmm it seems something strange is going on. I tried to plot the data (picture below) and Vaccinated 1 and 2 look weird. In particular, vaccinated 1 is decreasing while it should be cumulative now from my understanding

Thanks a lot for your efforts!

![Rplot](https://user-images.githubusercontent.com/24247667/223124516-799c991e-a2f8-4460-a663-b8ac323ad020.png)

**Comment by eguidotti** [comment]
Awesome! 

I just noticed that on `2022-01-24` the entry for `Hosp_require` seems to be a manual entry mistake. The value is `3222100` while I think it should be `322210`.

Except from that, I think this issue can be closed. I also checked the data at the prefecture level and they seem ok.

Thanks a lot for your help!
