### ISSUE TITLE
Vaccine_Scenario

### ISSUE THREAD

**Issue by SM-ins** [lisphilar/covid19-sir#176]
Dear Lisphilar,

i have some doubt regarding following output:-

                   
                 max(Infected)	argmax(Infected)	Infected on 17Aug2020	Fatal on 17Aug2020
No actions	232807	2020-03-23	                          104	                 57457
Lockdown	74113	2020-04-14	                         4197	                 37796
Medicine	       160879	2020-03-26	                           83	                          5919
Vaccine	        221598	2020-03-23	                           22	                          50508

Here, we see that in case of lockdown the no of max infected is less as compared to medicine and vaccine...,similar type of situations in other columns too...,i don't think that these columns are providing any valuable information...,the effect of medicine and vaccine is not looking effective..,what's your opinion?? Apart from that please provide me clear and full explaination  of these four rows and column attributes...,if possible...

With regards,
Rakesh

**Comment by lisphilar** [comment]
Dear Rakesh,
Thank you for your feed-back.
Please kindly note that the simulation is under the assumptions of parameter values.

I think the output of `Scenario.describe()` should include the parameter values to clearfy the assumptions. How do you think about this idea?

**Comment by SM-ins** [comment]
Dear Lisphilar,

Thanks for the response.Including parameters will be good idea..,it will might give better outlook...

**Comment by lisphilar** [comment]
Dear Rakesh,
I edited the code of `Scenario.describe()` to show the difference of reprodution numbers in version 2.6.0-iota.
