### ISSUE TITLE
[Docs] BibTex Format Citation Request

### ISSUE THREAD

**Issue by EnzeXu** [lisphilar/covid19-sir#1764]
### Checkbox

- [X] I agree to follow [code of conduct](https://lisphilar.github.io/covid19-sir/CODE_OF_CONDUCT.html) and to engage in discussion actively.

### Suggested improvement of documentation

I appreciate the dataset you’ve made available. It’s been extremely helpful for my work! However, I noticed that the repository lacks a BibTeX citation format, which would make it much easier to reference in academic publications. I understand there is no original published paper related to your dataset. However, you may create a website or github_repo reference like:
@misc{website_name,
  author       = {Author or Organization Name},
  title        = {Title of the Website or Page},
  year         = {Year of Publication or Last Update},
  url          = {https://www.example.com},
  note         = {Accessed: YYYY-MM-DD}
}

or

@misc{github_repo,
  author       = {Repository Author or Organization},
  title        = {Repository Title},
  year         = {Year of Publication or Last Update},
  url          = {https://github.com/username/repository},
  note         = {Accessed: YYYY-MM-DD}
}

And then you may add this BibTeX citation to the README. Thank you for your time and consideration!

**Comment by lisphilar** [comment]
@EnzeXu,
Thank you for using CovsirPhy and/or COVID-19 dataset for Japan.
Before add the format citation to documentation, followings will be help you.

### CovsirPhy

```
@misc{github_repo,
author = {Hirokazu Takaya and CovsirPhy Development Team},
title = {CovsirPhy version [version number]: Python library for COVID-19 analysis with phase-dependent SIR-derived ODE models},
year = {2020},
url = {https://github.com/lisphilar/covid19-sir),
note = {Accessed: YYYY-MM-DD}
}
```

### COVID-19 dataset in Japan

```
@misc{github_repo,
author = {Hirokazu Takaya},
title = {COVID-19 dataset in Japan},
year = {2020},
url = {https://github.com/lisphilar/covid19-sir/data/japan),
note = {Accessed: YYYY-MM-DD}
}
```

**Comment by EnzeXu** [comment]
@lisphilar 
Thank you very much for the information. We will reference CovsirPhy in our paper, as we’re not using the Japan dataset. Have a great week!

**Comment by lisphilar** [comment]
(I fixed minor errors on my last comment and add them to dcoumentation with #1765.)

**Comment by lisphilar** [comment]
(I fixed minor errors on my previous comment and add the citations to documentation with https://github.com/lisphilar/covid19-sir/pull/1765.)

**Comment by EnzeXu** [comment]
Sounds great! Thank you!
