### ISSUE TITLE
No updates are available for Kaggle dataset regarding the number of COVID-19 cases

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#261]
## What we need to document?
CovsirPhy has two data sources, but no updates are available for one dataset recommended in the documentation. We need to revise the documentation to inform users.

## Details
CovsirPhy has two data sources as explained in the following documentation.
https://lisphilar.github.io/covid19-sir/INSTALLATION.html

1. Kaggle dataset
In the early stage, CovsirPhy was developed using this dataset. Many thanks for SRK, the author!!
However, this dataset has not been updated since 24Sep2020. This leads improper simulation USA, Greece etc.
https://www.kaggle.com/sudalairajkumar/novel-corona-virus-2019-dataset/metadata

2. COVID-19 Data Hub
We can download this dataset with `covsirphy.DataLoader()` class. We need to use this dataset for our analysis. Analysis with Italy records is shown in the following documentation.
https://lisphilar.github.io/covid19-sir/usage_quickest.html

## Acknowledgement
Thank you for your suggestion, @Inglezos !

**Comment by lisphilar** [comment]
Dear @Inglezos,
The codes to download the dataset of COVID-19 Data Hub is as follows.
````Python
import covsirphy as cs
# Dataset preparation
data_loader = cs.DataLoader("input")
jhu_data = data_loader.jhu()
population_data = data_loader.population()
```

**Comment by Inglezos** [comment]
With these lines of code, the updated dataset of the "covid19datahub" team is downloaded and used, getting data from the JHU CSSE system.
The system should use directly and always as primary data source the "covid19datahub.io" source. Therefore, your kaggle notebook should be adjusted to reflect only this data source.

**Comment by lisphilar** [comment]
[The kaggle notebook](https://www.kaggle.com/lisphilar/covid-19-data-with-sir-model) was updated to use COVID-19 Data Hub as the data source.
Thank you!
