### ISSUE TITLE
Improve datasets preparation - setup automation

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#266]
## Summary of new feature - Problem description
This concerns an improvement of how the various datasets are prepared to be used. The problem is that it is unnecessarily complicated for the user how to set up all the required datasets. There is an `input/` folder, a `kaggle/input/` folder and some sub-folders inside the `kaggle/input/` folder. In order to get the system up and running, assuming no files in both files at first, the user has to manually download many datasets and put them manually into the appropriate folders.

Since `input.py` downloads the files as they are inside `input/`, extra overhead is added to the user, to manually create the folder structure and put the files in the respective folders or to edit manually the notebook code at the lines these paths are used.

The input.py script creates inside `input/` folder the files: 
     `OxCGRT_latest.csv`,
     `covid_jpn_total.csv`,
     `covid_19_data.csv`,
     `locations_population.csv`

If I comment out the "delete unnecessary files" lines inside the script, then these files are also added:
     `covid_jpn_metadata.csv`,
     `covid_jpn_prefecture.csv`,
     `COVID19_line_list_data.csv`,
     `COVID19_open_line_list.csv`,
     `time_series_covid_19_confirmed.csv`,
     `time_series_covid_19_confirmed_US.csv`,
     `time_series_covid_19_deaths.csv`,
     `time_series_covid_19_deaths_US.csv`,
     `time_series_covid_19_recovered.csv`.

But as I understand, all these are needed in the notebook code. Then why remove them in the first place during the script execution? (by default the script removes most of these files).

Anyway, assuming that we have all the above inside the `input/` folder, which then I copy-paste to the `kaggle/input/` folder, I try to run the notebook script. I use the `DataLoader()` as you said, so the `covid19th.csv` is created as well. But then the `population-pyramid` folder is still missing.

If I download this manually and delete the unnecessary sub-folder paths `kaggle/input/<sub-folder to delete>/*.csv` inside the code, then the only file missing is `Dataset_Italy_COVID_19.csv`. I download it manually. Then after all these I am ready with the datasets.

This is a lot of overhead work to be done manually by the user and at some points confusing. I mean in order to run fully line-by-line your notebook (not the quick usage guide!).

See also #267 .

## Solutions - Suggestions

- There is no need to exist both `input/` and `kaggle/input/` folders.
- The `input.py` script should create all the necessary folders and sub-folders (if exist) as well, download automatically all the required datasets that will be used and put them respectively inside these folders.
- The `population-pyramid` folder and data should also be created and downloaded by the script and not downloaded and placed by the user manually.
- The `Dataset_Italy_COVID_19.csv` file should also be downloaded and placed into the `input/` folder by the `input.py` script.
-  Finally, there is no need for sub-folders structure inside `input/` folder.

## Question
What are the `linelist*.csv` and `metadata*.csv` files? Why and how are they used inside the code? Are these necessary for the system to fully work?

**Comment by lisphilar** [comment]
`input.py` was revised to save Kaggle datasets you mentioned in `/kaggle/input/` directory.
Kindly confirm it.

**Comment by lisphilar** [comment]
`linelist*.csv` (case reports) is used to calculate a parameter of SEWIR-F model.
`metadata*.csv` is used in Japan scenario analysis.

`linelist*.csv` (case reports) is necessary to use SEWIR-F model, but this is not updated and non-Kaggle users cannot use it with CovsirPhy.
https://github.com/beoutbreakprepared/nCoV2019 will be an alternative. I will investigate it and create an issue.

**Comment by lisphilar** [comment]
Linelist of case reports will be discussed in #281
