### ISSUE TITLE
Wrong number of recovered cases for Greece and USA

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#268]
## Summary
The source `covid19datahub.io` has wrong source data about **recovered cases for Greece and USA** (at least) and wrong confirmed cases data for USA (source data are a little bit behind), compared to `worldometers.info` data.

I have already contacted the JHU systems by email (at jhusystems@gmail.com) regarding this wrong recovered cases data issue, but they still have not replied me back. For the recovered cases issue, I have suggested to the `covid19datahub.io` team to specifically process the recovered cases for Greece and USA (as far as I know only these two have this issue for the time being), as follows: `Recovered = Confirmed - Deaths - Active` at accumulative level. Then the daily change can be reflected as `Recovered[i] - Recovered[i-1]`. 

This is something that has to be done at least for Greece because the recovered data are stuck for months at a fixed value (1347).
Please check my comments (at bottom comments section) to the `covid19datahub.io` team at:
https://covid19datahub.io/articles/iso/GRC.html
https://covid19datahub.io/articles/iso/USA.html

Guidotti, after our discussion, has opened an issue at `JHU CSSE`:
https://github.com/CSSEGISandData/COVID-19/issues/3266

## Solution - Suggestions
- I propose to use as direct primary source the `worldometers.info` if possible, compare data with the `covid19datahub.io` ones and keep the largest number as valid (or something like that).
- It would be great if we could find credible active cases timeseries/historical data. If we do, then we can calculate the correct recovered data by ourselves.
- I have already sent an email to `worldometers.info` for information about licensing, because I think that they don't give their data for free/open source. This is probably going to cause us trouble acquiring active cases historical data. Maybe other data source needs to be found.

## Environment
- CovsirPhy version: 2.9.1
- Python version; 3.8
- Installation: Anaconda, Spyder, pip
- OS: Windows

**Comment by lisphilar** [comment]
Case reports (linelist) may be useful to calculate (estimate) the time to recover.

**Comment by Inglezos** [comment]
Yes maybe. Nevertheless, I think a credible recovered historical data source has to be found.

**Comment by lisphilar** [comment]
This may be solved by COVID-19 Data Hub, but it is very difficult because definition of "Recovered" and data collection system are not the same in all countries.

**Comment by Inglezos** [comment]
Yes, the reported recovered cases are the most problematic, but we have to handle them in the most efficient way we can.
- We had an update today, the CSSEGISandData team responded, see https://github.com/CSSEGISandData/COVID-19/issues/3266

**Comment by lisphilar** [comment]
Thank you for your communication with the team and notification to me.

We should
- keep eyes on the updates of the datasets,
- create data loader of linelist of case reports, and
- calculate recovery period in average/median with the linelist.

**Comment by Inglezos** [comment]
Regarding the JHU CSSE issue, we have updates, see their comment on their github issue (which they have now closed):

> Our recovery data comes directly from COVID Tracking Project and we cannot comment on the differences between their methodology at that of WorldoMeter. Of note, Worldometer double counts cases in several locations in the US (federal prisons, Navajo nation, etc.) so we tend to stay away from them for US data.
> 
> In regards to Greece, it appears that recovery data is now solely available from the government press conferences: https://eody.gov.gr/category/deltia-typoy/. Their machine-readable data does not include recoveries, which is why we have been carrying forward a static value. We have manually updated the recovered time series using these press releases as far back as this total is detailed. We will use these press releases moving forward.
>
As I saw in their updated data the recovered cases for Greece have been updated as well indeed.

**Comment by lisphilar** [comment]
Thank you for your kind notice.
For USA, we continue to use JHU/COVID-19 Data Hub via `DataLoader.jhu()`.

For Greece, we still have step-wise recovered values.
Is not calculated the number of recovered cases every day in Greece?
![grc_records](https://user-images.githubusercontent.com/7270139/97800247-142b4c80-1c77-11eb-8b3f-2b8566a3f172.jpg)

Date | Confirmed | Infected | Fatal | Recovered
-- | -- | -- | -- | --
2020/10/23 | 29057 | 8749 | 559 | 19749
2020/10/24 | 29992 | 9679 | 564 | 19749
2020/10/25 | 30782 | 10459 | 574 | 19749
2020/10/26 | 31496 | 11166 | 581 | 19749
2020/10/27 | 32752 | 12410 | 593 | 19749
2020/10/28 | 34299 | 10622 | 603 | 23074
2020/10/29 | 35510 | 11821 | 615 | 23074
2020/10/30 | 37196 | 13502 | 620 | 23074
2020/10/31 | 39251 | 15551 | 626 | 23074
2020/11/1 | 39251 | 15551 | 626 | 23074

**Comment by Inglezos** [comment]
As far as I know, Greece has not been reporting every day recovered cases; some other countries do that too unfortunately. I will try to find manually some data for that if I can and I will let you know.

**Comment by lisphilar** [comment]
OK, we will move forward to #269
