### ISSUE TITLE
Scenario.trend() and .estimate(): low accuracy in 0th phase

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#270]
## Summary of question
The initial phase, the 0th, is discarded from the estimator and therefore from the predictions? Because I see that for example Japan, India and USA ignore the 0th phase.

Is this happening because in that period the parameters exhibit huge RMSLE? Is the threshold 1.5 RMSLE in order to include a phase? How can this be adjusted? Can we fix this somehow to include these phases as well in our predictions? It is important for analysis completeness.

## Summary of **bugs**
- Spain has serious issue. The RMSLE for the 6th phase, which is mid May - October (**almost all the active pandemic period!**), is 36 >> 1.5 and thus it is ignored in the estimator/predictions. This is major bug and has to be resolved somehow. No substantial analysis can be done for Spain. Why is this caused?
- And for India this means that we ignore almost 5 months of analysis and for USA 3 months!

![spain_weird_predictions](https://user-images.githubusercontent.com/36845191/97127958-be6d1680-1743-11eb-9ce5-7cb228fac473.png)
(for the Spain weird infected/deaths prediction curves see #273).

![india_normal_predictions_graph](https://user-images.githubusercontent.com/36845191/97186662-42f28000-17aa-11eb-9da1-97380c512ded.png)
![usa_normal_death_predictions_graph](https://user-images.githubusercontent.com/36845191/97127956-bd3be980-1743-11eb-92e3-62799fd138fd.png)

- In addition, the fact that at least a phase, most times the initial, is ignored, might be happening and for other countries. We have to deal with this in general. For example, Greece analysis and predictions also ignore the first 4 months:

![greece_normal_death_predictions](https://user-images.githubusercontent.com/36845191/97128515-3556df00-1745-11eb-8149-ae3061a4a5c0.png)

## What have you tried?
All the relative kaggle notebook code for the various countries analyses.

## Environment
- CovsirPhy version: 2.9.1
- Python version; 3.8
- Installation: Anaconda, Spyder, pip
- OS: Windows

**Comment by lisphilar** [comment]
I thought this was solved with #228 , but we need to check it.

**Comment by Inglezos** [comment]
> I thought this was solved with #228 , but we need to check it.

Not only investigation for the 0th phase has to be made, but also for every phase that has large RMSLE. Spain analysis is very problematic.

**Comment by lisphilar** [comment]
Please help with me to try `Scenario.estimate(cs.SIRF, timeout=120)` mentioned in #274 to find the cause. We need to improve Estimator class or prolong the default value of time limit.

**Comment by lisphilar** [comment]
Actually, 0th phase is included, but not shown in the figure of `Scenario.simulate()`. This is because low accuracy of 0th phase.

**Comment by Inglezos** [comment]
Sure it is a low accuracy issue as well, but why in the first place the 0-th phase has such long duration? Maybe further analysis for the 0-th phase has to be done additionally.
Besides that, why is this strange behavior for Spain happening? Are there any irregularities perhaps in the Spain data?

**Comment by lisphilar** [comment]
I will look into the issues (0th phase with long duration and Spain issue) tomorrow using the new method discussed in #319 .
I think the root cause of "0th phase with long duration" is in the following codes of `ChangeFinder.run()`.
```Python
# Sampling to reduce run-time of Ruptures
samples = np.linspace(0, series.index.max(), len(self.sr_df), dtype=np.int64)
series = series[samples]
```

**Comment by lisphilar** [comment]
With Spain data, I found:
- `ChangeFinder.run()`: codes for sampling should be improved so that we can sub-divide 0th phase,
- `Estimator.run()` is not good at parameter estimation with sharply change of Infected records (9th  phase) at this time.

https://gist.github.com/lisphilar/aee856adc40e0706b7ad9951cae20a1a#file-spain-scenario_10nov2020-ipynb

**Comment by lisphilar** [comment]
Do you have any ideas to improve `ChangeFinder.run()`?
Please see my pull request #326 .

**Comment by lisphilar** [comment]
`ChangeFinder.run()` was updated in version 2.10.0-lambda. `Estimator.run()` will be updated in #291 or new issues.

**Comment by Inglezos** [comment]
So, for further subdivision of the initial phase, what must be improved, what can be investigated?

**Comment by lisphilar** [comment]
Yes, `ChangeFinder.run()` should be updated with new issues, if necessary.
