### ISSUE TITLE
Greece weird death cases predictions

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#271]
## Summary
The death cases predictions for Greece are not accurate and I have the following weird phenomenon; if I run:

## Codes and outputs:
      gr_scenario = cs.Scenario(jhu_data, pop_data, "Greece")
      gr_scenario.records().tail()
      _ = gr_scenario.trend()
      gr_scenario.summary()
      gr_scenario.estimate(cs.SIRF)
      gr_scenario.summary()
      _ = gr_scenario.history_rate()
      gr_scenario.clear()
      gr_scenario.add(days=7)
      gr_pred = gr_scenario.simulate() -> observe gr_pred

then the deaths predictions sometimes are very wrong and not only that, but they follow a triangular distribution, they increase, decrease and increase again (which is obviously wrong, the confirmed, deaths and recovered predictions must always increase).

![greece_weird_death_predictions](https://user-images.githubusercontent.com/36845191/97128241-7c90a000-1744-11eb-9c03-c22b9caabe6b.png)

But sometimes the deaths predictions seem normal with the first execution. I don't know why, this occurs at random execution trials. Please further investigate.

![greece_normal_death_predictions](https://user-images.githubusercontent.com/36845191/97128239-7bf80980-1744-11eb-9fa4-ad9e2c3c36ed.png)
(for the weird constant recovered prediction curve see #268).

## Environment
- CovsirPhy version: 2.9.1
- Python version; 3.8
- Installation: Anaconda, Spyder, pip
- OS: Windows

**Comment by lisphilar** [comment]
Please help with me to try `Scenario.estimate(cs.SIRF, timeout=120)` mentioned in #274 to find the cause.

**Comment by lisphilar** [comment]
With version 2.10.0-mu, the output is
https://gist.github.com/lisphilar/909d29d27da988dd49efe19bc1d95822#file-greece_13nov2020-ipynb
