### ISSUE TITLE
Russia, Spain, France, UK, Netherlands weird infected/death predictions

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#273]
## Summary
- For Russia and Spain, there are strange confirmed cases and death cases predictions plots. Predictions for confirmed and death cases are totally off by far. Weird triangular prediction curves behavior.

![russia_weird_predictions](https://user-images.githubusercontent.com/36845191/97129978-db581880-1748-11eb-8717-fca5b526645c.png)
![spain_weird_predictions](https://user-images.githubusercontent.com/36845191/97129974-dabf8200-1748-11eb-8ae5-a9bf4a7d94fc.png)
(for Spain phase analysis gap after mid-May see #270).
Same weird triangular curves behavior as in #271 for Russia and Spain. Please further investigate.

- For France, predictions for confirmed and **death** cases are generally off by far as well.

![france_weird_confirmed_death_predictions](https://user-images.githubusercontent.com/36845191/97130272-9da7bf80-1749-11eb-8e6e-a56eca6b796f.PNG)
![france_weird_death_predictions](https://user-images.githubusercontent.com/36845191/97130276-a00a1980-1749-11eb-8a31-3a7713a7bf38.PNG)

- UK and Netherlands have weird only deaths predictions (off by far). They seem to exhibit though the same weird triangular curves behavior as in #271 as well:

![uk_weird_death_predictions](https://user-images.githubusercontent.com/36845191/97130510-4d7d2d00-174a-11eb-8e7b-67889695950b.PNG)
![netherlands_weird_death_predictions](https://user-images.githubusercontent.com/36845191/97130505-4bb36980-174a-11eb-8539-19fbc4679f07.PNG)

## Codes and outputs:
Typical kaggle notebook countries analyses code:
       `<country>_scenario = cs.Scenario(jhu_data, pop_data, "<country>")`
       `<country>_scenario.records().tail()`
       `_ = <country>_scenario.trend()`
       `<country>_scenario.summary()`
       `<country>_scenario.estimate(cs.SIRF)`
       `<country>_scenario.summary()`
       `_ = <country>_scenario.history_rate()`
       `<country>_scenario.clear()`
       `<country>_scenario.add(days=7)`
       `<country>_pred = <country>_scenario.simulate()` -> observe `<country>_pred`

## Environment
- CovsirPhy version: 2.9.1
- Python version; 3.8
- Installation: Anaconda, Spyder, pip
- OS: Windows

**Comment by lisphilar** [comment]
Please help with me to try `Scenario.estimate(cs.SIRF, timeout=120)` mentioned in #274 to find the cause.

**Comment by Inglezos** [comment]
I have rerun with v2.11 some tests for Russia and UK:
The estimated confirmed (Russia, UK) and deaths cases (UK) are totally incorrect. And UK recovered data are very low (until now only 3100, while there are 2.500.000 confirmed).
Also why the `score()` for Russia for example gives only something small? I mean the difference between the actual and the simulated confirmed cases is huge: i.e. for 14Nov20 -> confirmed_actual = 1887836, confirmed_simulated = 2820574 => diff = 932.738 which is 49.4% error.

**Comment by lisphilar** [comment]
Russia:
`snl.score(metrics="RMSLE", variables=["Confirmed"])` gave me `3.13`. This is not a small error.
S-R trend analysis does not show errors, but parameter estimation failed. 
The last figures with `for phase in snl.summary().index:    snl.estimate_accuracy(phase)` indicates that `Fatal` is accurately estimated, but `Infected` and `Recovered` are not. When parameter estimation, we may need to emphasize the error of Infected than Fatal. (At this time, we use RMSLE score as error and this treats the all variables equally.)
https://gist.github.com/lisphilar/48ad567ed09206eecf644c3eb4618eb8#file-russia_20201116-ipynb

UK:
This will be discussed in #340.

**Comment by lisphilar** [comment]
The results with version 2.13.1-alpha are in https://gist.github.com/lisphilar/8f64aca428a3eb065c8c39ef827b3fc5

We move forward to #354 (and new issues) to improve the accuracy of parameter estimation.
