### ISSUE TITLE
Other SIR models status - SIRX integration possibility

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#275]
## Summary of question
Besides the SIRF model, the other models (SEIRF, SEWIR, SEWIRF, etc) models you mention, are indeed reliable and can be fully used without any problems? Are they fully functional, implemented and tested? Will you demonstrate them for specific countries scenarios in the notebook analysis soon? Did you have the time to investigate and integrate perhaps the SIRX model? ->
http://rocs.hu-berlin.de/corona/docs/forecast/model/
https://github.com/michibo/COVID-19-JHU-CSSE-data-SIRX-evaluation
https://nbviewer.jupyter.org/github/michibo/COVID-19-JHU-CSSE-data-SIRX-evaluation/tree/master/

## Environment
- CovsirPhy version: 2.9.1
- Python version; 3.8
- Installation: Anaconda, Spyder, pip
- OS: Windows

**Comment by lisphilar** [comment]
SIR-FV model needs the number of vaccinated people, but we do not have it.
This is used for scenario analysis at this time.
https://lisphilar.github.io/covid19-sir/usage_theoretical.html#Scenario-analysis-with-theoretical-data

SEWIR-F: we need to calculate rho1 and rho2 with case reports. (linelist).
https://www.kaggle.com/lisphilar/covid-19-data-with-sir-model#SIR-F-with-exposed/waiting-cases

**Comment by Inglezos** [comment]
> SIR-FV model needs the number of vaccinated people, but we do not have it.
> This is used for scenario analysis at this time.
> https://lisphilar.github.io/covid19-sir/usage_theoretical.html#Scenario-analysis-with-theoretical-data
> 
> SEWIR-F: we need to calculate rho1 and rho2 with case reports. (linelist).
> https://www.kaggle.com/lisphilar/covid-19-data-with-sir-model#SIR-F-with-exposed/waiting-cases

So essentially, the SIR-FV and SEWIR-F models cannot be used at all for the moment on actual data, because for SIR-FV we don't have any actual data on vaccinated people and for SEWIR-F we can't calculate these two parameters without proper linelist data?

**Comment by lisphilar** [comment]
Yes at this moment.
#281 will be discussed in advance to use SEWIR-F model or new models.

**Comment by lisphilar** [comment]
What is the advantage of SIR-X model?
https://arxiv.org/abs/2002.07572
http://rocs.hu-berlin.de/corona/docs/forecast/model/

**Comment by Inglezos** [comment]
From what I know, the only advantage is that it adds an extra compartment X for the quarantined people. With this, we can have an overview of how the number of the quarantined people changes. The SIRX model can easily be extended to SIRF-X model (I had done that on April before abandoning the whole model because of the author note at
http://rocs.hu-berlin.de/corona/docs/forecast/results_by_country/ )

I don't know if it will actually add any extra functionality to our pre-existing SIRF model, but I thought it would be useful to have that X compartment for the quarantined people.

**Comment by lisphilar** [comment]
It is difficult to use X/quarantined because we have no records of the number of quarantined cases/people.
I suggest that we use quarantine rate as a factor (Sq, Wq, Iq) of rho parameter.
Please refer to the Kaggle notebook.
https://www.kaggle.com/lisphilar/covid-19-data-with-sir-model#Factors-of-model-parameters

**Comment by Inglezos** [comment]
If this implementation for quarantine factor is something relatively easy, okay yes, otherwise I think that we can close this issue and move on from SIRX idea completely. This is not very important for now.

**Comment by lisphilar** [comment]
Thank you, we will move forward to #379 and new issues.
