### ISSUE TITLE
New dataset: Linelist of case reports

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#281]
## What dataset you need?
As mentioned in #275 , a dataset regarding linelist of case reports is necessary for analysis with SEWIR-F model.

## How will you use the dataset for your analysis?
For SEWIR-F model, we need to calculate rho1 and rho2 with linelist of case reports.
https://www.kaggle.com/lisphilar/covid-19-data-with-sir-model#SIR-F-with-exposed/waiting-cases

rho1 is tau per latent period. Latent period in average will be calculated as time from exposed date to onset date.
rho2 is tau per waiting period. Waiting period in average will be calculated as time from onset date to confirmation date.

## Example datasets
https://github.com/beoutbreakprepared/nCoV2019

The latest dataset is published in https://github.com/beoutbreakprepared/nCoV2019/tree/master/latest_data

Original paper:
Xu, B., Gutierrez, B., Mekaru, S. et al. Epidemiological data from the COVID-19 outbreak, real-time case information. Sci Data 7, 106 (2020). https://doi.org/10.1038/s41597-020-0448-0

**Comment by lisphilar** [comment]
Dear @Inglezos ,
Do you have any ideas to download the .tar.gz file from
https://github.com/beoutbreakprepared/nCoV2019/blob/master/latest_data/latestdata.tar.gz

**Comment by Inglezos** [comment]
Do you mean something like that?
https://stackoverflow.com/questions/54289735/use-python-requests-to-download-an-compressed-tar-gzfile-and-unzip-it-using-tar

**Comment by lisphilar** [comment]
Thank you.
This linelist has onset date, confirmed date and outcome (fatal or discharged=recovered) date. We can estimate how many days patients take to recover. Then, we can estimate theta, sigma and rho2 in SEWIR-F model.

**Comment by lisphilar** [comment]
WIth #301, classes in `covsirphy/cleaning` were refactored. `COVID19DataHub` class was created to clean `DataLoader` class. Then, test codes and docs were updated.

**Comment by lisphilar** [comment]
With version 2.11.0-alpha #338, `DataLoader.linelist()` method was added.
```Python
data_loader = cs.DataLoader()
linelist = data_loader.linelist()
linelist.cleaned()
```
