### ISSUE TITLE
Tool to confirm a new model can be used for parameter estimation

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#290]
## Summary of this new feature
When we will create a new model to understand the outbreak deeply, we need a tool to confirm that the models can be used for parameter estimation. This is related to #276 

c.f. If the model has too many parameters and few measurable varibles, parameter estimation fails.

## Solution
A solution is as follows.
1. Simulate the number of cases with an user-defined parameter set. 
2. Perform parameter estimation with the theoretical data (the dataset created with step 1).
3. Compare the user-defined parameter set and estimated parameter set.
4. Repeat with anather set of parameters.

When the difference of the two parameter sets was small, we will confirm that the model can be used for parameter estimation.

Notes:
- Theoritical data has only one phase.
- Step 1 will be performed with `ExampleData` class.
- Step 2 will be performed with `Scenario.estimate()` class.
- For step 3, we need to decide the metrics. RMSLE etc.

Usage of `ExampleData` class is documented in https://lisphilar.github.io/covid19-sir/usage_theoretical.html

**Comment by Inglezos** [comment]
Okay, now I understand what exactly you meant by performing validation on theoretical data. I agree with that solution.

**Comment by lisphilar** [comment]
Yes, estimated paramerters (x parameter set you got finally) could be different from the applied x parameter set if the model or prameter estimation sstem have some errors.

**Comment by lisphilar** [comment]
With #292, I added `covsirphy.analyse.model_validator.ModelValidator` class in version 2.9.1-gamma.
With following codes, we can validate some models.
```Python
import covsirphy.as cs
# Set the number of parameter sets (n_trials=8 as default), random seed (seed=1 as default)
validator = cs.ModelValidator(n_trials=8, seed=1)
# Validate models
# timeout=60 as default: time-out of parameter estimation
# allowance=(0.98, 1.02) as default: this is the same as that of Scenario.estimate()
# while max(simulated) < 0.98 * max(theoritical) or max(simulated) > 1.02 * max(theoritical),
# parameter estimation continues
validator.run(cs.SIR, timeout=60, allowance=(0.98, 1.02)
validator.run(cs.SIRD, timeout=60, allowance=(0.98, 1.02)
validator.run(cs.SIRF, timeout=60, allowance=(0.98, 1.02)
# Summarize
validator.summary()
```
Methods of visualization and scoring are not prepared currently, but we can analyze the results using the output of `validator.summary()`, a `pandas.DataFrame`.

Example code are in `example/model_validation.py` script.

We need to improve SIR-F model and the estimator because the difference of "Rt" (setting) and "Rt_est" (estimated) is small, but the difference of parameter values are not small.

**Comment by lisphilar** [comment]
Can we close this issue about model validator and move to #291 ?

**Comment by Inglezos** [comment]
Yes I think we can close this issue now.
