### ISSUE TITLE
Trends visualization - missing colored lines for Greece

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#309]
## Summary
In case of Greece trends analysis, I noticed that there are missing colored lines from the plot figure.
The trends RMSLE scores are fine (<< 0.1), but two colored lines are missing, for the 1st and 9th phase.
![greece_trends_missingColors](https://user-images.githubusercontent.com/36845191/98308969-0147ad80-1fd2-11eb-8808-1462dbc290fa.png)

## Code
```
gre_scenario = cs.Scenario(jhu_data, population_data, "Greece")
gre_scenario.records().tail()
gre_scenario.trend()
```

## Environment
- CovsirPhy version: 2.10.0-alpha.refactor.291
- Python version: 3.8
- Installation: Anaconda, Spyder, pip
- System: Windows

**Comment by lisphilar** [comment]
I investigated S-R trend of Greece with `Trend` class.
https://gist.github.com/lisphilar/3ac6029346ca240391553c47f0a98e2c

2nd phase:
Colored line is actually shown, but not visible because the delta R from the start date to end date is small.

9th phase:
Colored line is not shown. I do not think this is a fatal error, but we may need to show a line with `x=fixed R` line.

**Comment by Inglezos** [comment]
Since a color line is included in the legend section, then it should be depicted on the figure as well. No it is not a critical bug, but since we are already reworking the trends analysis, I thought it would be useful to mention this in order to be fixed.

**Comment by lisphilar** [comment]
The root cause of this is the same as #269. The number of recovered cases is not updated at daily-basis. We need to solve #269 rather than revising `Trend` and `ChangeFinder` class.

**Comment by Inglezos** [comment]
Yes I agree, the root cause is the wrong recovered cases and the further handling we have to implement in that level.

**Comment by lisphilar** [comment]
#269 solved this bug. With version 2.10.0-epsilon and records to 08Nov2020, the output will be as shown in the nex figure.
![grc_trend](https://user-images.githubusercontent.com/7270139/98530665-9690bd80-22c2-11eb-87ec-007b9c67b339.jpg)
