### ISSUE TITLE
Scenario class: scoring method of phase setting and parameter estimation

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#319]
## Summary of this new feature
We have evaluation system to evaluate accuracy of S-R trend analysis and that of parameter estimation in each phase respectively. However, we need a system to evaluate accuracy of phase setting and parameter estimation of all phases with one score. This was discussed in #279 with @Inglezos .

## (Optional) Solution
Create `Scenario.score()` method to calculate the score of accuracy. The difference of actual and simulated number of cases will be evaluated.
Scoring metrics can be selected from https://scikit-learn.org/stable/modules/model_evaluation.html

**Comment by lisphilar** [comment]
I created pull request #320 and merged it.
Please find the details of `Scenario.score()` with #320 and use the following codes.

```Python
snl.trend()
all_phases = snl.summary().index.tolist()
snl.disable(phases=all_phases[:-2])
snl.estimate(SIRF)
snl.score(metrics="RMSLE", variables=None)
```
`metrics` argument can be selected from "MAE", "MSE", "MSLE", "RMSE" and "RMSLE" (default).
`valiables` argument is a list of variable names and means the variables to use in calculation. If this is None (default), ["Infected", "Fatal", "Recovered"] will be used. "Confirmed", "Infected", "Fatal" and "Recovered" can be used in `variables`.

If you need another method or argument, please discuss it here and create a pull request if possible.

**Comment by lisphilar** [comment]
Dear @Inglezos ,
Please confirm the previous comment to know `Scenario.score()` method. I will close this issue.

**Comment by Inglezos** [comment]
The score is the total for all phases. Can I get somehow only the score for a specific phase (for example the last one) or even for specific dates period or for last <x> days?

**Comment by lisphilar** [comment]
`Scenario.disable()` method disables selected phases and these phases will not be used for parameter estimation and scoring.
```Python
snl.trend()
# Get nameas of all phases
all_phases = snl.summary().index.tolist()
# Disable all phases except the last two phases
snl.disable(phases=all_phases[:-2])
snl.estimate(SIRF)
snl.score()
```

**Comment by Inglezos** [comment]
So in order to just see the score for the last phase, I have to disable all the previous phases even at the estimator? This does not seem logical. The display of the score and the estimation analysis should not be connected. One thing is to simulate cases for phases and another independent should be to just display the score for specific phases I think.

**Comment by lisphilar** [comment]
I will update `Scenario.score()` method to add `phases` argument.
Please review my codes with #333 .

**Comment by lisphilar** [comment]
With pull request #333 and #337 , I added `phases` argument and `past_days` argument to `Scenario.sclore)` method. I will close this issue to release new stable version 2.11.0, but we continue the discussion about score calculation in #279 and new issues.

```Python
snl = cs.Scenario(...)
snl.trend()
snl.estimate(cs.SIRF)
# Calculate RMSLE score with all phases
snl.score(metrics="RMSLE")
# Calculate RMSLE score with 1st phase
snl.score(metrics="RMSLE", phases=["1st"])
# Calculate RMSLE score with the records for the past 30 days
snl.score(metrics="RMSLE", past_days=30)
```
