### ISSUE TITLE
ModuleNotFoundError: No module named 'better_exceptions' in installation

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#32]
Summary:
When installed CovsirPhy with pip command, "ModuleNotFoundError: No module named 'better_exceptions'" occurs and we cannot install this package.
This error was mentioned as a comment of [Kaggle notebook](https://www.kaggle.com/lisphilar/covid-19-data-with-sir-model).

CovsirPhy version 2.2.2

Codes and outputs:
```
pip install git+https://github.com/lisphilar/covid19-sir#egg=covsirphy
```
This code causes the following error.
```
Collecting covsirphy from git+https://github.com/lisphilar/covid19-sir#egg=covsirphy
  Cloning https://github.com/lisphilar/covid19-sir to /tmp/pip-build-y0_kp_8r/covsirphy
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-y0_kp_8r/covsirphy/setup.py", line 3, in <module>
        setup()
...
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-build-y0_kp_8r/covsirphy/covsirphy/__init__.py", line 6, in <module>
        import better_exceptions
    ModuleNotFoundError: No module named 'better_exceptions'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-y0_kp_8r/covsirphy/
```

Environment:
Python 3.6.4, pip, WSL.

**Comment by lisphilar** [comment]
For pip user, the following command may fix the error.
```
pip install "git+https://github.com/lisphilar/covid19-sir#egg=covsirphy"
```
I enclosed the URL with quotation marks to prevent `#egg=covirsphy` from being read as a comment.

**Comment by KartikeySharma** [comment]
Hi
I am @kartikeysm2001 and I am the one who pointed out this error. I am a pip user, and the command line you provided which worked on your local environment, didn't work for me.

**Comment by lisphilar** [comment]
Dear @KartikeySharma ,
Thank you for your feed-back.
It seems dependencies could not be installed. I will investigate that matter.

Here is another way to use this package with `pipenv`, not `pip` tool.
```
git clone https://github.com/lisphilar/covid19-sir.git
cd covid19-sir
pip install wheel; pip install --upgrade pip; pip install pipenv
export PIPENV_VENV_IN_PROJECT=true
export PIPENV_TIMEOUT=7200
pipenv install --dev
```
Sorry for the inconvenience.

**Comment by lisphilar** [comment]
The steps to use this package is as follow.

Currently, this package requires a Kaggle API key to download the recommended datasets.
Please open your profile page in kaggle and find account tab. Then, please find API > "Create New API Token", download "kaggle.json" and save it in covid19-sir directory.
![how-to-download_Kaggle-API-key](https://user-images.githubusercontent.com/7270139/85222478-49d14680-b3f6-11ea-8ed8-1f4c3a23cab6.jpg)

Run the next command in covid19-sir directory.
```
mkdir input
pipenv run python -m input
```
The datasets will be downloaded in `covid19-sir/input` directory.
(We are considering how to get datasets, not using Kaggle API. See #26 )

Example codes are in `covid19-sir/example` directory.
Please run `pipenv run python -m example.dataset_jhu` etc. Output files will be cretated in `covid19-sir/example/output/dataset_jhu` etc.

**Comment by lisphilar** [comment]
Dear @KartikeySharma ,
I found the cause (dependency packages were imported before installation of denpendeincies) and fixed it.
Please confirm with `pip install "git+https://github.com/lisphilar/covid19-sir#egg=covsirphy"`

**Comment by KartikeySharma** [comment]
Dear @lisphilar 
Thank you so much for the update and I am happy to inform you that it worked!
Thank you!

**Comment by lisphilar** [comment]
Dear @KartikeySharma ,
Thanks a lot for your cooperation!
If you find any other errors or need enhancement, please let us know using GitHub issues/Kaggle comments.

Best Regards,
Lisphilar

**Comment by KartikeySharma** [comment]
Sure. It would be my pleasure!

Best wishes
Kartikey

**Comment by lisphilar** [comment]
Becuase the error was fixed for pip users, this issue will be closed.
If you find another installation errors, please create new issues.
Thank you.
