### ISSUE TITLE
ensure_country_name() selects random country - use countries abbreviations

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#356]
## Summary
For example, if I call `usa_scenario = cs.Scenario(jhu_data, population_data, "USA")`, with `USA` argument, the `ensure_country_name()` function selects wrong country data. I suggest country abbreviations to be used (I remember in previous versions these were used, why were they removed though? Was it when the kaggle datasets were removed? And that affected countries abbreviations as well somehow?) and USA acronym to be added in `name_dict`:
```
    def ensure_country_name(self, country):
        ...
        # Special
        name_dict = {
            "UK": "United Kingdom",
            "South Korea": "Korea, South",
            "Ivory Coast": "Cote d'Ivoire",
            "USA": "United States",
        }
```
For example, if I call:
```
gre_scenario = cs.Scenario(jhu_data, population_data, "GR") or
gre_scenario = cs.Scenario(jhu_data, population_data, "gr") or
gre_scenario = cs.Scenario(jhu_data, population_data, "GRC") or
gre_scenario = cs.Scenario(jhu_data, population_data, "grc") or
gre_scenario = cs.Scenario(jhu_data, population_data, "Greece") or
gre_scenario = cs.Scenario(jhu_data, population_data, "GREECE")
```
it should be valid input and select the correct country data, according to the predetermined country abbreviations.
Of course in case of wrong input, for example
`gre_scenario = cs.Scenario(jhu_data, population_data, "gre")`, it should throw an error saying "invalid country" etc.

**Comment by lisphilar** [comment]
Thank you for your kind notice.
I updated the codes and test codes with 
Please confirm it with the latest development version.

**Comment by Inglezos** [comment]
Great thank you, it works fine. We can close this issue then.
