### ISSUE TITLE
Visualization of daily new cases method

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#367]
## Summary of this new feature
It would be useful to add a new method for visualization of reported daily new cases (confirmed, deaths, recovered), as part of data exploration analysis, besides from total cases plot. It would be also a good idea to include extra features/parameters such as 3-day and 7-day moving average smoothing, just like in worldometers.info:
![image](https://user-images.githubusercontent.com/36845191/100548942-a3c51a80-3278-11eb-8bbc-f1420567886f.png)
![image](https://user-images.githubusercontent.com/36845191/100548949-ade71900-3278-11eb-91d3-47acd43f4950.png)
![image](https://user-images.githubusercontent.com/36845191/100548956-b93a4480-3278-11eb-9d94-4938b3588121.png)

**Comment by lisphilar** [comment]
Which do you need?
- `Scenario.records_diff(variables=["Confirmed", "Fatal", "Recovered"], window=3)`
- `Scenario.records_diff(variable="Confirmed", window_values=[1, 3, 5])`

**Comment by Inglezos** [comment]
A mix of both, a function where I can pass either Confirmed, Fatal, Recovered and select the window, either 1, 3 or 7.

**Comment by lisphilar** [comment]
Busy charts will be shown if both of the arguments are lists.

**Comment by Inglezos** [comment]
Hmm on second thought there is no point in using multiple windows at the same time, the plot will be very messy.
So I think the first option is more appropriate, multiple variables but single window.

**Comment by lisphilar** [comment]
With #371, `Scenario.records_diff(variables=None, windows=7, show_figure=True, filename=None)` was created in version 2.12.0-zeta.
`variables` will be selected from Confirmed, Infected, Fatal and Recovered.
If None was set as `variables`, ["Confirmed", "Fatal", "Recovered"] will be used.

With #370, `JHUData.records()` was created for refactoring.

**Comment by lisphilar** [comment]
With #372, for maintenance, `DataHandler` class was created as the parent of `Scenario` class in version 2.12.0-eta. Some methods for data loading and complement was moved to this new class. No impact on usage of `Scenario` class.
