### ISSUE TITLE
Show the kind of complement was done with `JHUData.subset_complement()`

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#382]
## Summary of this new feature
`JHUData.subset_complement()` was created to complement recovered data, but it is difficult for users to know what kind of complement was done for the dataset. It is necessary to show the kind of complement with stdout or the title of figures.

## (Optional) Solution
- Stdout the kind of complement.
- Show the kind of complement in the title of `Scenario.records()` and `Scenario.records_diff()`.

Then, developers may need to monitor the list of countries where complement performed as mentioned in #380.

**Comment by lisphilar** [comment]
Dear @Inglezos ,
I'm writing a pull request for the second solution "Show the kind of complement in the title of `Scenario.records()` and `Scenario.records_diff()`".
Titles of `Scenario.reocrds()` figures could be
- "Cases over time (with fully complemented recovered data)"
- "Cases over time (with partially complemented recovered data)"
- "Cases over time (with recovered data complemented to show monotonic increasing)"

What do you think?

**Comment by Inglezos** [comment]
The second solution is the ideal one, showing the complement kind directly into the plot name. Yes I think these figure names are appropriate for informing the user.

**Comment by lisphilar** [comment]
Thank you, the third title will be revised.
OK, we will update figure names, not standard outputs.

P.S.
If you have time, please check the statuses of the other issues to select issues which will be fixed in version 2.13.0.

**Comment by lisphilar** [comment]
Dear @Inglezos ,
With #390, titles of `Scenario.records()` with complemented data were updated.
With Netherlands records,
![nld_records](https://user-images.githubusercontent.com/7270139/101502925-e2637f00-39b4-11eb-8973-1b49d5fc5233.jpg)

**Comment by lisphilar** [comment]
FYI:
With #391, methods for complement in `JHUData` class were moved to new class `covsirphy.cleaning.jhu_complement.JHUDataComplementHandler` class for refactoring.

When we update complement tools, we will
- create/update methods of this class,
- update `._protocol` method and
- update class variable `.STATUS_NAME_DICT`, if necessary.

**Comment by Inglezos** [comment]
Great thank you, this is enough I think, now we can close this issue.

**Comment by lisphilar** [comment]
I found that
- confirmed value decreased from 2020-06-18 to 2020-06-19 and monotonic increasing was broken
- fatal value decreased from 2020-06-23 to 2020-06-24 and monotonic increasing was broken
https://gist.github.com/lisphilar/258ddea8f0f2604fdc58b9145fb528ab

I do not know why the values were changed in the raw data, but the behavior of complement method is correct.

**Comment by lisphilar** [comment]
However, `\n` should be added to the title.

**Comment by Inglezos** [comment]
Oh I thought that we would inform the user only about the recovered complement/monotonic handling, not for the other two.

**Comment by lisphilar** [comment]
Sorry... I omitted monotonic handling for confirmed/fatal, refering the titles.
Monotonic handling for confirmed/fatal was included before this change.

**Comment by lisphilar** [comment]
Becuase complement of confirmed and fatal reocrds impacts on the result of trend analysis and so on, users should be notified when confirmed/fatal values were complemented.
