### ISSUE TITLE
DataLoader.jhu() replaces wrong last day recovered data in Japan internally

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#383]
## Summary
In covid19dh.csv, for the current/last day, the recovered is 0 for some reason, even though the previous day has ordinary records. Is this something we should handle somehow or should we contact the covid 19 datahub team?
This leads incorrectly to zeroing all the recovered data fields inside `_complement_non_monotonic`, thus applying incorrectly full complement after.

**Comment by lisphilar** [comment]
Yes, recovered values you mentioned are sometimes 0.
To solve this issue, I moved my Kaggle dataset for Japan to https://github.com/lisphilar/covid19-sir/data/japan and created `DataLoader.japan()` method.
Records at prefecture (province) level will be removed at this version, but we can replace the records in `DataLoader.jhu()` with the following script.
```Python
jhu_data = data_laoder.jhu()
japan_data = data_loader.japan()
jhu_data.replace(japan_data)
```
If users will not be confused, we can call `DataLoader.japan()` in `DataLoader.jhu()` automatically.

**Comment by Inglezos** [comment]
All this is unnecessary overhead for the user I think and confusing.
It is preferable the jhu dataloader to automatically use the proper japan dataset (including japan() call if necessary).

**Comment by Inglezos** [comment]
I just tried it. Yes it solves the problem in `_complement_non_monotonic()` on one hand, but nevertheless it is fully complemented.

**Comment by lisphilar** [comment]
With #385 and #386, `DataLoader.jhu()` calls DataLoader.japan() internally to replace Japan dataset of COVID-19 Data Hub with that of https://github.com/lisphilar/covid19-sir/tree/master/data at country and prefecture (province) level.

The primary source of COVID-19 Data Hub collects data in a different way from my dataset, and it is difficult to fill in the blanks with values of my dataset. I use Government-announced values, but they use prefecture-announced values to calculate total values in Japan.

Updating my dataset at daily basis (when I'm not on business trips) is not harder for me than maintaining this Python package. Please advertise CovsirPhy in social media to accerate communication in CovsirPhy project. I sometimes use Twitter for advertisement.
