### ISSUE TITLE
[Discuss] Questions about the SIRF hyperparameter optimization example

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#394]
## Summary of question
1. For SIRF Hyperparameter optimization example, why are the estimated parameters so much different than the expected? Is this bad or this is simply just another set of solutions for the parameters, which lead to the same case results? I get for theta = 0.0195 (expected is 0.002) and for kappa = 0.0032 (expected is 0.005).

2. What does the trajectory plot exactly mean? I see that there is not a single solution set.
For this plot I get:
![sirf_example_parameters](https://user-images.githubusercontent.com/36845191/101619817-6f8dee80-3a1c-11eb-9989-ef1688058652.png)

but you have something totally different in the kaggle notebook results for SIRF example:
![image](https://user-images.githubusercontent.com/36845191/101619949-9a784280-3a1c-11eb-8503-c0d834c1273d.png)

**Comment by lisphilar** [comment]
Yes, low accuracy of parameter estimation with SIR-F is the problem to solve. It may be necessary to change the system of parameter estimation with SIR-F model. We have only four observed variables to estimate four parameters.

The trajectory is for hyperparameter optimization with Optuna package.
- Optuna suggest a parameter set and calculate error value (in CovsirPhy, RMSLE)
- To minimize the error value, Optuna suggest a new parameter set
- Repeats
The figure shows all parameter sets. CovsirPhy uses the last parameter set as the parameter set of a phase.

Please provide the codes and results with `Scenario.summary()`.

**Comment by Inglezos** [comment]
I'm just running the `sirf_model.py` example from the `example/` folder. The first image of the results is from the `example/output/sirf_model` folder.

**Comment by Inglezos** [comment]
> The trajectory is for hyperparameter optimization with Optuna package.
> 
> * Optuna suggest a parameter set and calculate error value (in CovsirPhy, RMSLE)
> * To minimize the error value, Optuna suggest a new parameter set
> * Repeats
>   The figure shows all parameter sets. CovsirPhy uses the last parameter set as the parameter set of a phase.
>
Yes I mean how the plots are read? For example the rho-sigma plot (row=2, column=3) what does it mean?

**Comment by lisphilar** [comment]
In the second graph, points of rho-sigma plot are concentrated because hyperparameter optimization (minimization of the error by updating parameter set) was successfully completed.

In the first graph, points of rho-sigma plot are not concentrated because hyperparameter optimization was not done and parameter set in each step was randomly selected without minimization of error.

The cause of the second figure should be investigated.

**Comment by Inglezos** [comment]
Is there something wrong with the examples and the code? Or a general bug of the system?
Can you please investigate this in order to find a solution? First rerun the code to compare results.

**Comment by lisphilar** [comment]
The following result indicates theta and kappa of SIR-F model is estimated with lowa accuracy. They are elated to the same variable (Fatal).

  | rho | sigma | theta | kappa
-- | -- | -- | -- | --
SIR-F | 0.203457 | 0.074732 | 0.019557 | 0.003262
set | 0.2 | 0.075 | 0.002 | 0.005

With class menthod `covsirphy.ode.sirf.SIRF.param_range`, the value range of theta and kappa is set as (0, 1). The estimator suggest parameter values within this range. I think this is too wide to get the parameter values with high accuracy.

WIth the same class method, value range of rho is in (30%, 70%) quantile of  `- population * Susceptible.diff() / Susceptible / Infected`. Value range of sigma is in (30%, 70%) quantile of `Recovered.diff() / Infected`, accoridng to ODE equation of SIR-F model.

Do you have any ideas to narrow the value range of kappa and theta with the dataset?

**Comment by Inglezos** [comment]
So to get this straight, which results are valid, mine or yours in kaggle? Why they differ? Did I do something wrong in the code or my results are correct? But the important thing is why this came up now? I mean at some point it gave the result you had, which is more accurate. Nevertheless, with this parameters, the model seems to make good estimation of the example cases, why is that?

**Comment by Inglezos** [comment]
Could it mean that there is not a unique solution? Perhaps one parameter set corresponds to some simulated cases, but the inverse, these cases if they are analyzed, can lead to more than one solutions.

**Comment by lisphilar** [comment]
I re-runed the Kaggle Notebook and I get the following figure. This is expected.
![__results___102_0](https://user-images.githubusercontent.com/7270139/102011186-15778b00-3d86-11eb-99ea-ac5a0c346058.png)

However, in Google Colab, the same script produced the different figure with unknown reason.
Plese refer to https://gist.github.com/lisphilar/df00c797b1b3e6041e1efce5b4b1eb3e

> Could it mean that there is not a unique solution? Perhaps one parameter set corresponds to some simulated cases, but the inverse, these cases if they are analyzed, can lead to more than one solutions (which is the parameter set). Could both solutions be correct?

Please provide the details.

**Comment by Inglezos** [comment]
How is this possible? The results should not be different. So for some reason me and collab have the same weird results. Could the cores be the problem? How many are you using?
I think this is a high priority problem, because it could affect total model performance.

>Please provide the details.
>
I don't have specific details, it's just a thought.

**Comment by lisphilar** [comment]
Kaggle Notebook: 4 CPUs, expected figure
Google Colab: 2 CPUs, weired
Local PC: 8 CPUs, weired

The number of cores does not affect on the results because estimation in one phase is performed with single core.

Becuase SIR and SIR-D do not show the weired figures, we many need to investigate covisrphy/ode/sirf.py

**Comment by Inglezos** [comment]
I got a little confused, which one shows the weird results, collab or your pc?
https://gist.github.com/lisphilar/df00c797b1b3e6041e1efce5b4b1eb3e is your pc results, Kaggle's or collab's?

Could something go wrong when we had changed the `timeout` and `timeout_iteration` arguments values in `simulation.estimator()` ?

Or this has to do with the `sirf.py` file exclusively?

**Comment by lisphilar** [comment]
The gist notebook is the result of Collab.
The result in Kaggle Notebook is in https://www.kaggle.com/lisphilar/covid-19-data-with-sir-model
The result in my local PC with example/sirf_mode.py is here.
![estimate_history](https://user-images.githubusercontent.com/7270139/102013533-27602a80-3d94-11eb-8d92-e32924ca8297.png)


  | rho | sigma | theta | kappa | tau | Rt | alpha1 [-] | 1/alpha2 [day] | 1/beta [day] | 1/gamma [day] | RMSLE | Trials | Runtime
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
SIR-F | 0.203457 | 0.074732 | 0.019557 | 0.003262 | 1440 | 2.56 | 0.02 | 306 | 4 | 13 | 0.097295 | 2636 | 3 min  1 sec
set | 0.2 | 0.075 | 0.002 | 0.005 | 1440 |   |   |   |   |   |   |   |  

Because `timeout=180` and `timeout_iteration=10` are default values of `Estimator.run()` as well as Scenario.estimate()`, I think this is not related to this issue...

**Comment by lisphilar** [comment]
Kaggle notebook and the Colob notebook uses `Scenario.estimate()`, but example/sirf_model.py uses `Estimator` class directly. Could I update example/sirf_model.py to use `Scenario.esitimate()`?

**Comment by Inglezos** [comment]
Which one is more correct? If this were the cause, then collab would be same with kaggle; but this does not happen.

**Comment by lisphilar** [comment]
The result in my Kaggle Notebook is expected (more correct).

**Comment by Inglezos** [comment]
Yes of course that seems more correct, but I meant which is the best way to call estimator, using `Scenario.estimate()` or directly the `Estimator` class?

**Comment by lisphilar** [comment]
Sorry for misunderstanding.
Because we use `Scenario` class as the interface of CovsirPhy at this time, it is preferred to call `Scenario.estimate()` to avoid confusion.

**Comment by Inglezos** [comment]
Yes I agree, but why the different behavior?
Nevertheless, the problem unfortunately remains I think right?

**Comment by lisphilar** [comment]
The problem remains. I'm reading codes (`Scenario.estimate()`, `PramTracker.estimate()`, `MPEstimator`, `PhaseUnit.estimate()` and `Estimator`), but I do not have any ideas to solve this issue.

**Comment by lisphilar** [comment]
Actually, example/sirf.py and so on are not suitable for example codes.
How to crearte theoritiacal (example with user-defined parameter values) is documented in https://lisphilar.github.io/covid19-sir/usage_theoretical.html

We `ModelValidator` class to validate models.

**Comment by Inglezos** [comment]
What does this mean? That we should not run parameter estimation on the example codes?

**Comment by Inglezos** [comment]
Ohhh I just got what you mean, you say that we should use the `ModelValidator` for the example codes and not the actual estimator!

**Comment by lisphilar** [comment]
Yes, sirf.py etc. should be replaced with example/model_validation.py and https://lisphilar.github.io/covid19-sir/usage_theoretical.html

**Comment by Inglezos** [comment]
So what is the purpose then of `sir_model.py`, `sird_model.py`, `sirf_model.py`, `sirfv_model.py`, sewirf_model.py`? What the estimator fails for these examples?

**Comment by lisphilar** [comment]
The files were created to show the usage of `ExampleData` class when we did not have example/model_validation.py and https://lisphilar.github.io/covid19-sir/usage_theoretical.html

I think the roles of the files are over and we remove these files from example folder.

sir_model.py, sird_model.py: not failed
sirf_model.py: Not failed because accuracy is high, but there is a room to improve SIR-F paramter estimation
sirfv_model.py, sewirf_mode.py: parameter estimation should not be applied because the number of parameters is too larger than that of measurable variables.

**Comment by Inglezos** [comment]
Okay just to understand the general picture, we have a problem with the estimator, the kaggle notebook got the plots right, while me, you and collab have weird estimations for SIRF example. Is the root cause for this the fact that we should use the model validator instead or not? Will this solve the problem?
Because if not, then I would say that SIRF failed if we still get the same weird results, different than kaggle's assumed correct ones.

**Comment by Inglezos** [comment]
In order to realize if this works, how can we get from the `model_validation.py` the respective plot for "Trajectory of parameter values in hyperparameter estimation" and the "estimated accuracy" for SIRF? I mean the respective plots that correspond to the following kaggle plots:
![image](https://user-images.githubusercontent.com/36845191/102102416-72ca1580-3e34-11eb-9d37-0fe9a658b5f1.png)
![image](https://user-images.githubusercontent.com/36845191/102102456-81183180-3e34-11eb-9baf-5841a64cc7fd.png)

The `model_validation.py` must be reworked in order to save these plots as images as well.

**Comment by Inglezos** [comment]
Only then we can compare the results and realize if ModelValidator usage solves the problem indeed.

**Comment by Inglezos** [comment]
But unfortunately, from some first runs I see that the estimated and actual parameters differ in the saved `long_restricted.csv` logfile.

**Comment by lisphilar** [comment]
`ModelValidator` does not have the method to show the plots, but `units_estimated[0]._estimator.history(filename)` and `units_estimated[0]._estimator.accuracy(filename)` may create the figures becuase `units_estimated` is a instance of `covsirphy.phase.phase_unit.PhaseUnit` class.

**Comment by lisphilar** [comment]
I ran  model_validation.py and also found that estimated and actual parameter values show large difference, while SIR and SIR-D successed.
We need to revise `SIRF` class to improve accuracy of estimation., including `param_range` method.

**Comment by Inglezos** [comment]
Yes that is not the cause.
alpha1 parameter in SIRF and SEWIRF is in [1/min] or dimensionless?

**Comment by Inglezos** [comment]
alpha1 parameter in SIRF and SEWIRF is in [1/min] or dimensionless?
Because it is dimensionless, since it expresses a probability, then it should not be named "mortality rate", it confuses, because rate has dimensions [1/min].

**Comment by lisphilar** [comment]
Sorry, alpha1 is dimentionless and documentation should be revised.

**Comment by Inglezos** [comment]
Shall we name this "direct fatality probability"?

**Comment by lisphilar** [comment]
I think I used "probability of cases fatal before confirmed". Anyway, we need to revise the term with clear expression.

**Comment by lisphilar** [comment]
I agree with the idea we use "direct".

**Comment by Inglezos** [comment]
And in Control factors of effective contact rate beta1 section, in f1 equation, what is the " s " variable before " c " at the end?

**Comment by Inglezos** [comment]
Actually, wow!, all these control factors for beta, gamma, alpha, where did you find them? Did you come up with this analysis by yourself ??? :O

**Comment by Inglezos** [comment]
These control factors about beta1, gamma and alpha2 concern only SEWIRF model or are more general and apply to SIRF as well?

**Comment by lisphilar** [comment]
I and some Kagglers discussed and found control factors. The controll factors are for SIR-F. ("Exposed" and "Waiting" are variables in SEWIR-F model, but we can use "exposure" and "waiting for diagnosis" as controll factors in SIR-F model.) Yes, with new issues, we can create features of CovsirPhy to discuss parameter values deeply with cotroll factors.

Do you have any ideas regarding improvement of `SIRF` class?

**Comment by Inglezos** [comment]
Do you have any references about these equations or the various control factors?
So the control factor analysis for beta1 of the SEWIRF applies to beta of the SIRF as well, and gamma, alpha2 analysis of SEWIRF applies to gamma, alpha2 of SIRF as well? I mean the same control factors are for both models for beta, beta1, gamma, alpha2, right?

No, I don't have currently any ideas to improve SIRF class. Could something be going on with the timeout, trials or n_jobs values?

**Comment by lisphilar** [comment]
> Do you have any references about these equations or the various control factors?

I did not find references except for SIR, (SIR-D) and SEIR model, but we my need to read all comments of the Kaggle Notebook...

> In "Control factors of effective contact rate β1" section, in f1 equation, what is the " s " variable before " c " at the end? As I see there is no description for this factor.

Oops, "s" should be removed."s" is not in the next equation "beta1 = 1/49 {}...".

> So the control factor analysis for beta1 of the SEWIRF applies to beta of the SIRF as well, and gamma, alpha2 analysis of SEWIRF applies to gamma, alpha2 of SIRF as well? I mean the same control factors are for both models for beta, beta1, gamma, alpha2, right?

Yes, except for beta. Beta in SIR-F model is the function of beta1, beta2 and beta3.

> No, I don't have currently any ideas to improve SIRF class. Could something be going on with the timeout, trials or n_jobs values?

Update of timeout/the number of trial seems not impact on performance.

In `SIRF.param_range`, value range of the parameters are set.
Range of rho in SIR-F is (30%, 70%) quantile of "- n * (dS/dt) / S / I".
Range of sigma is (30%, 70%) quantile of "(dR/dt) / I".

However, range of theta is (0, 1) and the range of kappa is (0, 1).
Can we restrict the value range of theta and kappa?

**Comment by Inglezos** [comment]
>Yes, except for beta. Beta in SIR-F model is the function of beta1, beta2 and beta3.
>
So for SIRF beta, we could say that it has at least the control factors of SEWIRF's beta1 ? No need to get an equation, just to determine what factors affect beta.

>However, range of theta is (0, 1) and the range of kappa is (0, 1).
>Can we restrict the value range of theta and kappa?
>
Perhaps yes, in the same way with rho and sigma, restricting them to a quantile? Can you try that?

**Comment by lisphilar** [comment]
> You mean we can say beta (from SIRF) = f(beta1,beta2,beta3) (from SEWIRF) ?

Yes.

> Perhaps yes, in the same way with rho and sigma, restricting them to a quantile? Can you try that?

I'm trying theta = (0, 0.01) etc., but performance was not improeved...
We need to find alternative ways to update `Estimator` and `SIRF` class.

**Comment by Inglezos** [comment]
(also update alpha1 in SEWIRF, is dimensionless [-])

**Comment by lisphilar** [comment]
How shall we proceed this issue?

**Comment by Inglezos** [comment]
I am not sure. Maybe this can be integrated into 354 issue? Or is it related to the example model only?

**Comment by lisphilar** [comment]
This is related to #354 and an issue for SIR-F model and parameter etimation.
We will move forward to #354.

**Comment by Inglezos** [comment]
As I noticed just now in the latest kaggle notebook, the plot there is the same now with ours, the seemingly wrong one.

**Comment by lisphilar** [comment]
We did not change the codes related to parameter estimation and scripts of the section of the Kaggle Notebook....
Could updating dependencies impact on them...?

**Comment by lisphilar** [comment]
This is not a problem in itself, cut-off of long estimation could be implemented.

**Comment by Inglezos** [comment]
So what caused the different behavior? The long runtime?

**Comment by lisphilar** [comment]
Simply Optuna is strugging to find out the best parameter values. The graph is normal. We need to give Optuna hints to find the best params with new ideas and end interation when RMSLE score does not change for the last iterations.
