### ISSUE TITLE
[New] method of `JHUData` to know what kind of complement was done for subset for each country

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#401]
## Summary of this new feature
To monitor effectivity and safety of complement on JHU subset, we need to know what kind of complement was done for JHU subset for each country.

## (Optional) Solution
New method will return
| Country | Province | Monotonic_confrimed | Monotonic_fatal | Monotonic_recovered | Full | Partial |
| --- | --- | --- | --- | --- | --- | --- |
| Netherlands | - | False | False | False | True | False |

**Comment by lisphilar** [comment]
Dear @Inglezos ,
Would you mind if I assgn issues regarding complement, including documentation and this issue, to you?

**Comment by Inglezos** [comment]
No I don't mind, just I don't know when I will find time to do them. I am not sure about documentation also (I haven't written any).

**Comment by lisphilar** [comment]
Thank you.
I will release version 2.14.0 on 31Dec2020, but you need not stick to this timeline.

Documentaion:
Please edit "The number of cases (JHU style)" section of examples/usage_dataset.ipynb file in this repository to document overview of complement and this new method of this issue. When merged, I will deploy it to https://lisphilar.github.io/covid19-sir/usage_dataset.html using Semaphore CI.

**Comment by Inglezos** [comment]
So the user will call for example `jhu_data.new_method(country)` and this info will be returned?

**Comment by lisphilar** [comment]
Yes, but it will accept `country=None` to show all countries' results. This will useful when we monitor the impact of changing complement methods.

**Comment by Inglezos** [comment]
Yes but which countries? All of them?
This means that scenario analysis has to be run individually for each one of them

**Comment by lisphilar** [comment]
It will be useful if we can call this method from `Scenario` class, but please create a method of `JHUData`, not `Scenario` class (`DataHandler` class), as the first step.
`country=None` (or `countries=list[str] or None`) means `countries = self._cleaned_df[self.COUNTRY].unique().tolist()` because we need to monitor complement statuses of all/subset of countries. The output will be `pandas.DataFrame` with country name index.

**Comment by Inglezos** [comment]
Created pull request #472.
New method `show_complement()` in `JHUData` class was created for returning the kind of complement that was done for JHU subset for all the available countries or for specified country/countries.

**Comment by lisphilar** [comment]
Thank you very much for hard work!
#472 (and #485 just for refactoring) was merged.

I commented on your pull request to add `Avilability` column to the output. However, I reconsidered the changes and this column is not necessary because this column will be False only when users set the country/province name mistakenly. Sorry for bother you.

To remove `Availability` column, I created pull request #487. Kindly review it.

**Comment by lisphilar** [comment]
#487 was merged and we can close this issue.
We will move forward to #478.
