### ISSUE TITLE
SIRD example estimator error

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#402]
## Summary
Upon running sird_example from examples folder,  an error occurs:
```
File "C:\Users\ingle\Anaconda3\envs\py38\lib\site-packages\seaborn\distributions.py", line 305, in _compute_univariate_density
    warnings.warn(msg, UserWarning)
UserWarning: Dataset has 0 variance; skipping density estimate.
```
And then the execution terminates.

**Comment by lisphilar** [comment]
Example code without line 12 `warnings.simplefilter("error")` raises `UserWarning` and correct outputs.
I think this error can be ingnored. This error is from `UserWarning` in `seaborn`.
If you agree, I will supress this `UserWarning` in `Estimator.accuracy()`.

**Comment by lisphilar** [comment]
I created pull request #410 to supress `UserWarning`. Please review it.

**Comment by Inglezos** [comment]
Yes, we can suppress this if this is not related to a general model error; I approved and merged the change.
