### ISSUE TITLE
Example SIRFV model errors

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#417]
## Summary
I am trying to run the example `sirfv_model.py`, but it throws the warning:
"DeprecationWarning: Passing `np.nan` to mean no clipping in np.clip has always been unreliable, and is now deprecated. In future, this will always return nan, like it already does when min or max are arrays that contain nan. To skip a bound, pass either None or an np.inf of an appropriate sign." and stops the execution.
If I comment out the line `warnings.simplefilter("error")`, then it throws the error:
"ValueError: Domain error in arguments."

**Comment by lisphilar** [comment]
I created pull request #418. Please review it.

**Comment by Inglezos** [comment]
I approved the deprecation warning fix. Nevertheless, I think the SIRFV model has other more serious problems. The results I get are:
![estimate_history](https://user-images.githubusercontent.com/36845191/102083193-db58c880-3e1b-11eb-812a-62c9b9e0d9c3.png)
![estimate_accuracy](https://user-images.githubusercontent.com/36845191/102083183-d7c54180-3e1b-11eb-8c95-a30c496e12e7.png)

**Comment by lisphilar** [comment]
Yes, SIRF-V is not suitable to parameter estimation.
Variables: 5 (S, I, R, F, V)
Parameters:  5 (theta, kappa, rho, sigma, omega)

**Comment by Inglezos** [comment]
So can we do something to improve this? Or we have to use SIRFV only for theoretical scenarios and never for estimation and on actual data?

**Comment by Inglezos** [comment]
Also, regarding the medicine scenario, I remember you had said something about Italy medicine scenario example some time ago, about some medicine parameters that were wrong. Seeing the kaggle section, I realize that the main and medicine plots are essentially the same, without major differences in max(I) or max(F). This seems wrong.

**Comment by lisphilar** [comment]
Yes, I think vaccine data is necessary. As you know, vaccination starts/will start in USA and UK.

Medicine paramamters are not "wrong", just not based on the latest papers. In the Kaggle notebook, I calculated the parameter values in the future phases using the results of papers manually.

**Comment by Inglezos** [comment]
Why there is no difference between the two scenarios (I mean for max(Fatal) and max(Infected))?
![image](https://user-images.githubusercontent.com/36845191/102099057-8b383100-3e30-11eb-9ec3-a134432d0dcd.png)
![image](https://user-images.githubusercontent.com/36845191/102099128-a2771e80-3e30-11eb-8e77-45745d165d85.png)

**Comment by lisphilar** [comment]
The new parameter values (sigma_med and kappa_med in the Kaggle Notebook) are applied only on the future phase. Becuase max(Fatal) and max(Infected) were the data in the past phases, max(Fatal) and max(Infected) are as the same values as that of main scenario.

**Comment by Inglezos** [comment]
Okay, but what is the difference, how medicine scenario improves the situation, according to these plots?

**Comment by lisphilar** [comment]
I found `ita_scenario.clear(name="Medicine")` was removed from In[124]. I will rerun the notebook today. This may solve the problem. If not, this is because the parameter change is too small to impact on the near future values.
