### ISSUE TITLE
[Fix] Scenario.records() create a figure with Infected/Fatal/Recovered but Confirmed included in the returned dataframe

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#438]
## Summary
Only Infected, Fatal and Recovered columns are included in the figure of `Scenario.records()`, but returned dataframe includes Confirmed as well as the three columns.

## (Optional) Related classes
- `covsirphy.Scenario`
- `covsirphy.DataHandler`

## Codes and outputs:
```Python
import covsirphy as cs
# Dataset preparation
data_loader = cs.DataLoader("input")
jhu_data = data_loader.jhu()
population_data = data_loader.population()
# Scenario analysis
snl = cs.Scenario(jhu_data, population_data, "Japan")
# Get records
snl.records().tail()
```

  | Date | Confirmed | Infected | Fatal | Recovered
-- | -- | -- | -- | -- | --
311 | 2020/12/13 | 177287 | 25439 | 2562 | 149286
312 | 2020/12/14 | 179653 | 26121 | 2585 | 150947
313 | 2020/12/15 | 181870 | 25708 | 2643 | 153519
314 | 2020/12/16 | 184042 | 25807 | 2688 | 155547
315 | 2020/12/17 | 187103 | 26077 | 2739 | 158287

![Figure_0](https://user-images.githubusercontent.com/7270139/102622409-5277bf00-4184-11eb-9d3a-a627f6e3ada2.png)

## Environment
- CovsirPhy version: 2.13.2
- Python version; 3.8
- Installation: pipenv
- System: WSL (Ubuntu)

**Comment by lisphilar** [comment]
With pull request #422,
The dataframe will be

  | Date | Infected | Fatal | Recovered
-- | -- | -- | -- | --
311 | 2020/12/13 | 25439 | 2562 | 149286
312 | 2020/12/14 | 26121 | 2585 | 150947
313 | 2020/12/15 | 25708 | 2643 | 153519
314 | 2020/12/16 | 25807 | 2688 | 155547
315 | 2020/12/17 | 26077 | 2739 | 158287

Figure will not be changed.

![Figure_1](https://user-images.githubusercontent.com/7270139/102622546-8a7f0200-4184-11eb-8108-5faac4902c86.png)

**Comment by Inglezos** [comment]
So in order to get confirmed column as well, I have to call `Scenario.records(variables=["Confirmed", "Infected", "Fatal", "Recovered"])` ?

**Comment by lisphilar** [comment]
Yes.
