### ISSUE TITLE
[Fix] use minimum number of tests in PCRData class for positive_rate()

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#441]
## Summary
A minimum number of daily/weekly tests must be applied in `positive_rate()` method of the PCRData class (for example min_pcr_tests=100) in order to ensure stable behaviour during low tests/cases (not extremely high rates). Also I would suggest the default window to be changed to 7 (1 week), since the positivity over one week is more representative.

**Comment by Inglezos** [comment]
I created pull request #439.
Used min_pcr_tests (default = 100) and changed default window to 7.

**Comment by lisphilar** [comment]
Thank you for your pull request, #439 was merged.
