### ISSUE TITLE
[Fix] ParserError when reading linelist data dated 18Dec2020

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#442]
## Summary
When CovsirPhy read linelist data dated 18Dec2020, `ParserError` was raised.

## (Optional) Related classes
- `covsirphy.LinelistData`
- `covsirphy.CleaningBase`

## Codes and outputs:
```Python
import covsirphy as cs
# Dataset preparation
data_loader = cs.DataLoader("input")
# Download linelist
linelist = data_loader.linelist()
```
This code raises the following error.
```Python
---------------------------------------------------------------------------

ParserError                               Traceback (most recent call last)

<ipython-input-4-69ff6eb123df> in <module>()
      1 data_loader = cs.DataLoader()
----> 2 data_loader.linelist()

9 frames

/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py in read(self, nrows)
   2155     def read(self, nrows=None):
   2156         try:
-> 2157             data = self._reader.read(nrows)
   2158         except StopIteration:
   2159             if self._first_chunk:

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.read()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.raise_parser_error()

ParserError: Error tokenizing data. C error: Expected 1 fields in line 11, saw 3
```
https://gist.github.com/lisphilar/dcccee390cfb9bc30973105b8ce90b00

## Environment
- CovsirPhy version: 2.13.2
- Python version; 3.8
- Installation: pipenv
- System: Google Colaboratory

**Comment by lisphilar** [comment]
I think the root cause is in the raw dataset, but we need to fix this issue in CovsirPhy because this error will be raised when we call `DataLoader.jhu()`. We need to solve this issue immediately and release 2.13.3 for all users.

**Comment by lisphilar** [comment]
Dear @Inglezos ,
Could you download and unzip the raw data (.tar.gz file) manually?
https://github.com/beoutbreakprepared/nCoV2019/blob/master/latest_data/latestdata.tar.gz

Error occurred when I unziped this file in Ubuntu (Windows Subsystem for Linux) with  `tar -zxvf latestdata.tar.gz` code.
Error code said "gzip: stdin: unexpected end of file". Is this file broken?

**Comment by lisphilar** [comment]
I found that `dask.dataframe.read_csv()` failed in downloading linelist data with `ParserError`, but `pandas.read_csv()` successfully completed.
I created a pull request #443. After tests passed, I will release minor version 2.13.3 as soon as possible.

**Comment by Inglezos** [comment]
What was the cause? Does it work now?
Is there enough disk space for unzipping I guess right? (0.5 Gb)
https://www.iditect.com/how-to/57104583.html
https://programmersought.com/article/8459281908/

Oh you said the problem was not in pandas, but in dask?

**Comment by lisphilar** [comment]
> Is there enough disk space for unzipping I guess right? (0.5 Gb)

Disk space... possible...

> Oh you said the problem was not in pandas, but in dask?

We are using dask in `CleaningBase.load()` to shorten reading time. However, dask sometimes fails in loading, thouth pandas completes.

**Comment by lisphilar** [comment]
Tests passed with pull request #443!!
I will merge this and release 2.13.3.
