### ISSUE TITLE
[New] Reduce memory usage of LinelistData by not saving raw data

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#449]
## Summary of this new feature
Because data loading of LinelistData takes long time and much memory, it is better to use only JHU data for calculation of recovery period.

Nevertheless, we could overcome this issue and include linelist if we preprocess them once at the beginning of the analysis in order to save a final cleaned dataset with the few valid records. Then we could use this to load and process every time instead of the large raw file. In that way we can use linelist in calculation of recovery period as well (perhaps averaging or consider it in some way in order to represent these data as well).

Currently, the valid linelist data we have for COVID-19 are only few hundred records, so probably they are not representative enough, compared to the million of cases worldwide. For the moment, we should use perhaps only the JHU data to calculate recovery period using `calculate_recovery_period()`. We should further revise this if we find other credible linelist data source with more valid records.

This is related to #420, #447.

**Comment by lisphilar** [comment]
In 2.13.3, raw dataset is saved in `._raw` (Uses can access it with property `.raw`). To reduce the memory usage of `LinelistData`, we can
- Remove `._raw`
- (Deprecate `.raw` property (if deprecated, it will be removed in version 3.0.0 in the future))
- filename will be saved to `self._filename` and property `.raw` will return `.load(filename)`

With this change, user cannot access to raw data if the file was moved. However, this is effective to reduce memory usage.

**Comment by Inglezos** [comment]
Hmm I would suggest removal if this is not used or better the `._raw` dataset should be created upon explicit user request (command execution).

**Comment by lisphilar** [comment]
All public methods should be kept until the next major version 3.0.0 will be released. (I don't plan new major version currently.)

The raw dataset is saved as `_raw` using `self._raw = self.load(filename)` (linelist) or `= dd.read_csv()` in cleaning classes.

**Comment by Inglezos** [comment]
I suggested this because as you said it would reduce memory usage. I meant that we don't need to save this raw dataset internally, but only upon explicit user code execution, such as `_raw = self.load(filename)`

**Comment by lisphilar** [comment]
I created draft pull request #461 for discussion.

**Comment by lisphilar** [comment]
I created draft pull request #462 for discussion.

`LinelistData`:
- Remove `._raw`
- filename will be saved to `self._filename` and property `.raw` will return `.load(filename)`

Deprecation of `.raw` property is not included.

**Comment by lisphilar** [comment]
Please review my pull request #463.

`LinelistData`:
- Remove `._raw`
- filename will be saved to `self._filename` and property `.raw` will return `.load(filename)`
- Not save the columns we will not use in data cleaning

Deprecation of `.raw` property is not included.

**Comment by Inglezos** [comment]
I approved the changes!

**Comment by lisphilar** [comment]
Thank you, it was merged.
