### ISSUE TITLE
Dear Rakesh(@SM-ins),

### ISSUE THREAD

**Issue by SM-ins** [lisphilar/covid19-sir#46]
Dear Rakesh(@SM-ins),
Thank you for your feed-back!

`cs.Population` does not input the CSV files directly downloaded from THE WORLD BANK. We need `DataLoader` class to use them.
Please run the following codes with the latest version (>2.3.0).
```Python
data_loader = cs.DataLoader("../input")
pop_data = data_loader.population()
pop_data.cleaned().tail()
```
Type of `pop_data` is equal to `cs.Population` and "locations_population.csv" will be saved in "../input" directory. This is different from "API_EN.POP.DNST_DS2_en_csv_v2.csv", but well organized.

Best Regards,
Lisphilar

_Originally posted by @lisphilar in https://github.com/lisphilar/covid19-sir/issues/42#issuecomment-651144648_

**Comment by lisphilar** [comment]
This issue is discussed in #42 and I will close this new issue.
