### ISSUE TITLE
[New] method of `Scenario` to know what kind of complement was done for subset

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#478]
## Summary of this new feature
With #401, `JHUData.show_complent(country)` was discussed to show the kind of complement performed for the subset of each country (for debug). As the next step, we need to add `Scenario.show_complement()` to show the details of complement performed on the selected country (for users).

## (Optional) Solution
Add `DataHandler.show_complement()` method. (`DataHandler` is a parent class of `Scenario`).

**Comment by lisphilar** [comment]
With #537, `.show_complement()` will be added to `DataHandler` (`Scenario`) class.

Dear @Inglezos, please add explanation of this method when updating documentation for #531, like this (can be changed).

example/usage_quick.ipynb:
`Scenario.show_complement()` method is useful to show the kinds of complement. The details of complement is explained in [Usage: dataset](https://lisphilar.github.io/covid19-sir/usage_dataset.html) section.
```Python
snl.show_complement()
```

**Comment by Inglezos** [comment]
Created pull request #541 for this.
Added "recovery period" term and described `.show_complement()` usage.

**Comment by lisphilar** [comment]
Thank you. #541 was merged.
