### ISSUE TITLE
[Docs] start to use Poetry for package management

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#479]
## What we need to document?
To improve the development environment of CovsirPhy, we need Poetry as the package management tool. we are currently using Pipenv, but it sometimes fails in updating dependencies.

After that, how to set-up development environment should be documented in https://lisphilar.github.io/covid19-sir/CONTRIBUTING.html

**Comment by Inglezos** [comment]
Will this be compatible with Anaconda and conda environments as well?

**Comment by lisphilar** [comment]
- CovsirPhy is not uploaded to Anaconda.
- Pipfile, Pipfile.lock, setup.cfg and setup.py will be removed.
- pyproject.toml and poetry.lock will be added.

What are you concerns?

**Comment by Inglezos** [comment]
Happy new year!! I wish you health and happiness!!! :)
Yes CovsirPhy is not uploaded to Anaconda, but if I had activated a conda environment then in Anaconda console I could issue for example pip install covsirphy. Now with this Poetry manager will I be able to do so similarly? For development though I guess I will continue to use git clone/pull seamlessly independently.

**Comment by lisphilar** [comment]
Yes, `pip install covsirphy` works like before.
However, it is recommended to use Poetry for dependency management with clone/pull because we need not `pip install covsirphy` after editing covsirphy derectory. (`pip install . -e` does not work because setup.py will be replaced with pyproject.toml file.)

I will show the details after updating documentation.

**Comment by Inglezos** [comment]
Okay great, I hope everything will work normal then.

**Comment by lisphilar** [comment]
Started to use Poetry in the development version and usage was documented in https://lisphilar.github.io/covid19-sir/CONTRIBUTING.html

Please review documentation.

**Comment by lisphilar** [comment]
Dear @Inglezos ,
With reviewing the documentation, do you have any ideas to accelerate comminication and particilation of CovsirPhy users?

**Comment by Inglezos** [comment]
Sorry, I will check this some time in the week and if anything comes up I will comment.

**Comment by Inglezos** [comment]
I had many troubles with poetry. I have Windows 10. Do I install it inside a conda environment? From where do I run the commands you have in `covid19-sir/CONTRIBUTING.html`? In cmd? In Anaconda console? Somewhere else? To be honest I don't have much time to investigate this. Will this be a problem for me for future development of CovsirPhy?

What I am currently doing is the following setup: I have a conda env with many packages installed. I activate this env with Anaconda console and then I run spyder from there. I have cloned covsirphy github repo to a local folder e.g. `.../cInglezos/`) and I set in spyder the working directory to that folder (`.../cInglezos/covid19-sir/`). I have linked that repo to my respective fork repo in github as well. For the git commands, I use MINGW64 console and I open it from inside `.../cInglezos/covid19-sir/` folder. Then whenever I want to get the latest codes I simply `git pull`, that's my update. Finally, to install any package dependency related to covsirphy, I pip/conda install them inside the conda env via Anaconda console.

That's all my setup and I am used to it all this time. Will I have to use poetry at all or this setup will be enough for my needs?

**Comment by lisphilar** [comment]
It is not required for you to setup with poetry at this time, but it may fails in reslolving dependencies in the future (because pip is being updated to implement more strict resolvers and CovsirPhy needs many dependencies) or when you install some packages CovsirPhy does not include as dependencies.

The commands to install poetry will be run in PowerShell or MINGW64 console after installation of Python https://www.python.org/ in Windows OS. This system does not need Anaconda. I will add comments to the markdown later. Thank you.
