### ISSUE TITLE
[Fix] jhu_data.total() last record issue

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#483]
## Summary
Upon executing `jhu_data.total()`, the last entry depends on JHU dataset and Japan dataset time sync, which can lead to weird results. For example, if Japan dataset is updated first, then as total cases it shows only the Japan ones, ignoring completely past JHU records:
![image](https://user-images.githubusercontent.com/36845191/103459465-5ecd5180-4d18-11eb-9dd6-3b2d6c733c86.png)
One solution would be to either sync Japan update time to JHU or calculate cumulative from JHU plus the new Japan entries.
This leads to plot:
![image](https://user-images.githubusercontent.com/36845191/103459523-bc619e00-4d18-11eb-82d6-07d7386e62e7.png)

## Codes and outputs:
```
import covsirphy as cs
# Dataset preparation
data_loader = cs.DataLoader("input")
jhu_data = data_loader.jhu()

df = jhu_data.cleaned()
jhu_first_date, jhu_last_date = df["Date"].min(), df["Date"].max()
data_cols = ["Confirmed", "Infected", "Fatal", "Recovered"]
total_df = jhu_data.total()
total_df = total_df.loc[total_df.index <= jhu_last_date, :]

cs.line_plot(total_df[data_cols], "Total number of cases over time", color_dict={"Confirmed": "blue", "Infected": "orange", "Fatal": "red", "Recovered": "green"})
```

## Environment
- CovsirPhy version: 2.13.3-iota
- Python version: 3.8
- Installation: Anaconda/pip
- System: Windows

**Comment by lisphilar** [comment]
Yes, I agree with your idea.
The last date of `JHUData.total()` should be the last date of `pd.to_datetime(JHUData._raw[self.DATE]).dt.max()`. Because the last date of Japan dataset is included in the cleaning data, we need to use the `JHUData._raw`.

**Comment by Inglezos** [comment]
This was resolved with #492.

**Comment by Inglezos** [comment]
The issue is not resolved but in a new way, I guess due to year change. If I execute the code:
```
import covsirphy as cs

data_loader = cs.DataLoader(directory="kaggle/input")
jhu_data = data_loader.jhu()
population_data = data_loader.population()
pcr_data = data_loader.pcr()
oxcgrt_data = data_loader.oxcgrt()

data_cols = ["Confirmed", "Infected", "Fatal", "Recovered"]
df_cleaned = jhu_data.cleaned()
jhu_first_date, jhu_last_date = df_cleaned["Date"].min(), df_cleaned["Date"].max()
jhu_elapsed = (jhu_last_date - jhu_first_date).days
total_df = jhu_data.total()
total_df = total_df.loc[total_df.index <= jhu_last_date, :]
total_df.tail()
cs.line_plot(total_df[data_cols], "Total number of cases over time", color_dict={"Confirmed": "blue", "Infected": "orange", "Fatal": "red", "Recovered": "green"})
```

then the results are these:
![image](https://user-images.githubusercontent.com/36845191/104004926-0cbf7c80-51ad-11eb-86de-d6eeacf0e47f.png)
![image](https://user-images.githubusercontent.com/36845191/104004972-23fe6a00-51ad-11eb-9e16-2a515f0c61b3.png)

There is this high accumulation of cases in early 2020 for some reason. I suspect these cases should be added instead in 2021.

**Comment by Inglezos** [comment]
It appears that this has to do with wrong France data for Jan 2021, we will continue this thread in issue #484 conversation.
