### ISSUE TITLE
[Fix] Partial complement recovery data of Greece shows negative infected values

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#488]
## Summary
Partial complement recovery data of Greece shows negative infected values.

## Codes and outputs:
```Python
import covsirphy as cs
# Dataset preparation
data_loader = cs.DataLoader("input")
jhu_data = data_loader.jhu()
jhu_data.records("Greece")[0].head()
```
This code returns 

  | Date | Confirmed | Infected | Fatal | Recovered
-- | -- | -- | -- | -- | --
0 | 2020/1/6 | 0 | -1 | 0 | 1
1 | 2020/1/7 | 0 | -1 | 0 | 1
2 | 2020/1/8 | 0 | -1 | 0 | 1
3 | 2020/1/9 | 0 | -1 | 0 | 1
4 | 2020/1/10 | 0 | -1 | 0 | 1

## Environment
- CovsirPhy version: 2.14.0-alpha-fu1
- Python version: 3.8
- Installation: pipenv
- System: WSL (Ubuntu

**Comment by lisphilar** [comment]
`jhu_data.show_complement("Greece")` returns

Country | Province | Monotonic_confirmed | Monotonic_fatal | Monotonic_recovered | Full_recovered | Partial_recovered
-- | -- | -- | -- | -- | -- | --
0 | Greece | - | False | False | False | False | True

Dear @Inglezos,
Is this a problem specific to partial complement of recovered data?

**Comment by Inglezos** [comment]
Hmm, without your new code changes, I mean using 13.3-iota and my code changes as I git pushed them in the pull request, I get:
![image](https://user-images.githubusercontent.com/36845191/103477667-bb3c7980-4dc9-11eb-85cf-050b829d7aaa.png)
Why do you have False everywhere and why the country is in Province? It seems like a right shift has been made by the later changes?

**Comment by Inglezos** [comment]
Regarding the negative values yes they exist, I will investigate this.

**Comment by lisphilar** [comment]
Sorry, I failed in convert the table to markdown (index=0 makes values out of positions). The following is correct as you mentioned.

Country | Province | Monotonic_confirmed | Monotonic_fatal | Monotonic_recovered | Full_recovered | Partial_recovered
-- | -- | -- | -- | -- | -- | --
Greece | - | False | False | False | False | True

**Comment by lisphilar** [comment]
Thank you for your pull request #489 and I merged it. I think we can close this issue.
