### ISSUE TITLE
[Fix] PCR positive_rate() behavior for USA

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#490]
## Summary
For USA, positive_rate shows weird ending values. As I saw manually, the original testing records are sharply declining after mid-December and then are unupdated. The last diff value is very small (~250k), which value we keep as ending values after and interpolate. Can we do something better for such cases in PCR handling, especially for unupdated ending values? Or should we accept such testing data? Maybe not include last window days?
![image](https://user-images.githubusercontent.com/36845191/103478859-3570fc00-4dd2-11eb-8ec6-945fc476af3b.png)
![image](https://user-images.githubusercontent.com/36845191/103478872-4a4d8f80-4dd2-11eb-9b16-ca8a26bbf123.png)

## Codes and outputs:
```
import covsirphy as cs
# Dataset preparation
data_loader = cs.DataLoader("input")
pcr_data = data_loader.pcr()
usa_pcr = pcr_data.positive_rate("USA")
```

## Environment
- CovsirPhy version: 2.13.3-iota
- Python version: 3.8
- Installation: Anaconda/pipenv
- System: Windows

**Comment by lisphilar** [comment]
Test values seems not updated from 26Dec2020 in COVID-19 Data Hub.
```Python
pcr_data._subset_by_area("United States", province="-", dataset="COVID-19 Data Hub").tail(15)
```

ISO3 | Date | Tests | Confirmed
-- | -- | -- | --
USA | 2020/12/20 | 233284904 | 17853731
USA | 2020/12/21 | 234473695 | 18045048
USA | 2020/12/22 | 235907673 | 18239758
USA | 2020/12/23 | 237405251 | 18466484
USA | 2020/12/24 | 238503891 | 18665343
USA | 2020/12/25 | 239016679 | 18765529
USA | 2020/12/26 | 239260589 | 18992126
USA | 2020/12/27 | 239260589 | 19142603
USA | 2020/12/28 | 239260589 | 19309281
USA | 2020/12/29 | 239260589 | 19511426
USA | 2020/12/30 | 239260589 | 19740772
USA | 2020/12/31 | 239260589 | 19968087
USA | 2021/1/1 | 239260589 | 20128693
USA | 2021/1/2 | 239260589 | 20427780
USA | 2021/1/3 | 239260589 | 20427780

"Our World In Data" has values from 27Dec2020 to 31Dec2020, but they are too large.

```Python
pcr_data._subset_by_area("United States", province="-", dataset="Our World In Data").tail(15)
```

ISO3 | Date | Tests_diff | Tests
-- | -- | -- | --
USA | 2020/2/20 | 1 | 239260601
USA | 2020/2/21 | 1 | 239260602
USA | 2020/2/22 | 1 | 239260603
USA | 2020/2/23 | 0 | 239260603
USA | 2020/2/24 | 0 | 239260603
USA | 2020/2/25 | 1 | 239260604
USA | 2020/2/26 | 0 | 239260604
USA | 2020/2/27 | 0 | 239260604
USA | 2020/2/28 | 3 | 239260607
USA | 2020/2/29 | 62 | 239260669
USA | 2020/12/27 | 1383493 | 483649950
USA | 2020/12/28 | 1540320 | 485190270
USA | 2020/12/29 | 1251638 | 486441908
USA | 2020/12/30 | 1578458 | 488020366
USA | 2020/12/31 | 1719181 | 489739547

**Comment by lisphilar** [comment]
"The COVID Tracking Project" has a dataset regarding the number of tests in USA and Data API.
This is only for USA, but may be useful for this issue.
https://covidtracking.com/data/national

**Comment by Inglezos** [comment]
I think that "Our World In Data" values are valid and probably correct. 1-2 million tests daily seems normal for a country with 150-200k confirmed daily. But as a general solution for USA tests, we could use also "The COVID Tracking Project" data as well yes.

**Comment by lisphilar** [comment]
The current situation in USA is as follows.
```Python
import covsirphy as cs
data_loader = cs.DataLoader()
pcr_data = data_loader.pcr()
pcr_data.positive_rate("USA").tail(20)
```

ISO3 | Date | Tests | Confirmed | Tests_diff | Confirmed_diff | Test_positive_rate
-- | -- | -- | -- | -- | -- | --
USA | 2020/12/26 | 242327934 | 19042166 | 1.50E+06 | 190322.1429 | 12.678895
USA | 2020/12/27 | 243240561 | 19199355 | 1.46E+06 | 185706.5714 | 12.760157
USA | 2020/12/28 | 244456896 | 19366014 | 1.42E+06 | 181867.7143 | 12.782591
USA | 2020/12/29 | 246218414 | 19564536 | 1.41E+06 | 182289.7143 | 12.97397
USA | 2020/12/30 | 248318504 | 19796528 | 1.40E+06 | 182846 | 13.083093
USA | 2020/12/31 | 250152244 | 20026231 | 1.40E+06 | 187410.7143 | 13.358776
USA | 2021/1/1 | 251334989 | 20184236 | 1.42E+06 | 195617.5714 | 13.751835
USA | 2021/1/2 | 252369534 | 20486742 | 1.43E+06 | 206368 | 14.385915
USA | 2021/1/3 | 253316016 | 20696637 | 1.44E+06 | 213897.4286 | 14.860689
USA | 2021/1/4 | 254486252 | 20873232 | 1.43E+06 | 215316.8571 | 15.028064
USA | 2021/1/5 | 256036034 | 21104369 | 1.40E+06 | 219976.1429 | 15.684382
USA | 2021/1/6 | 257729694 | 21354750 | 1.34E+06 | 222603.1429 | 16.55712
USA | 2021/1/7 | 259306060 | 21635491 | 1.31E+06 | 229894.2857 | 17.580209
USA | 2021/1/8 | 260602638 | 21928012 | 1.32E+06 | 249110.8571 | 18.815732
USA | 2021/1/9 | 261477833 | 22192842 | 1.30E+06 | 243728.5714 | 18.731269
USA | 2021/1/10 | 261477833 | 22409132 | 1.29E+06 | 244642.1429 | 18.949792
USA | 2021/1/11 | 261477833 | 22622305 | 1.25E+06 | 249867.5714 | 20.007765
USA | 2021/1/12 | 261477833 | 22838952 | 1.15E+06 | 247797.5714 | 21.501183
USA | 2021/1/13 | 261477833 | 23077247 | 1.04E+06 | 246071 | 23.762122
USA | 2021/1/14 | 261477833 | 23077247 | 9.35E+05 | 240007.2857 | 25.658455

![Figure_1](https://user-images.githubusercontent.com/7270139/104598235-af01c780-56b9-11eb-8832-82aa532989cb.png)

**Comment by lisphilar** [comment]
Delay of updating test values in USA was observed, but this could occurs in many countries. The new dataset will solve the problem in USA, but this will not solve the problems in the other countires.
So, can we apply one of the next solutions?
- remove repeated values at the ending as default
- fill in the repeated values with linear interpolation of diff values (and recalculate test values)

**Comment by Inglezos** [comment]
I would think the second approach to be more efficient, in a similar way to `_recovered_partial_ending()` perhaps?

**Comment by lisphilar** [comment]
Yes, this is like `_recovered_partial_ending()`, but `diff_series.loc[diff_series.duplicated()] = None;  diff_series.interpolate()` could be enough. Could you try this?

**Comment by Inglezos** [comment]
Yes, I created pull request #538 for this.

**Comment by lisphilar** [comment]
Thank you! #538 was merged.
