### ISSUE TITLE
[New] specify columns and colors in Scenario.simulate() plot

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#495]
## Summary of this new feature
Add the option in cases simulation method `Scenario.simulate()` to specify columns (for example [Confirmed, Infected, Fatal, Recovered]) and the desired colors for the respective plot lines. Currently there are only [Infected, Fatal, Recovered] without the Confirmed variable option.

**Comment by lisphilar** [comment]
With #527, `variables` argument and `colors` argument were added to `Scenario.simulate()`.
