### ISSUE TITLE
[Question] Accuracy of estimation in df format - Estimator Class

### ISSUE THREAD

**Issue by rebeccadavidsson** [lisphilar/covid19-sir#499]
Which code can be used in order to get the accuracy of estimation in df format?
For example, when running ```snl.estimate_accuracy(phase="1st")```,  the accuracy is shown in a Figure. The method 'accuracy' in the Estimator Class returns this df, but how can it be accessed? 
I want to use this to check for differences in accuracy among countries and models.
Thank you!

**Comment by lisphilar** [comment]
Because `Scenario.phase_estimator()` returns `Estimator` class, we can access to the dataframe as follows.
```Python
snl = cs.Scenario(...)
...
df = snl.phase_estimator(phase="1st").accuracy()
print(df.columns)
```
```
Index(['Confirmed', 'Infected_actual', 'Fatal_actual', 'Recovered_actual',
       'Susceptible_actual', 'Susceptible_predicted', 'Infected_predicted',
       'Recovered_predicted', 'Fatal_predicted'],
      dtype='object')
```

Yes, this is un-useful for users. `Scenario.estimate_accuracy(phase="1st")` probably should return this dataframe, not `None`.

**Comment by rebeccadavidsson** [comment]
Amazing, thank you for the quick response!
