### ISSUE TITLE
[New] Scenario.history() support for actual Confirmed as well

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#502]
## Summary of this new feature
`snl.history("Confirmed")` shows only the scenarios (Main, Forecast) upon execution and not the actual data, as in the case `snl.history("Fatal")` for example. This happens because `records()` which is called internally keeps only `[self.CI, self.F, self.R]` columns/variables. Please add the option for Confirmed as well, either in `records()` or in `history()`.

**Comment by lisphilar** [comment]
Please replace `self.records(show_figure=True)` with `self.record_df.copy()` at line 814 (`.track()` method).
