### ISSUE TITLE
[New] Add Date column to phase_estimator df

### ISSUE THREAD

**Issue by rebeccadavidsson** [lisphilar/covid19-sir#503]
It would be useful if the dataframe also has a 'Date' column, that's now being returned from:
```
snl.estimate(cs.SIRF, phases=["1st"])
df = snl.phase_estimator(phase="1st").accuracy()
```
There is a **t** column, however it's hard to relate this column to the original date.
 ![Schermafbeelding 2021-01-07 om 10 18 13](https://user-images.githubusercontent.com/11540873/103874604-aade1480-50d1-11eb-8cce-96eeca732263.png)

## Temporary Solution
```
df["Date"] = data.iloc[-len(df):]["Date"].values
df.plot(x="Date", y=["Infected_actual", "Infected_predicted"]);
```
Also, the y-axis range could be smaller/in range of the data:
![image](https://user-images.githubusercontent.com/11540873/103874401-63f01f00-50d1-11eb-912e-228ffa1fff80.png)

Inserting the date would also allow the phase_estimator() function to have multiple phases as input, eventually creating an overview of the accuracy along each phase.

**Comment by lisphilar** [comment]
Did you try `snl.history("Infected")`?
```Python
# Disable all phases except for 1st and 2nd phases
all_phases = snl.summary().index.tolist()
snl.disable(phases=all_phases)
snl.enable(phases=["1st", "2nd"])
# Parameter estimation
snl.estimate(cs.SIRF)
# Compare actual values and estimated values
snl.history("Infected")
```
![Figure_1](https://user-images.githubusercontent.com/7270139/103885559-8ad74100-5123-11eb-9ca7-a8304b678431.png)

For enhancement, we will add the following features.
- `.disable()` and `.enable()` accept `phases=None` to disable/enable all phases.
- `.history()` have `phases` argument to select phases to show.
- `.history()` accept `ylim=(None, None)` argument to change y-axis range. (i.e. add `**kwargs` to control `cs.line_plot()` function internally.)

If this is a good solution for you, I will create issues later. Do you have time to create pull requests?

**Comment by rebeccadavidsson** [comment]
Great, thank you!

**Comment by lisphilar** [comment]
We wiil move forward to #510, #511 and #512.
