### ISSUE TITLE
[Fix] negative Rt in parameters forecast with `fit_predict()` for larger delay

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#507]
## Summary
With the current implementation of parameters forecast, sometimes the predicted `Rt` value can become negative if delay is large. For example I tried hardcoded delay of 30 days instead of the recovery period (changed delay to 30 in `_fit_create_data()`) and I ran the estimator for Greece. The result was to have a phase with extremely small duration (zero or one day) and 
 `Rt` to become negative:
![image](https://user-images.githubusercontent.com/36845191/103937318-4783cf00-5131-11eb-8188-7f953cfc7c8c.png)
![image](https://user-images.githubusercontent.com/36845191/103937471-7732d700-5131-11eb-99d0-c692239d450c.png)

## Codes
```
import covsirphy as cs

data_loader = cs.DataLoader(directory="kaggle/input")
jhu_data = data_loader.jhu()
population_data = data_loader.population()
oxcgrt_data = data_loader.oxcgrt()

gre_scenario = cs.Scenario(jhu_data, population_data, "Greece")
gre_scenario.records().tail()
_ = gre_scenario.trend()
gre_scenario.estimate(cs.SIRF)
gre_scenario.add(name="Main", days=30)
gre_scenario.add(name="Forecast", days=30)
gre_scenario.fit_predict(oxcgrt_data=oxcgrt_data, name="Forecast").summary(name="Forecast")
gre_scenario.summary()
gre_sim_df_main = gre_scenario.simulate(name="Main")
gre_sim_df_forecast = gre_scenario.simulate(name="Forecast")
```

## Environment
- CovsirPhy version: 2.14.0-delta
- Python version: 3.8
- Installation: conda/pip
- System: Windows

**Comment by lisphilar** [comment]
(This may be related to #513. 30 days may not be acceptable for Greece at this time.)

**Comment by lisphilar** [comment]
In version 2.16.2-kappa-fu2, delay-30 for Greece did not show negative values.
https://gist.github.com/lisphilar/4b889de957bbc3554a13062d531d6e94
