### ISSUE TITLE
[Discuss] Poland parameter forecast gives unexpected increased Rt

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#509]
## Summary
The forecast analysis (with delay=recovered period) for Poland gives unexpected increased `Rt` value which results in increased cases, while actually the situation in Poland seems to stabilize:
![image](https://user-images.githubusercontent.com/36845191/103947541-e7952480-5140-11eb-8349-8cef0a8f6816.png)
![image](https://user-images.githubusercontent.com/36845191/103947587-fbd92180-5140-11eb-8d21-2a4d1fa9edbc.png)

## Codes
```
import covsirphy as cs

data_loader = cs.DataLoader(directory="kaggle/input")
jhu_data = data_loader.jhu()
population_data = data_loader.population()
oxcgrt_data = data_loader.oxcgrt()

 x_scenario = cs.Scenario(jhu_data, population_data, "Poland")
 x_scenario.records_diff()
 x_scenario.records().tail()
 _ = x_scenario.trend()
 x_scenario.estimate(cs.SIRF)
 x_scenario.add(name="Main", days=30)
 x_scenario.fit_predict(oxcgrt_data=oxcgrt_data, name="Forecast").summary(name="Forecast")
 x_sim_df = x_scenario.simulate(name="Main")
 x_sim_df = x_scenario.simulate(name="Forecast")
 x_scenario.summary()
```

## Environment
- CovsirPhy version: 2.14.0-delta
- Python version: 3.8
- Installation: conda/pip and Google Colab (v2.14.0)
- System: Windows

**Comment by lisphilar** [comment]
The table indicates rho sharply decreased and theta + simga increased as expected with Rt definition of SIR-F model. (figures: `Scenario.history("rho")`. etc.)

Were OxCGRT scores sharply changed in Poland?

**Comment by Inglezos** [comment]
It is strange because the Main scenario is totally different and seems more normal:
![image](https://user-images.githubusercontent.com/36845191/104032717-39888980-51d7-11eb-9391-566817219978.png)
![image](https://user-images.githubusercontent.com/36845191/104032730-40170100-51d7-11eb-8803-ba6bec024773.png)

**Comment by Inglezos** [comment]
No, OxCGRT indicators are stable:
![image](https://user-images.githubusercontent.com/36845191/104033107-c29fc080-51d7-11eb-9c97-8f99736d2a1c.png)

**Comment by lisphilar** [comment]
The 7th column shows "1, 1, 1,.... 2 (31Dec2020), 2, 2, 2, 2, 1, 1...."
`Scenario.fit()` may be a clue. (I will check the details UTC-tomorrow.)

**Comment by Inglezos** [comment]
Yes I know, but this little change (from 1 -> 2) seems improbable to lead to such a rapid increase of cases in the next days. It is about doubling the cases in just two weeks.

**Comment by Inglezos** [comment]
Also weird forecast results seem to have Russia and Switzerland as well.

**Comment by lisphilar** [comment]
> this little change (from 1 -> 2) seems improbable to lead to such a rapid increase of cases in the next days. It is about doubling the cases in just two weeks

Max values of OxCGRT scores (except `stringency_index`) are 3 or 4 and this not a small change.

> since a partial score increased (stricter), then the cases should not increase that much but decrease instead

Yes. (stricted policy measures -> decreased rho -> decreased number of infected cases)

**Comment by lisphilar** [comment]
Details of OxCGRT indicators:
https://covid19datahub.io/articles/doc/data.html
https://github.com/OxCGRT/covid-policy-tracker/blob/master/documentation/codebook.md

For Poland,
- predicted sigma value was negative value.
- `Cancel_events` increase -> rho increase (confirmed with [15] un-expected)
- `Internal_movement_restrictions` increase -> rho increase (confirmed with [15] un-expected)

https://gist.github.com/lisphilar/4f71b3e62448fc0d50eed983abd3fc2a

**Comment by Inglezos** [comment]
So what is happening, what the results mean? What went wrong? As I remember, the parameters must never be negative.

**Comment by lisphilar** [comment]
At the current version 2.15.0-eta-fu1, the situation was improved with "delay=12" (estiamted with `.estimate_delay()`), but `kappa` is still negative value.
https://gist.github.com/lisphilar/d3ee1cd2cdfe85aaa3c3c2458326897b

Restriction to (0, 1) could be implemented, but no ideas for codes at this time.

**Comment by lisphilar** [comment]
Version 2.16.2-kappa-fu2: theta < 0
https://gist.github.com/lisphilar/190d9583a10a3c6c8678ce065a0c693b

**Comment by lisphilar** [comment]
This will be discussed in #668.
