### ISSUE TITLE
[Fix] Scenario.disable() and .enable() do not accept None (i.e. all phases)

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#510]
## Summary
Docstring of `Scenario.disable()` says `phases` argument accepts `None`, but this does not accept `None` actually. When `None`, `phases` argument is expected as all phases.
The same is true for `Scenario.enable()` method.

## Codes
```Python
import covsirphy as cs
# Dataset preparation
data_loader = cs.DataLoader("input")
jhu_data = data_loader.jhu()
population_data = data_loader.population()
# Scenario analysis
snl = cs.Scenario(jhu_data, population_data, "Japan")
snl.trend()
snl.disable(phases=None)
```

## Outputs
Raises `TypeError: @phases must be a list or tuple, but <class 'NoneType'> was applied.`

## Environment
- CovsirPhy version: 2.14.0-delta
- Python version: 3.8.5
- Installation: poetry
- System: WSL (Ubuntu)

**Comment by lisphilar** [comment]
This is related to #503.

In `analysis.param_tracker.ParamTracker.diable()` method and `.enable()`, the following codes (or refactored codes) should be added at the first lines.
```Python
all_phases = [self.num2str(num) for (num, unit) in enumerate(self._series) if unit]
phases = phases or all_phases[:]
```

**Comment by rebeccadavidsson** [comment]
Thanks for thinking along! There are several functions with docstrings saying that phases=None is also an option which doesn't always work, but it's quite complex. For now (for me) using this piece of code is a good solution:

```
all_phases = snl.summary().index.tolist()
snl.disable(phases=all_phases)
snl.enable(phases=["1st", "2nd"])
```

So thank you 👍

**Comment by lisphilar** [comment]
With #525, `Scenario.disable(phases=None)` and `Scenario.enable(phases=None)` were added to the latest development version. If you can install development version, please confirm that with the following codes.
```Python
snl.disable(phases=None)
snl.enable(phases=["1st", "2nd"])
```

Kindly create bug reports if you find any methods which do not work as expected!
