### ISSUE TITLE
[Docs] summary of complement and related terms

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#531]
## What we need to document?
- summary of JHU data complement
- related terms including "recovery period"

This is related to #514.

## Where to document
- example/usage_dataset.ipynb, https://lisphilar.github.io/covid19-sir/usage_dataset.html#The-number-of-cases-(JHU-style)
- docs/markdown/TERM.md, https://lisphilar.github.io/covid19-sir/TERM.html

**Comment by Inglezos** [comment]
Created pull request #541 for this.
Added "recovery period" term and described .show_complement() usage.
