### ISSUE TITLE
[Docs] Update docs/usage_theoretical with non-dimensional equations

### ISSUE THREAD

**Issue by rebeccadavidsson** [lisphilar/covid19-sir#534]
Usage_theoretical.ipynb did not cover information about non-dimensional parameters, which are used in the examples.

Related to #533

**Comment by lisphilar** [comment]
Dear @rebeccadavidsson ,
Do you have time to edit example/usage_theoritical.ipynb, not the file in docs directory, without running the notebook?
Sorry, I noticed this after merging your pull request.

**Comment by lisphilar** [comment]
Please rebase your forked default branch before updating files.

**Comment by lisphilar** [comment]
This documentation system is complecated and we may change the directory setting.

**Comment by lisphilar** [comment]
FYI
"usage_theoritical.ipynb" with updated comments was moved from "docs" to "example" directory.
This will be uploaded to GitHub Pages in some hours.
