### ISSUE TITLE
[Question/Docs] How to set the sensitivity in S-R trend analysis

### ISSUE THREAD

**Issue by andrybicio** [lisphilar/covid19-sir#568]
## Summary of question
I would like to set the sensitivity (i.e. I think to tune "max_rmsle") of covsirphy.ChangeFinder class in order to have more in number and shorter trends phases, since sometimes it does not detect efficiently the changings. Is there a way to tune/set it? 

In other words:
when running 
``
scenario.trend(set_phases=True)
``
is there a way to tune some parameter to make ruptures more sensitive to change in slope?

**Comment by Inglezos** [comment]
>in order to have more in number and shorter trends phases
>
One note I would like to make on that: it is not preferable to have short phases since the ODE need sufficient number of records to model the cases. Currently we have set the minimum phase duration to 5 days but I would not recommend to further decrease this. If the trends analysis is not that much correct then I would suspect that the problem lies elsewhere.

**Comment by andrybicio** [comment]
> If the trends analysis is not that much correct then I would suspect that the problem lies elsewhere.
i do understand your point and I basically agree. However I would like to avoid the situation that appears in my following notebook, specially cell executed [14]. I'm uploading here the first image for province "Friuli Venezia Giulia"
One can easily see that lines are actually two, and beside dividing the phase manually, I wonderedif one could tune some parameter to do it automatically.

https://github.com/andrybicio/LDE_Project/blob/main/CovSIRphy_Analysis_v2.ipynb

![download1](https://user-images.githubusercontent.com/56033694/105773201-d1220200-5f63-11eb-97b7-bc4e7901e4de.png)

**Comment by lisphilar** [comment]
Then minimum length of the phases in S-R trend analysis can be set by `Scenario.trend(min_size=3)`, but, as mentioned, shorter length is not recommended. Improvement of accuracy in trend analysis and estimation is a challenge and we are looking for ideas.

As a temporary solution, you can separate the 11th phases manually with `Scenario.separate(date="17Oct2020")` if it is difficult to change the last date. The 11th phase will be 10Oct2020 - 16Oct2020 and the new 12th phase will be 17Oct2020 - 20Oct2020.

**Comment by andrybicio** [comment]
So the only parameter, at the actual moment, that can be set is the minimum size for the length of each phase?

**Comment by lisphilar** [comment]
Yes with `Scenario.trend()`. `max_rmsle` can be also changed, but this does not change the behavior of change date finding. (`max_rmsle` is to determine whether lines on the figure will be shown or not).

**Comment by andrybicio** [comment]
I see, so mine is still an open issue. Thank you for your help!
One more thing: in some graphs, such as the one above, sometimes the curve is note centered since "recovered" label is forced to start at 0.

This occurs also with  https://github.com/andrybicio/LDE_Project/blob/main/CovSirPhy_Analysis.ipynb

Output for cells [122] and [123] . I think they are forced to start from 0.0, therefore it might happen for them to appear "out of scale" and not properly represented

**Comment by lisphilar** [comment]
X range is set as `(0, None)` directly in `Trend.show_with_many()` and no user control arguments are available at this time. Could you create an issue to improve visibility of trend graph? We about to update some graphs, but not started.

**Comment by andrybicio** [comment]
> X range is set as `(0, None)` directly in `Trend.show_with_many()` and no user control arguments are available at this time. Could you create an issue to improve visibility of trend graph? We about to update some graphs, but not started.

I'll do it. Thank you

**Comment by lisphilar** [comment]
Dear @andrybicio,
How could we proceed this discussion?

**Comment by andrybicio** [comment]
Dear @lisphilar 
I'm not sure this is more related to "ruptures" library, rather than the _covid19-sir_ one. Maybe the possibility to provide different cost functions would be a solution but, honestly speaking, I am not so well versed in this topic. 
I see you are using ruptures.Pelt with rbf model and maybe here something can be tuned.

**Comment by lisphilar** [comment]
OK, but could you list up the types of trend misreading, including the case in Friuli Venezia Giulia?
Let's set direction as to how to fix bugs, putting Python details aside.

**Comment by andrybicio** [comment]
I have just upgraded to 2.16.0 with code, but I have some problems with it. Therefore I'm opening an issue.
As soon as I downgrade I'll reply to this

**Comment by lisphilar** [comment]
We continue this discussion in #670.
