### ISSUE TITLE
[New/Revise] Deprecation of SIR-FV model because vaccination effect should be discussed with SIR-F parameters

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#573]
## Summary of this new feature
The number of vaccinations is a key factor to end outbreak. Because we have vaccination data (`VaccineData`), we can add the number of vaccinations as a variable to `Scenario` class.

**Comment by lisphilar** [comment]
(Cc. @Inglezos  and @andrybicio)
Addition of the number of vaccinations as a variable to `Scenario` class enables us to use the number of vaccinations as a variable in SIR-FV model. Currently, vaccination effect is included in reduction of `Susceptible` variable, but this is not useful for parameter estimation with SIR-FV model.

SIR-FV considers vacctnation of sussceptible people as follows. ω×N persons will be vaccinated in a day. N is the total population.
<img width="512" alt="キャプチャ" src="https://user-images.githubusercontent.com/7270139/106350989-68000d00-631c-11eb-9481-3d57e0738a54.PNG">

**Comment by lisphilar** [comment]
Alternative:
Use the number of vaccinations when calculating "Susceptible". This is better because vaccination impacts on "Susceptible" variable, not I, R, F. ODE model is still SIR-F.

**Comment by lisphilar** [comment]
New parameters when calculating Susceptible:
- inverse of "period to get effectivity of vaccination"
- inverse of "period to lost effectivity of vaccination"

**Comment by lisphilar** [comment]
Alternative:
Regard "vaccination" as a control factor of rho/sigma/kappa, not a variable of ODE models.
With this idea, we can use `VaccineData` as a explanatory variable in `Scenario.fit_predict()` as well as `OxCGRTData`.

**Comment by Inglezos** [comment]
Yes, I think the last solution is the more correct approach, because the vaccinations:
    i. have effectivity property which alters the result and 
    ii. affect infectivity but probably cannot stop the transmission, simply protects the person itself from developing symptoms and become sick.

This shall be represented in the parameters as control factor. In no case the vaccinations mean that a person is removed from the S compartment and in the future never affects again other people. He could either be infected eventually due to decreased vaccine effectiveness or infect others as well as a carrier by transmitting the disease to non-vaccinated people.

**Comment by lisphilar** [comment]
Thank you for your confirmation. Yes, "Vaccinated" could not be separated from "Susceptible" and so on. We cannot calculate "Period to get (lost) effectivity of vaccination" with datasets at this time. (We may find clinical studies for that with repeated PCR tests and antibody tests at many timepoints, but the number of subjects is limited.)

In our data-driven approach, I think SIR-F model can be the final ODE model for COVID-19.
i.e. All records except for Confirmed/Rrecovered/Fatal/Population will be regarded as controll factors.

**Comment by lisphilar** [comment]
My idea:
- Creating instance of `covsirphy.SIRFV` raises `FutureWaring: SIR-FV model will be removed in the future because vaccinated persons may move to the other compartments. Please use SIR-F model and adjust parameter values of SIR-F model, considering the impact of vaccinations on infectivity, effectivity and safety.`
- We will discuss how to estimate the impact of vaccinations on infectivity, effectivity and safety.

**Comment by lisphilar** [comment]
Update: raise `NotImplementedError`, not warnings.
