### ISSUE TITLE
[New] add "the number of vaccinated" to VaccineData as well as "the number of vaccinations"

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#609]
## Summary of this new feature
"people_vaccinated" (the number of vaccinated people) was added to the raw dataset in "Our World In Data".
https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations

This is also informative data as well as the number of vaccinations (administored doses) and we can add this data to the cleaned dataset of `VaccineData` as `Vaccinated` records.

**Comment by lisphilar** [comment]
This is related to #573.

**Comment by Inglezos** [comment]
With vaccinations do we mean a single vaccine dose or a fully vaccinated individual (which is single or double-dose) depending on the type? Because if it is the first one then we have a problem in using these data. I think "our world in data" differentiates between these two with categories "Total number of people who have received at least one dose of the COVID-19 vaccine" and "Total number of people who have been fully vaccinated against COVID-19".

**Comment by lisphilar** [comment]
I think "Total number of people who have received **at least one dose** of the COVID-19 vaccine" could be used. By dividing "the number of vaccinations (doses)" with this new data, mean number of doses people received can be calculated. We should discuss the name of this new data (e.g. Vaccinated_once), but what is the problem when using this data?

The second one (fully vaccinated) can be also included in `VaccineData`, but definition of "fully" may be changed in the near future. We say "fully vaccinated" when received two doses currently. However, we may need to take doses more than twice to keep immunity for long time.

**Comment by Inglezos** [comment]
In exploratory analysis and visualization yes we can use either one.
But, in my understanding, in the modelling and the control factors there is no point in using half-vaccinated people. One vaccination should mean one full vaccination (one or two doses depending on the vaccine type). What might be needed in the future to keep the immunity or to extend it, is another issue I think.

**Comment by lisphilar** [comment]
No publications, but some studies are indicating that people who was (or might) infected asymptomatically show sufficient immune responses when half-vaccinated. https://www.bmj.com/content/372/bmj.n308
Because this does not show discrepancy with the role of vaccination and primary/secondary immunity, I'm looking at these studies with interest as a clinical research associate.

In data science, all of the three variables (the number of vaccinations, fully or partially vaccinated persons) can be used in parameter prediction of future phases. After adding them to the regression model for future engineering #611, we can select necessary features with Elastic Net model (which has been implemented).

**Comment by lisphilar** [comment]
Additionally, ISO3 codes will be added to the cleaned dataset of `VaccineData`.

**Comment by lisphilar** [comment]
With #630, added the following columns to the cleaned dataset of `VaccineData`.

- ISO3 (pandas.Category): ISO3 codes
- Vaccinated_once (int): cumulative number of people who received at least one vaccine dose
- Vaccinated_full (int): cumulative number of people who received all doses prescrived by the protocol
