### ISSUE TITLE
[New] dataset regarding hospitalization

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#643]
## What dataset you need?
The following variables in "COVID-19 Data Hub".
- hosp: Number of hospitalized patients on date
- icu: Number of hospitalized patients in ICUs on date
- vent: Number of patients requiring invasive ventilation on date

## How will you use the dataset for your analysis?
`HospitalData` will be created and `.subset()` returns them. Additionally, `Scenario.register(extras)` accept this data cleaning class and `Scenario.fit()` will use them for parameter prediction.

**Comment by lisphilar** [comment]
FYI:
Documentation of "COVID-19 Data Hub" https://covid19datahub.io/articles/doc/data.html

**Comment by Inglezos** [comment]
Could these variables be displayed in global colored map as well?

**Comment by lisphilar** [comment]
Yes, could be. `.map` method should be inplemented in the new class.

**Comment by lisphilar** [comment]
This may be dicussed laiter, but not required at this time.
