### ISSUE TITLE
Some phases have small number of days (<=2) suggested by ChangeFinder

### ISSUE THREAD

**Issue by SM-ins** [lisphilar/covid19-sir#66]
Summary:
`` needs to return ... but returns ...

CovsirPhy version 

Related classes:
- `covsirphy.`
(optional)

Codes and outputs:
```Python
```
This code returns 

Environment:
Python 3.8, pipenv, WSL.

Hi Lisphilar,
i am getting following error while running the below code:-

ind_scenario.trend()

ValueError: @end_date must be over 23Jun2020.

Please help me out if possible...

With regards,
Rakesh

**Comment by lisphilar** [comment]
Dear Rakesh,
Thank you for your feed-back!

It seems that some phases have small number of days (<=2).
I will fix this issue in the next version.

**Comment by lisphilar** [comment]
Dear Raksh,
I fixed this bug in CovsirPhy version 2.4.1 and please confirm it.
If you have the same error, please kindly share the details of the codes and errors.

Thank you.

**Comment by SM-ins** [comment]
Dear Lisphilar,

Thankyou so much for your kind cooperation...,it's working now..

With regards,
Rakesh

**Comment by SM-ins** [comment]
Dear @lisphilar/covid19-sir
<reply@reply.github.com> ,
 Thankyou it's  working now...,i had compiled ind_scenario.estimate(cs.SIRF)
after that code and as a result error was coming...
