### ISSUE TITLE
[Fixed in dependencies] France source data are not updated

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#679]
## Summary
Since 19Feb21, the data for France are not updated and stuck to 

Confirmed | Recovered | Fatal |
-- | -- | --
3560764 | 248488 | 83964

Temporary workaround solution by covid19datahub team:
https://github.com/covid19datahub/COVID19/issues/157

> Until this is resolved, we are using a workaround to at least get the cases data (there are more columns, cases is the only that really matters to us right now) directly from the French government website.
> 
> Our solution looks like this, in case anyone needs that data too:

> ```
> from covid19dh import covid19
> import requests
> import pandas as pd
> 
> pdf, src = covid19(verbose=False)
> 
> column_renames = {
>     "maille_code": "id",
>     "conf": "confirmed",
> }
> 
> #Download French Government Data to File
> govFR_file = "data-gouv-fr-chiffres-cles.csv"
> govFR_url = (
>     "https://www.data.gouv.fr/fr/datasets/r/f335f9ea-86e3-4ffa-9684-93c009d5e617"
> )
> 
> #Download File
> file = requests.get(govFR_url)
> with open(govFR_file, "wb") as f:
>     f.write(file.content)
> #Load csv into pandas
> data_govFR = pd.read_csv(govFR_file)
> 
> #Rename Columns
> data_govFR.rename(column_renames, axis="columns", inplace=True)
> 
> #Get Date for last valid reported case data on covid19dh
> lastReportedValidDate = datetime.strptime("19-02-2021", "%d-%m-%Y")
> 
> #Convert date column to date
> data_govFR["date"] = pd.to_datetime(data_govFR["date"])
> #Get only rows where date is greated than the last date where valid data was available in covid19dh
> data_govFR = data_govFR.loc[data_govFR["date"] > lastReportedValidDate]
> #Filter out rows where confirmed is N/A
> data_govFR = data_govFR.loc[~data_govFR["confirmed"]. isna ()]
> 
> #Copy values from French government dataset to covid19dh dataset
> for currentDate in data_govFR["date"].dt.date.unique().tolist():
>   pdf.loc[(pdf["id"]=="FRA") & (pdf["date"].dt.date == currentDate), "confirmed"] = data_govFR.loc[data_govFR["date"].dt.date == currentDate, "confirmed"].values
> ```

> You can then check that there are confirmed cases for France in your data again by using:

> `pdf.loc[(pdf["id"]=="FRA") & (pdf["date"] > lastReportedValidDate)]`

**Comment by lisphilar** [comment]
I think `pd.read_csv()` can read the data with the URL, not saving the data to a CSV file, but script is necessary for`covsirphy.cleaning.covid19datahub.py.COVID19DataHub._download()`.

**Comment by Inglezos** [comment]
Guidotti has updated the datahub issue status with a comment that it has now been fixed and I can confirm this by looking at the source data.

**Comment by lisphilar** [comment]
I also confirmed that it has been fixed in COVID-19 Data Hub.

```Python
import covsirphy as cs
data_loader = cs.DataLoader()
jhu_data = data_loader.jhu()
subset_df = jhu_data.subset("France")
subset_df.tail()
cs.line_plot(subset_df.set_index("Date"), title="France: the number of cases")
```

  | Date | Confirmed | Infected | Fatal | Recovered
-- | -- | -- | -- | -- | --
366 | 2021/3/19 | 4216695 | 3845085 | 91964 | 279646
367 | 2021/3/20 | 4252022 | 3879311 | 92140 | 280571
368 | 2021/3/21 | 4282603 | 3909370 | 92278 | 280955
369 | 2021/3/22 | 4298395 | 3923889 | 92621 | 281885
370 | 2021/3/23 | 4298395 | 3923889 | 92621 | 281885

![Figure_1](https://user-images.githubusercontent.com/7270139/112138593-0b7ee700-8c15-11eb-88e1-ec6ad41e76d0.png)
