### ISSUE TITLE
[Fix] Scenario.register() for France data raised Segmentation fault

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#681]
## Summary
`Segmentation fault` was raised when register France data to `Scenario` instance. This may be linked with #679.

## Codes

```Python
import covsirphy as cs
data_loader = cs.DataLoader()
jhu_data = data_loader.jhu()
population_data = data_loader.population()
snl = cs.Scenario(country="France")
snl.register(jhu_data, population_data)
```

## Outputs
`Segmentation fault (core dumped)`

## Environment

- CovsirPhy version: 2.17.0-kappa-fu2
- Python version: 3.9.2
- Installation: poetry
- System: WSL (Ubuntu)

**Comment by lisphilar** [comment]
The latest stable version 2.17.0 (with Google Colab) also raised `Segmentation fault`.

**Comment by lisphilar** [comment]
`jhu_data.subset_complement()` also raised the same error.
```Python
import covsirphy as cs
data_loader = cs.DataLoader()
jhu_data = data_loader.jhu()
jhu_data.subset_complement("France")
```

**Comment by Inglezos** [comment]
After debugging I found out that the segmentation fault is raised inside `jhu_complement.py` -> `_monotonic()` -> at line `series.interpolate(method="spline", order=1, inplace=True)`. This means I guess that the interpolation fails totally. If I change either method to `linear` or keep `spline` but with `order=2`, then the problem is solved.

**Comment by lisphilar** [comment]
Yes, "spline" should be replaced with "linear".

**Comment by lisphilar** [comment]
I remember we discussed replacement of "spline" in some issues (I could find the issue...) and some lines of the class uses "linear". However, "spline" remains here.
Do you have time to create a pull request today?

**Comment by lisphilar** [comment]
Thank you!
