### ISSUE TITLE
[Question] Future simulation days in forecast

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#714]
## Summary of question
As I remember, the forecasted days are equal (at most) to the country's delay right? So for example if the delay is 12 days, then the forecast returns the predicted cases for the next ~12 days at most. If the user wants fewer days then he can pass argument `days` as long as it is less than delay.
But what about if the user wants to project more days? For example 1 month?
In my opinion then, we should be able to provide such results, by extending the future phase during which we will keep constant the forecasted parameters and just simulate the cases.

**Comment by lisphilar** [comment]
Yes, we can provide it, but implicit implementation may be confusing. (E.g. extend only when `extend=True`, default is False)

At version 2.19.0, we can extend the future phase to 31 days like this.
```Python
fit_dict = snl.fit()
delay = fit_dict.get("delay")
snl.predict()
snl.add(days=31-delay)
```


Please also refer to open issue #477. This is not your point in this question, but this is necessary for meaningful long-term forecasting.

**Comment by lisphilar** [comment]
With pull request #720, to fix the last date of simulation results and to simplify the call tree of simulation, I created `ode.ode_solver._ODESolver` (internal only) and `ode.ode_datahandler.ODEHandler` (public) class.
They are not used in `Scenario` class at this time. Call tree of `Scenario.simulate()` will be changed later and `ODESimulator` will be deprecated.
Please check the usage of these classes with tests/test_ode.py::TestODEHandler.
