### ISSUE TITLE
[Question] SIR model with influential nodes detection

### ISSUE THREAD

**Issue by seemarani1307** [lisphilar/covid19-sir#719]
## What we need to document?
Hello Sir,

I am working on influential nodes detection from social networks. How can we apply SIR model on our network? please help .

Thanks

**Comment by lisphilar** [comment]
Thank you for your question.
Could you explain your question in more detail?

**Comment by seemarani1307** [comment]
Hello Sir,

Thankyou for kind reply. I have worked on influential nodes detection from multilayer network. I want to use SIR model to validate the work. How can I apply SIR model on my network. Please help sir.

**Comment by lisphilar** [comment]
The network is for epidemiological data? Sorry, I could not understand how you want to "validate" your work. PLease show a detailed example for this discussion.

**Comment by seemarani1307** [comment]
No sir. It's social network data. I have performed infleuntial nodes detection. The reviewer has suggested me to do compare your work SIR model. SIR model is only for epidemiological data?

**Comment by lisphilar** [comment]
CovsirPhy downloads COVID19-related datasets and analyse them with SIR-derived ODE models. S, I, R stand for Susceptible, Infected and Recovered respectively. Please kindly ask the reviewer the details and refer to our documentation. We do not have published papers currently.

https://www.kaggle.com/lisphilar/covid-19-data-with-sir-model
https://lisphilar.github.io/covid19-sir/index.html
