### ISSUE TITLE
[New/Question] Forecast plots focus

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#725]
## Summary of this new feature
When we run forecast analysis and scenario comparison, for example with:
```
ita_scenario.fit_predict(oxcgrt_data=oxcgrt_data, name="Forecast").summary(name="Forecast")

ita_scenario.summary()
ita_sim_df = ita_scenario.simulate(variables=["Confirmed", "Infected", "Fatal", "Recovered"],
                                   color_dict={"Confirmed": "blue", "Infected": "orange", "Fatal": "red", "Recovered": "green"},
                                   name="Main")
ita_sim_df = ita_scenario.simulate(variables=["Confirmed", "Infected", "Fatal", "Recovered"],
                                   color_dict={"Confirmed": "blue", "Infected": "orange", "Fatal": "red", "Recovered": "green"},
                                   name="Forecast")

_ = ita_scenario.history(target="Confirmed")
_ = ita_scenario.history(target="Infected")
_ = ita_scenario.history(target="Fatal")
_ = ita_scenario.history(target="Recovered")
_ = ita_scenario.history(target="Rt")
```
I see that in the plots the latest values that concern mostly the user, the current week and the future days, most times they get lost in the scaling and the values cannot be seen as they are covered from the Main scenario line for example, because the differences are small in comparison. For example in such cases:
![image](https://user-images.githubusercontent.com/36845191/115160326-54a14a00-a0a0-11eb-9e67-c4c72cab799b.png)
![image](https://user-images.githubusercontent.com/36845191/115160362-76023600-a0a0-11eb-8719-35a6c649ef90.png)

Is there any easy way that the plots focus/autoscale/zoom preferably on the latest months in order that the user can distinguish the cases simulation clearly from each scenario without that excessive overlapping?

**Comment by lisphilar** [comment]
Did you try `phases` argument? #511
I don't have my PC to check it today, but I think the following works.
```Python
all_phases = snl.summary(name="Main").index.tolist()
snl.history("Infected", phases=all_phases[-3:])
```

Yes, easier way, including y-logscaling (`y_logscale=True` work?) and adding new arguments, will be discussed here.

**Comment by lisphilar** [comment]
With the change of phase detection algorithm, we have much more phases now. It is difficult for users to controll phases with phase names, like "10th".

I think `phases` could be deprecated and replaced with `date_range=("2021-01-01", "2021-02-28")` (or `limits`) argument etc. Dates will be parsed with `pandas.to_datetime()`.

**Comment by Inglezos** [comment]
Yes I agree this would be the best, the user shall specify at the Scenario level a range of dates to plot for the `history()`.

**Comment by lisphilar** [comment]
With #752 (from version 2.19.1-eta), we can focus on the values in specified date range with the following arguments. Internally, these arguments are parsed by `PhaseTracker.parse_range()`.

- `dates`: tuple of start date and end date
- `past_days` (integer): how many past days to use in calculation from today (`Scenario.today` property)
- `phases` (list of str): phase names to use in calculation

These arguments are effective with `Scenario.history()`, `Scenario.simulate()`, `Scenario.track()` and `Scenario.score()`.

Documentation was also updated with usage_quick.ipynb.
https://lisphilar.github.io/covid19-sir/usage_quick.html

**Comment by lisphilar** [comment]
@Inglezos, can we close this issue regarding plotting? Kindly confirm the current statuses of the opened issues.

**Comment by Inglezos** [comment]
For the moment I don't have any findings on this, so we can close it. If something comes up I will create a pull request.
