### ISSUE TITLE
[Fix] missing dates in global Vaccinations data & colored map plot

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#728]
## Summary
Upon `jhu_data.map(country="China", variable="Confirmed")` execution, it throws error:
```
  line 1, in <module>
    jhu_data.map(country="China", variable="Confirmed")

  \cleaning\jhu_data.py", line 684, in map
    return self._colored_map_country(

  \cleaning\cbase.py", line 476, in _colored_map_country
    self._colored_map(title=title, data=df, level=self.PROVINCE, **kwargs)

  \cleaning\cbase.py", line 407, in _colored_map
    cm.plot(**find_args([gpd.GeoDataFrame.plot, ColoredMap.plot], **kwargs))

  \visualization\colored_map.py", line 88, in plot
    gdf = self._country_specific_data(data, included=included, excluded=excluded, country=country)

  \visualization\colored_map.py", line 186, in _country_specific_data
    hkg_gdf = gdf.loc[gdf[self.ISO3] == "HKG"].dissolve()

  \site-packages\geopandas\geodataframe.py", line 951, in dissolve
    aggregated_data = data.groupby(by=by).agg(aggfunc)

  \site-packages\pandas\core\frame.py", line 6508, in groupby
    raise TypeError("You have to supply one of 'by' and 'level'")

TypeError: You have to supply one of 'by' and 'level'
```

## Codes
```
import covsirphy as cs

data_loader = cs.DataLoader(directory="kaggle/input")
jhu_data = data_loader.jhu()
population_data = data_loader.population()
oxcgrt_data = data_loader.oxcgrt()

jhu_data.map(country="China", variable="Confirmed")
```

## Environment
- CovsirPhy version: v2.19.1-beta
- Python version: 3.8.5
- Installation: conda/pip
- System: Windows

**Comment by lisphilar** [comment]
The error seems an error in `geopandas.GeoDataFrame.dissolve()`?
In my environment, error was not raised and I got a figure successfully. I used version 2.19.1-beta-fu1, but no changes regarding `JHUData` from 2.19.1-beta to 2.19.1-beta-fu1.
```Python
import covsirphy as cs
data_loader = cs.DataLoader(directory="input")
jhu_data = data_loader.jhu()
jhu_data.map(country="China", variable="Confirmed")
```
![Figure_1](https://user-images.githubusercontent.com/7270139/115735793-b8d84c80-a3c5-11eb-879d-87d35b068585.png)

I used GeoPandas 0.9.0 and Pandas 1.1.5.
```Python
import geopandas as gpd
gpd.__version__
import pandas as pd
pd.__version__
```

**Comment by Inglezos** [comment]
Alright I updated the geopandas dependencies and finally the error is resolved.
However, if I run
```
import covsirphy as cs

data_loader = cs.DataLoader(directory="kaggle/input")
jhu_data = data_loader.jhu()
population_data = data_loader.population()
oxcgrt_data = data_loader.oxcgrt()

jhu_data.map(country="Japan", variable="Confirmed", date="15Apr2021")
vaccine_data.map(date="15Apr2021")
```
the results are
![image](https://user-images.githubusercontent.com/36845191/115794792-4bcdb280-a3d7-11eb-8d2b-f67ddce3b2ca.png)
![image](https://user-images.githubusercontent.com/36845191/115794764-3eb0c380-a3d7-11eb-8676-9aebdf98a132.png)

**Comment by Inglezos** [comment]
I tried to debug it locally on my PC and I got something weird about the countries that are included in the df:
![test1](https://user-images.githubusercontent.com/36845191/115961918-5f853000-a521-11eb-9396-35782695e479.PNG)
![test2](https://user-images.githubusercontent.com/36845191/115961920-60b65d00-a521-11eb-9384-f8f79fdd5a5e.PNG)

The first image is from breakpoint at line 429 (with step over), which means the df right after it was assigned `self._cleaned_df.copy()` and the second image is right before plotting on line `self._colored_map(title=title, data=df, level=self.COUNTRY, **kwargs)`.

It seems like the countries the map includes are only the ones starting with A-F letter for some reason. The plot result right after is this:
![image](https://user-images.githubusercontent.com/36845191/115961984-c86ca800-a521-11eb-9d1b-6dceaa65501b.png)

which seems to confirm this assumption.

I had run only code `vaccine_data.map(date="10Apr2021")`.

**Comment by lisphilar** [comment]
`.map()` works for me in my local environment (Ubuntu with "Windows Subsystem for Linux" and Python 3.9.2).
```Python
import covsirphy as cs
data_loader = cs.DataLoader()
jhu_data = data_loader.jhu()
jhu_data.map(country="Japan", variable="Confirmed", date="15Apr2021")
vaccine_data = data_loader.vaccine()
vaccine_data.map(date="10Apr2021")
```
![Figure_1](https://user-images.githubusercontent.com/7270139/115963689-75174b80-a55b-11eb-8c14-07084cde66b5.png)
![Figure_2](https://user-images.githubusercontent.com/7270139/115963693-78123c00-a55b-11eb-8637-751dfddb53b4.png)

In your environment, `vaccine_data._cleaned_df.Country.unique().tolist()` does not include G-Z countries?

**Comment by Inglezos** [comment]
>In your environment, vaccine_data._cleaned_df.Country.unique().tolist() does not include G-Z countries?
>
['Afghanistan', 'Africa', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Anguilla', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', '**Asia**', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Cambodia', 'Cameroon', '**Canada**', 'Cape Verde', 'Cayman Islands', 'Chile', '**China**', 'Colombia', 'Congo', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Curacao', 'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'England', 'Equatorial Guinea', 'Estonia', 'Eswatini', 'Ethiopia', '**Europe**', **'European Union**', 'Faeroe Islands', 'Falkland Islands', 'Fiji']

I think I have found what's going on. The vaccinations source from owid has changed drastically.

**Comment by lisphilar** [comment]
We use "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv" and this includes G-Z countries.
Repo: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv

**Comment by Inglezos** [comment]
![image](https://user-images.githubusercontent.com/36845191/115964846-03c1a380-a52f-11eb-8877-3e2e763ee370.png)
That's the last entry right after line `rec_df = self.load(self.URL_REC, columns=list(set(rename_dict) - set(["vaccines"])))` during data download.

**Comment by lisphilar** [comment]
Not caused in my environment...
Could you check the outputs of `cbase.load()` and `dd.reaa_csv()` with the URL?
https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv

**Comment by Inglezos** [comment]
I changed line `return dd.read_csv(urlpath, blocksize=None, **kwargs).compute()` to `return pd.read_csv(urlpath, **kwargs)` and now it reads all the countries.

Nevertheless, Africa data visualization for vaccines seem weird progressing from 10Apr21 to today:

![image](https://user-images.githubusercontent.com/36845191/115965437-f0640780-a531-11eb-84a1-7e5ac9181f4a.png)
![image](https://user-images.githubusercontent.com/36845191/115965439-f5c15200-a531-11eb-8cfe-02d7593dee1e.png)
![image](https://user-images.githubusercontent.com/36845191/115965443-f8bc4280-a531-11eb-939e-b1bdf549af55.png)
![image](https://user-images.githubusercontent.com/36845191/115965444-fb1e9c80-a531-11eb-9cdd-063abfda567c.png)
![image](https://user-images.githubusercontent.com/36845191/115965447-fe198d00-a531-11eb-83f7-9f7516d2ba93.png)
![image](https://user-images.githubusercontent.com/36845191/115965450-01147d80-a532-11eb-8343-038386300329.png)
![image](https://user-images.githubusercontent.com/36845191/115965453-040f6e00-a532-11eb-949b-61544295253c.png)
![image](https://user-images.githubusercontent.com/36845191/115965455-0671c800-a532-11eb-8994-683808828397.png)

I ran this also in Colab and I get the same results for Africa vaccinations map.

Could it be source data problem or `date` argument in `map()`?

**Comment by Inglezos** [comment]
I have found the problem. For many countries in the Africa continent (at least, I haven't check if this is happening for other continents as well), the vaccinations source data do not continue up to today. This means that each country has its own dates range. So when we project on a map a screenshot of the vaccinations for one day, this day might not be included in the dates range for every country.

For example South Africa has vaccine records up to 13Apr21, Algeria up to 19Feb21, Botswana up to 10Apr21, Mali up to 12Apr21 and so on.

What we need to do is to extend the last date's vaccine value up to today, including all the in-between days, and for every country that its end date is less than today.

**Comment by lisphilar** [comment]
Do you mean vaccination data is not updated regurarly (at daily basis)? Or, stopped updating for some countries? If the formar case, please consider to update `VaccineData._cleaning()` method.

**Comment by Inglezos** [comment]
I mean that for some countries there are not daily records at all for vaccinations. Not only the value of the number of vaccines is missing, but also the complete row/record with date and rest info is missing, and this happens over many days up to today.

**Comment by lisphilar** [comment]
If you have time, could you try updating `VaccineData._cleaning()` to solve this issue?

**Comment by Inglezos** [comment]
Reworked `VaccineData._cleaning() - Extended vaccine data up until today for missing records.
![image](https://user-images.githubusercontent.com/36845191/116012239-21c3fc80-a632-11eb-81f1-dd7f5c5ff7c6.png)
![image](https://user-images.githubusercontent.com/36845191/116012249-27b9dd80-a632-11eb-9708-4b95b36d88ea.png)
The missing countries in Africa for 10Apr21 is correct since then data for Congo or Libya were not available. In today's plot however, Congo should have values, I don't know why it doesn't plot them. You can see manually that the dates are all filled with the last data if you call `vaccine_data._cleaned_df` or `.subset()`.

**Comment by lisphilar** [comment]
Thank you for your pull request!! I added some comments just for speed and refactoring.

> Congo should have values, I don't know why it doesn't plot them, could it be a geopandas issue?

It may be a mismatch of geometry information (`gpd.datasets.get_path("naturalearth_lowres")` in line 216 of colored_map.py) and `.subset()`.

> the horizontal legend is personal preference

Oh, we discussed the location of legend somwhere, but I forgot to move it. Could you update `ColredMap` class with a new issue?
