### ISSUE TITLE
OxCGRT data not registered

### ISSUE THREAD

**Issue by gvncore** [lisphilar/covid19-sir#730]
At which point in the documentation do we register OxCGRT indicators into the Scenario object? Can we register those manually?

![image](https://user-images.githubusercontent.com/57956871/115752553-7f3e1c00-a39a-11eb-8b2c-d062b244e110.png)

**Comment by lisphilar** [comment]
Thank you for your question!
Please register OxCGRT data manually by `Sceanrio.register(extras=[oxcgrt_data])` before `Scenario.estimate_delay()`.
```Python
import covsirphy as cs
# Load datasets
data_loader = cs.DataLoader("input")
jhu_data = data_loader.jhu()
population_data = data_loader.population()
oxcgrt_data = data_loader.oxcgrt()
# Create Sceanrio instance
snl = cs.Scenario(country="country name here")
# Register datasets
snl.register(jhu_data, population_data, extras=[oxcgrt_data])
snl.estimate_delay()
```
Documentation: https://lisphilar.github.io/covid19-sir/usage_quick.html#Start-scenario-analysis

**Comment by gvncore** [comment]
Great, thanks for your help!

**Comment by lisphilar** [comment]
Did you try `today` argument of `Scenario.timepoint()`?
Kindly share the script you tried.

**Comment by lisphilar** [comment]
Additionally, version information and outputs/errors may be necessary for investigation. Could you create a new issue for that with "Request fixing a bug" template?
https://github.com/lisphilar/covid19-sir/issues/new/choose
