### ISSUE TITLE
[New] backup/restore Scenario object

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#741]
## Summary of this new feature
As @hannanabdul55 proposed in #735, methods to save/retrieve `Scenario` objects will be helpful when we perform parameter estimation using a server and simulate with the estimated parameter values using local machines.

> My idea was a way to save and retrieve the Scenario object with one command. Similar to pd.DataFrame.to_csv() and pd.DataFrame.read_csv(). Currently, it's clearly inefficient as a pickle.dump of the object is massive.

**Comment by lisphilar** [comment]
To recover `Scenario object`, we need at least
- country/province name
- records for the country/province (output of `Scenario.records()`)
- start/end date, tau, estimated parameter values of phases (output of `Scenario.summary()`)

@hannanabdul55,
Do you have any ideas regarding this issue?
E.g. What file format will be useful to store `Scenario`?

**Comment by lisphilar** [comment]
From #735, @hannanabdul55,

> I see that the Scenario object, on pickling, saves all the data associated too, like, for example, the entire JHU and population data for the basic case ( extras also if specified). We could avoid these data frames when pickling to make the size of the output file much smaller. And if so, we can also serialize the Scenario object to a JSON object itself.

`Scenario` instance has `DataHandler` object as internal variable `Scenario._data`. This may the cause and we can update codes to remove it.

**Comment by Inglezos** [comment]
>Scenario instance has DataHandler object as internal variable Scenario._data. This may the cause and we can update codes to remove it.
>
This won't affect `_cleaned_df` right? We will still have access to it with `Scenario._cleaned_df`?

**Comment by lisphilar** [comment]
In `Scenario`, the role of `DataHandler` is to provide the dataset **for specific country/province** and to estimate delay period. `Scenario` does not need `JHUData._cleaned_df` directly. However, `Scenario._data` is `DataHandler` instance. This could be replaced with dataframes.

**Comment by hannanabdul55** [comment]
Yes, since the `_cleaned_df` is generated using a fixed function, we could just re-create this dataframe on load, instead of saving the entire object. One thing to note here is that the data _most probably_ would have been changed (at least in the case of JHU) if we load the object much later.

**Comment by lisphilar** [comment]
> One thing to note here is that the data most probably would have been changed (at least in the case of JHU) if we load the object much later.

That may mean it is better not to save records of datasets. Saving only phase settings is efficient.

**Comment by lisphilar** [comment]
`DataHandler._data_dict` has data cleaning class (`JHUData`, `PopulationData` etc.) instances directly. To reduce the size of `DataHandler` and `Scneario`  instances, `DataHandler._data_dict` will save dataframes.

**Comment by hannanabdul55** [comment]
> `DataHandler._data_dict` should save dataframes   
What does dataframe here mean? Also, from the data, it looks like we're storing the entire JHU data, right?  

Another alternative would be to store _only_ the data for the Country/Province in the `Scenario` object. In that way, maybe we can also save the data as well, but also keep the size very low.

**Comment by lisphilar** [comment]
"Dataframe" is `pandas.DataFrame` of data for the country/province in the `Scenario` object (instance).

> Another alternative would be to store only the data for the Country/Province in the Scenario object. In that way, maybe we can also save the data as well, but also keep the size very low.

That's exactly what I wanted to say!

**Comment by hannanabdul55** [comment]
Perfect. my apologies, I did not understand it completely initially! I will implement this and raise a draft PR soon! Thank you.

**Comment by lisphilar** [comment]
This is my first thought.

We have `JHUData` and `PopulationData` class separately because the data sourses were different when I created them.
However, the classes could be merged because both of the classes use the same data source "COVID-19 Data Hub". With this change, users can set datasets more easily as follows. Class/method names (`merged` here) are tentative.

```Python
import covsirphy as cs
loader = cs.DataLoader()
merged_data = loader.merged()
oxcgrt_data = loader.oxcgrt()
vaccine_data = loader.vaccine()
snl = cs.Scenario(country="Country name")
snl.register(merged_data, extras=[oxcgrt_data, vaccine_data])
```


Note that it is not recommended to include `OxCGRTData` because
- some users want to read local CSV files for SIFR variables (Susceptible etc.) and download indicator values from "COVID-19 Data Hub".
- unlike SIFR, OxCGRT records are indicators of forecasing, not main dataset for parameter estimation.

**Comment by lisphilar** [comment]
I created new issue #759 to discuss merge of `JHUData` and `PopulationData` in my previous comment.

**Comment by lisphilar** [comment]
With #767 (development version 2.19.1-kappa), we will have `Scenario.backup(filename)` and `Scenario.restore(filename)` to backup/restore timepoints and phase information.

Backup information:
```Python
backupfile_dict = cs.Filer(directory="output")
snl.backup(**backupfile_dict)
```

Restore information:
```Python
backupfile_dict = cs.Filer(directory="output")
snl = cs.Scenario(country="Japan")
snl.register(jhu_data, population_data)
snl.restore(**backupfile_dict).summary()
```

Note that we need to execute `Scenario.register()` in advance to set timepoints with `Scenario.restore()`. After restoring information, we can skip `Scenario.trend()` and `Scenario.estiate()`.
