### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by Cody-coder017** [lisphilar/covid19-sir#771]
## What dataset you need?
A dataset consisting of datasets related to India similar to what is made for japan

## How will you use the dataset for your analysis?
The dataset will be used to write a research paper and make a SIR model for India

**Comment by lisphilar** [comment]
Hi @Cody-coder017,
What variables will be required in the dataset for Indea?

**Comment by lisphilar** [comment]
This may be related to #716.

**Comment by Cody-coder017** [comment]
thank you
