### ISSUE TITLE
[Discuss] [forecasting] select features independently for all the ODE parameters

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#778]
## Summary of this new feature
We use `MultiTaskElasticNetCV ` for forecasting (`Scenario.fit_predict()`) and this makes a "constraint is that the selected features are the same for all the regression problems, also called tasks." (scikit-learn documentation: https://scikit-learn.org/stable/modules/linear_model.html#multi-task-elastic-net)

This constraint may be the cause of the low accuracy of forecating. It will be better choice to use `ElasticNetCV` class internally.

**Comment by lisphilar** [comment]
With #782, I tried to replace `MultiTaskElasticNetCV` with `MultiOutputRegressor` + `ElasticNetCV`. However, this raises `ValueError: max() arg is an empty sequence`.

**Comment by lisphilar** [comment]
Ideas for the next steps
- Revise scoring method of regression (backtesting? current: regression model score of test dataset).
- Add new regressors.

**Comment by Inglezos** [comment]
>However, # 782 was not merged because this raised ValueError: max() arg is an empty sequence.
>
In `fit_predict()`, did you try using as delay the None value, in order to use the previous default method instead of the grid search?

**Comment by lisphilar** [comment]
Thank you! `delay=None` fixed the `ValueError` in Italy case.
But, accuracy of forecasting is still low as shown in the next figure. I tried forecasting (and trend analysis/parameter estimation) after `.timepoints(today="01Apr2021")` to compare the predicted number and actual number of variables (good only for Recovered).
![ita_12_history_Confirmed](https://user-images.githubusercontent.com/7270139/119174979-3914cf00-baa4-11eb-8c2e-a33d92958859.png)
![ita_12_history_Recovered](https://user-images.githubusercontent.com/7270139/119174983-3ade9280-baa4-11eb-8859-3addb245b3de.png)
![ita_13_history_Fatal](https://user-images.githubusercontent.com/7270139/119174991-3ca85600-baa4-11eb-9335-daa83a58c5db.png)

**Comment by lisphilar** [comment]
Because 10 days (estimated by `delay=None` in the above case) is included in the grid (5, 31), the errors when using grid search of delay may be caused by scoring method of regression rather than grid search of delay.

**Comment by lisphilar** [comment]
Backtest results for the last one phase.
version 2.20.1
https://gist.github.com/lisphilar/1f3de681ce3de0034e65679f8c2281ad

version 2.20.1-beta
https://gist.github.com/lisphilar/8e089925653954355ccd3f345d7cfe2c

**Comment by lisphilar** [comment]
May be improved in #789.
We continue discussions regarding performance of forecasting in new issues later when we have ideas/questions.
