### ISSUE TITLE
how to change the no of days in a particular column in  @marcoferrante estimation

### ISSUE THREAD

**Issue by Cody-coder017** [lisphilar/covid19-sir#781]
## Summary of question
This is the kaggle note book code which you given for while defining the  function go_out.Here when i wanted to change the no of days nursery to 5, nursery school  to  6 to 4,elementary, and middle school to 6 only in the column .How to do it

## (Optional) What tried

import numpy as np
import pandas as pd
# @marcoferrante estimation
_period_of_life_list = [
    "nursery", "nursery school", "elementary school", "middle school",
    "high school", "university/work", "work", "work", "work", "work",
    "retired", "retired", "retired"
]
df = pd.DataFrame(
    {
        "Age_first": [0, 3, 6, 11, 14, 19, 26, 36, 46, 56, 66, 76, 86],
        "Age_last": [2, 5, 10, 13, 18, 25, 35, 45, 55, 65, 75, 85, 95],
        "Period_of_life": _period_of_life_list,
        "Days": [3, 5, 6, 6, 7, 7, 6, 5, 5, 5, 4, 3, 2]
    }
)
# Adjustment by author
df["Types"] = df["Period_of_life"].replace(
    {
        "nursery": "school",
        "nursery school": "school",
        "elementary school": "school",
        "middle school": "school",
        "high school": "school",
        "university/work": "school/work"
    }
)
df["School"] = df[["Types", "Days"]].apply(lambda x: x[1] if "school" in x[0] else 0, axis=1)
df["Office"] = df[["Types", "Days"]].apply(lambda x: x[1] if "work" in x[0] else 0, axis=1)
df["Others"] = df["Days"] - df[["School", "Office"]].sum(axis=1)
df.loc[df["Others"] < 0, "Others"] = 0
df.loc[df.index[1:5], "School"] -= 1
df.loc[df.index[1:5], "Others"] += 1
df.loc[df.index[5], ["School", "Office", "Others"]] = [6, 6, 1]
df[["School", "Office", "Others"]] = df[["Days", "School", "Office", "Others"]].apply(
    lambda x: x[1:] / sum(x[1:]) * x[0], axis=1
).astype(np.int64)
df.loc[df.index[6:10], "Others"] += 1
df = df.drop(["Days", "Types"], axis=1)
# Show dataset
_out_df = df.copy()
_out_df

## (Optional) Environment

- CovsirPhy version: 
- Python version: 3.8.5
- Installation: poetry/pipenv/conda/pip
- System: WSL (Ubuntu)/Windows/Linux/Mac/Kaggle Notebook/Google Colaboratory

**Comment by lisphilar** [comment]
Kindly provide the details by editting the first comment of this issue.

**Comment by Cody-coder017** [comment]
i changed it

**Comment by lisphilar** [comment]
Thank you. Because `_out_df` is just an `pandas.DataFrame`, we can
```Python
_out_df.loc[_out_df["Period_of_life"] == "nursery", "School"] = 5
_out_df.loc[_out_df["Period_of_life"] == "nursery school", "School"] = 6
_out_df.loc[_out_df["Period_of_life"] == "elementary school", "School"] = 4
_out_df.loc[_out_df["Period_of_life"] == "middle school", "School"] = 6
```
Full codes and outputs: https://gist.github.com/lisphilar/8ef42d8096fce68f967c219f0dee34c7

**Comment by Cody-coder017** [comment]
Thank you
