### ISSUE TITLE
Use of new dataset 

### ISSUE THREAD

**Issue by aboukric** [lisphilar/covid19-sir#791]
## What dataset you need?

I want to use my dataset for my analysis. it is just a .csv file regarding Alberta's cases.

**Comment by lisphilar** [comment]
Thank you for your issue.
We can create `JHUData` instance  with local CSV files via `CountryData`.
https://lisphilar.github.io/covid19-sir/markdown/INSTALLATION.html#use-a-local-csv-file-which-has-the-number-of-cases

Could you share the column names and some lines of your dataset?

**Comment by aboukric** [comment]
Hello Hirokazu
Thank you for your email. Sure, here is the data I am using: "
https://opendata.arcgis.com/datasets/3afa9ce11b8842cb889714611e6f3076_0.csv".
I will use it to create the SEIR and SEIRD modelling.
Best regards,
Ali.

**Comment by lisphilar** [comment]
At the latest version 2.19.2, we can do like this.
https://gist.github.com/lisphilar/a1c7f8bc03eaf9fddeda8d0dd4142e47

Note at the latest version:
- It will be necessary to set population values manually. (Cell 30 of the notebook)
- It will be necessary to convert time "2021-05-24 12:00:00+00:00" to "2020-01-25" manually. (Cell 23)

-> As new features, CovsirPhy may handle them internally.

FYI.
We can read all comments of this issue at https://github.com/lisphilar/covid19-sir/issues/791
E-mails are just a notification.

**Comment by lisphilar** [comment]
With #793 (only development version 2.20.2-alpha at this time), time will be rounded to date.
(i.e. in the next stable version 2.21.0, we will skip `df["Date"] = df["Date"].dt.date`.)
https://gist.github.com/lisphilar/fdc473719bdf005bc46e74d7208e666d

**Comment by lisphilar** [comment]
Seems staled.

**Comment by aboukric** [comment]
Hello Hirokazu
Do you have any idea how to drow the best fit for infected cases? I tried
the graph below, but it looks different from yours.
Thank you very much in advance.
Best regards,
Ali
[image: image.png]

**Comment by lisphilar** [comment]
@aboukric ,
Thank you for reporting, but could create a new issue using your browser with the codes, outputs and version number? When we reply to GitHub notification e-mails, attached files are removed automatically.

**Comment by lisphilar** [comment]
Please use your browser when you have attached files.
