### ISSUE TITLE
[Revise] [forecasting] X include Indicators(n)/Indicators(n-1)

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#823]
## Summary of this new feature
When forecasting with elastic net, SVR and decision tree regressor, X will include Indicators(n)/Indicators(n-1). Then, "Indicators(n)/Indicators(n-1) -> Parameters(n)/Parameters(n-1)" approach will be removed for performance because in-effective.

Note that ’RegressionHandler' ensures 0 <= param <= 1.

**Comment by lisphilar** [comment]
- SVR, Decision tree regressor: whether convert infdicators or not will be determined by grid search
- Elasticc Net: not use converter to avoi errors/warnings

**Comment by Inglezos** [comment]
I didn't understand, you mean that the rates representation of the data now will not be used anymore for forecast?

**Comment by lisphilar** [comment]
Forecasting with Elastic Net will not use rates.

Forecasting with SVR and that with decision tree regressor includes new internal class `_RateConverter` in their pipelines. Necessity of rate representation will be determined by grid search (or random search).
