### ISSUE TITLE
[Docs] update estimate_delay_days.ipynb to fix AttributeError

### ISSUE THREAD

**Issue by jparra0419** [lisphilar/covid19-sir#829]
## Codes

```Python
import covsirphy as cs
# Dataset preparation
data_loader = cs.DataLoader("input")
jhu_data = data_loader.jhu()
# Scenario analysis
snl = cs.Scenario(country="Country name used")
snl.register(jhu_data)
```

## Environment

- CovsirPhy version: 
- Python version: 
- Installation: poetry/pipenv/conda/pip
- System: WSL (Ubuntu)/Windows/Linux/Mac/Kaggle Notebook/Google Colaboratory

**Comment by jparra0419** [comment]
There is a bug in the CODE: Estiamte-delay_days.
Here is the error: 

AttributeError                            Traceback (most recent call last)
<ipython-input-4-0a117ddd44c3> in <module>
      5 print("Indicators: ", indicators)
      6 
----> 7 records = scn.record_df
      8 print("Targets: ", records.columns.values[1:])

AttributeError: 'Scenario' object has no attribute 'record_df'

**Comment by lisphilar** [comment]
Thank you for your notice.
I updated estimate_delay_days.ipynb with #830 to run the example codes with version 2.20.3.

**Comment by lisphilar** [comment]
Documentation was updated and this issue seems staled.
I will close this issue, but we can continue discussion here and create new issues for problems.
