### ISSUE TITLE
[Question/Kaggle] SEWIRF Linelist data kde plot

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#838]
## Summary of question
A long time ago, in the Kaggle notebook in the SEWIRF section, we used to process linelist data and to plot a kde plot, before completely abandoning the linelist data since they are not sufficient. The plot was this:
![image](https://user-images.githubusercontent.com/36845191/122655644-ad529900-d15c-11eb-8081-1b2c75e5d0c8.png)

This was at the section of estimating rho2 and rho3 with Le and Lw periods. The thing is that for that we used the mean/median values of the linelist data. In what way this kde plot was useful? Initially I had thought that we took the argmax values, the days where the kde plot is maximized for Latent/Waiting period but this is not the case.

In specific, in that example the mean value of latent was 8.18 days and of waiting was 7.68, while the argmax corresponds to smaller values (around 5+ and 3+ days instead respectively). These mean values are taken from the raw linelist data, without need of kde plot. Finally the median values are used and in that example both Le ans Lw medians were 6 days, so rho2 and rho3 = 1/6.

**Comment by lisphilar** [comment]
Density (kde) plot is useful to determine the kind of representative values, checking the distribution easily.
The figure indicates latent period and waitning period have asymmetric unimodal distributions. So, we can use median values as the representative values.

If the distribution was symmetric, mean value could be useful. If bimodal, mode value could be useful. I also 
used density plots when we discussed how to calculate the representative value of recovery period with all valid JHU datasets of registered countries.

**Comment by Inglezos** [comment]
Since they have unimodal distributions, why don't we simply use the mode value (which is the argmax) for this too? In asymmetric unimodals the median is more representative?

**Comment by lisphilar** [comment]
When we use mode values, most of the records will be ignored. This is not better when we describe the records.
Eg.
When x1=[0, 0, 1, 1, 1, 1, 1, 2, 3, 4], x2=[0, 0, 1, 1, 1, 2, 3, 3, 4, 4],

&nbsp; | Mode | Median
-- | -- | --
x1 | 1 | 1
x2 | 1 | 1.5

- Mode: The same value because all values except 1s are ignored.
- Median: The different values because the other values are also considered.

**Comment by lisphilar** [comment]
c.f.
 https://link.medium.com/JgqIX5qeYhb

**Comment by lisphilar** [comment]
Dear @Inglezos ,
Long time no see.
Was this issue solved?

**Comment by Inglezos** [comment]
Yes yes it is solved thank you!
