### ISSUE TITLE
[Question/Docs] how to predict COVID-19 prevalence

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#887]
## Summary of question
@AnujTiwari  commented on #851 as follows.

> Hi lisphilar, Is it possible to predict COVID-19 prevalence (symptomatic patients + asymptomatic patients) using the current model?

## (Optional) Environment

- CovsirPhy version: 2.21.0

**Comment by lisphilar** [comment]
Dear @AnujTiwari,
We cannot clasify symptomatic/asymptomatic because we do not have these data.
We can predict ODE parameter values for about one month with `Scenario.fit()` and `Scenario.predict()` methods.
https://lisphilar.github.io/covid19-sir/usage_quick.html#Short-term-prediction-of-parameter-values

**Comment by lisphilar** [comment]
Actually, the prediction accuracy is low and this is the biggest challenge of CovsirPhy project.

Glossary:
- parameter estimation = Optimization of model parameter values with actual records of a phase.
- prediction = Prediction of parameter values in the future phases using relationship of estimated parameters and indexes regarding measures taken by countries and individuals.

https://lisphilar.github.io/covid19-sir/markdown/TERM.html

**Comment by lisphilar** [comment]
Dear @AnujTiwari,
Was this question answered?

**Comment by AnujTiwari** [comment]
Hi Lisphilar, 

I would like to discuss this in detail as we can extend the current model for estimating the true prevalence of the pandemic. 
I know that it is not possible to get the asymptomatic patient data but I came across some of the EPI models which are capable of predicting the true prevalence (asymptomatic + symptomatic) of pandemic using some mathematical estimation.. I am searching the literature and soon share them with you for discussion. 
Thanks

**Comment by lisphilar** [comment]
Thank you, I understood the background of this question. Yes, we need to discuss the mathematical estimation in detail.

FYI.
Postive rate of tests ("daily confirmed" per "daily tests") will be related? This can be calculated with `PCRData.positive_rate()` #389.

**Comment by lisphilar** [comment]
We will discuss this issue later, if necessary.
