### ISSUE TITLE
[Question/Docs] Estimate model for the Selected Phase of Trend Analysis and get_all_ChangePoints() Function 

### ISSUE THREAD

**Issue by AnujTiwari** [lisphilar/covid19-sir#902]
In the current flow of the model, after trend analysis when we use snl.estimate(cs.SIRF) It computes modeling parameters () for all the trend periods (change points). I would like to only compute modeling parameters  for a selected phase like the first or last phase from trend analysis. 

As model takes too much time in execution it is difficult to first estimate model for all the change points and than fetch the record only for a selected phase. I don't want to manually add change points as I want to utilise the advantage of trend analysis (change point). 

also, I request get_all_ChangePoints(), get_first_ChangePoints() and get_last_ChangePoints() functions. 

thank you for the support.

**Comment by lisphilar** [comment]
> I would like to only compute modeling parameters for a selected phase like the first or last phase from trend analysis.

We have `phases` argument of `Scenario.estimate()` (`snl.estimate(cs.SIRF, phases=["0th", "last"])`), but seems not work currently. I will check for that.
https://gist.github.com/lisphilar/e4d7f2faf294a26f2e2eef82757bb9cb

> I request get_all_ChangePoints(), get_first_ChangePoints() and get_last_ChangePoints() functions.

New methods may be useful, but we can do like this if I understand correctly.

```Python
# All
import pandas as pd
df = snl.summary()
all_points = pd.to_datetime(df["Start"]).tolist()
# First, last
all_points[0], all_points[-1]
```

**Comment by lisphilar** [comment]
With #910 (issue: #911), we can use `snl.estimate(cs.SIRF, phases=["0th", "last"])`.
https://gist.github.com/lisphilar/710395694e5bf0b505f6c12c7e9a5593

**Comment by lisphilar** [comment]
@AnujTiwari ,
Was this issue solved?

**Comment by lisphilar** [comment]
We will discuss this issue later, if necessary.
