### ISSUE TITLE
[Discuss] snl.history(target="Rt") giving error 'NoneType' object has no attribute 'title'

### ISSUE THREAD

**Issue by AnujTiwari** [lisphilar/covid19-sir#915]
## Summary of question
In case when the number of days in the last phase is less if I try to estimate the model (only for the last phase) and access the Rt history using  _ = snl.history(target="Rt"). Model throws an error NoneType' object has no attribute 'title'.

I understand that there are no sufficient values to compute the Rt [as I can see in the snl.summary() after snl.estimate(cs.SIRF) _refer the screenshot_] is the cause of this error but I suggest maintaining the Rt title in the output file with the 'NA' [or something else for not sufficient values to compute Rt]. This will help the seamless implementation of the library for a large number of cities/counties/provinces/counties. 

![11111](https://user-images.githubusercontent.com/7472061/127749611-9dff1973-1257-44db-9f51-61b509c8e749.png)

**Comment by lisphilar** [comment]
Thank you for reporting, but could you provide the all outputs of the error? I could not identify the code to revise.

**Comment by lisphilar** [comment]
(For bug fix, please use "Request fixing a bug" issue templete and write the minimal codes and error outputs there next time.)

**Comment by lisphilar** [comment]
This will be closed at this time and we can reopen if necessary.
