### ISSUE TITLE
Error in pip install covsirphy

### ISSUE THREAD

**Issue by anthonytanck** [lisphilar/covid19-sir#920]
I tried using pip to install the covsirphy, but ran into the following error messages. 

ERROR: Failed building wheel for lightgbm
  Running setup.py clean for lightgbm
Failed to build lightgbm

Pls help? Thank you

Phyton 3.9.6
OS Windows 10
Installation pipenv

########################
pip install --upgrade covsirphy

Collecting covsirphy
  Using cached covsirphy-2.22.0-py3-none-any.whl (193 kB)
Collecting covid19dh<3.0.0,>=2.0.3
  Using cached covid19dh-2.3.0-py3-none-any.whl (9.4 kB)
Collecting japanmap<0.0.25,>=0.0.21
  Using cached japanmap-0.0.23-py3-none-any.whl (167 kB)
Requirement already satisfied: ruptures<2.0.0,>=1.1.1 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from covsirphy) (1.1.4)
Requirement already satisfied: pandas<2.0.0,>=1.1.5 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from covsirphy) (1.3.1)
Collecting geopandas<0.10.0,>=0.9.0
  Using cached geopandas-0.9.0-py2.py3-none-any.whl (994 kB)
Collecting descartes<2.0.0,>=1.1.0
  Using cached descartes-1.1.0-py3-none-any.whl (5.8 kB)
Collecting country-converter<0.8.0,>=0.7.1
  Using cached country_converter-0.7.3-py3-none-any.whl
Requirement already satisfied: scipy<2.0.0,>=1.4.1 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from covsirphy) (1.7.1)
Collecting better-exceptions<0.4.0,>=0.3.2
  Using cached better_exceptions-0.3.3-py3-none-any.whl (11 kB)
Requirement already satisfied: wbdata<0.4.0,>=0.3.0 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from covsirphy) (0.3.0)
Requirement already satisfied: scikit-learn<0.25.0,>=0.24.0 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from covsirphy) (0.24.2)
Requirement already satisfied: mapclassify<3.0.0,>=2.4.2 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from covsirphy) (2.4.3)
Requirement already satisfied: Unidecode<2.0.0,>=1.2.0 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from covsirphy) (1.2.0)
Requirement already satisfied: matplotlib<4.0.0,>=3.2.1 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from covsirphy) (3.4.3)
Requirement already satisfied: seaborn<0.12.0,>=0.11.1 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from covsirphy) (0.11.1)
Requirement already satisfied: optuna<3.0.0,>=2.3.0 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from covsirphy) (2.9.1)
Requirement already satisfied: tabulate<0.9.0,>=0.8.7 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from covsirphy) (0.8.9)
Requirement already satisfied: numpy<2.0.0,>=1.18.5 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from covsirphy) (1.21.1+mkl)
Collecting lightgbm<4.0.0,>=3.2.1
  Using cached lightgbm-3.2.1.tar.gz (1.5 MB)
Requirement already satisfied: requests<3.0.0,>=2.25.1 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from covsirphy) (2.26.0)
Requirement already satisfied: colorama in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from better-exceptions<0.4.0,>=0.3.2->covsirphy) (0.4.4)
Requirement already satisfied: pyproj>=2.2.0 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from geopandas<0.10.0,>=0.9.0->covsirphy) (3.1.0)
Requirement already satisfied: fiona>=1.8 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from geopandas<0.10.0,>=0.9.0->covsirphy) (1.8.20)
Requirement already satisfied: shapely>=1.6 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from geopandas<0.10.0,>=0.9.0->covsirphy) (1.7.1)
Requirement already satisfied: six>=1.7 in c:\users\anthony.tan\appdata\roaming\python\python37\site-packages (from fiona>=1.8->geopandas<0.10.0,>=0.9.0->covsirphy) (1.16.0)
Requirement already satisfied: setuptools in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from fiona>=1.8->geopandas<0.10.0,>=0.9.0->covsirphy) (40.8.0)
Requirement already satisfied: attrs>=17 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from fiona>=1.8->geopandas<0.10.0,>=0.9.0->covsirphy) (21.2.0)
Requirement already satisfied: munch in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from fiona>=1.8->geopandas<0.10.0,>=0.9.0->covsirphy) (2.5.0)
Requirement already satisfied: certifi in c:\users\anthony.tan\appdata\roaming\python\python37\site-packages (from fiona>=1.8->geopandas<0.10.0,>=0.9.0->covsirphy) (2021.5.30)
Requirement already satisfied: gdal~=3.3.0 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from fiona>=1.8->geopandas<0.10.0,>=0.9.0->covsirphy) (3.3.1)
Requirement already satisfied: click-plugins>=1.0 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from fiona>=1.8->geopandas<0.10.0,>=0.9.0->covsirphy) (1.1.1)
Requirement already satisfied: cligj>=0.5 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from fiona>=1.8->geopandas<0.10.0,>=0.9.0->covsirphy) (0.7.2)
Requirement already satisfied: click>=4.0 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from fiona>=1.8->geopandas<0.10.0,>=0.9.0->covsirphy) (8.0.1)
Requirement already satisfied: importlib-metadata in c:\users\anthony.tan\appdata\roaming\python\python37\site-packages (from click>=4.0->fiona>=1.8->geopandas<0.10.0,>=0.9.0->covsirphy) (4.6.4)
Requirement already satisfied: opencv-python<5.0.0,>=4.2.0 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from japanmap<0.0.25,>=0.0.21->covsirphy) (4.5.3.56)
Requirement already satisfied: Pillow<8.0.0,>=7.1.1 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from japanmap<0.0.25,>=0.0.21->covsirphy) (7.2.0)
Requirement already satisfied: wheel in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from lightgbm<4.0.0,>=3.2.1->covsirphy) (0.37.0)
Requirement already satisfied: networkx in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from mapclassify<3.0.0,>=2.4.2->covsirphy) (2.6.2)
Requirement already satisfied: cycler>=0.10 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from matplotlib<4.0.0,>=3.2.1->covsirphy) (0.10.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from matplotlib<4.0.0,>=3.2.1->covsirphy) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from matplotlib<4.0.0,>=3.2.1->covsirphy) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from matplotlib<4.0.0,>=3.2.1->covsirphy) (1.3.1)
Requirement already satisfied: alembic in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from optuna<3.0.0,>=2.3.0->covsirphy) (1.6.5)
Requirement already satisfied: cmaes>=0.8.2 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from optuna<3.0.0,>=2.3.0->covsirphy) (0.8.2)
Requirement already satisfied: packaging>=20.0 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from optuna<3.0.0,>=2.3.0->covsirphy) (21.0)
Requirement already satisfied: cliff in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from optuna<3.0.0,>=2.3.0->covsirphy) (3.8.0)
Requirement already satisfied: sqlalchemy>=1.1.0 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from optuna<3.0.0,>=2.3.0->covsirphy) (1.4.22)
Requirement already satisfied: PyYAML in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from optuna<3.0.0,>=2.3.0->covsirphy) (5.4.1)
Requirement already satisfied: tqdm in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from optuna<3.0.0,>=2.3.0->covsirphy) (4.62.0)
Requirement already satisfied: colorlog in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from optuna<3.0.0,>=2.3.0->covsirphy) (5.0.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from pandas<2.0.0,>=1.1.5->covsirphy) (2021.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from requests<3.0.0,>=2.25.1->covsirphy) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from requests<3.0.0,>=2.25.1->covsirphy) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from requests<3.0.0,>=2.25.1->covsirphy) (1.26.6)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from scikit-learn<0.25.0,>=0.24.0->covsirphy) (2.2.0)
Requirement already satisfied: joblib>=0.11 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from scikit-learn<0.25.0,>=0.24.0->covsirphy) (1.0.1)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from sqlalchemy>=1.1.0->optuna<3.0.0,>=2.3.0->covsirphy) (1.1.1)
Requirement already satisfied: appdirs<2.0,>=1.4 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from wbdata<0.4.0,>=0.3.0->covsirphy) (1.4.4)
Requirement already satisfied: decorator>=4.0 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from wbdata<0.4.0,>=0.3.0->covsirphy) (5.0.9)
Requirement already satisfied: python-editor>=0.3 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from alembic->optuna<3.0.0,>=2.3.0->covsirphy) (1.0.4)
Requirement already satisfied: Mako in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from alembic->optuna<3.0.0,>=2.3.0->covsirphy) (1.1.4)
Requirement already satisfied: stevedore>=2.0.1 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from cliff->optuna<3.0.0,>=2.3.0->covsirphy) (3.3.0)
Requirement already satisfied: cmd2>=1.0.0 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from cliff->optuna<3.0.0,>=2.3.0->covsirphy) (2.1.2)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from cliff->optuna<3.0.0,>=2.3.0->covsirphy) (5.6.0)
Requirement already satisfied: PrettyTable>=0.7.2 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from cliff->optuna<3.0.0,>=2.3.0->covsirphy) (2.1.0)
Requirement already satisfied: wcwidth>=0.1.7 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from cmd2>=1.0.0->cliff->optuna<3.0.0,>=2.3.0->covsirphy) (0.2.5)
Requirement already satisfied: pyperclip>=1.6 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from cmd2>=1.0.0->cliff->optuna<3.0.0,>=2.3.0->covsirphy) (1.8.2)
Requirement already satisfied: pyreadline in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from cmd2>=1.0.0->cliff->optuna<3.0.0,>=2.3.0->covsirphy) (2.1)
Requirement already satisfied: typing-extensions in c:\users\anthony.tan\appdata\roaming\python\python37\site-packages (from cmd2>=1.0.0->cliff->optuna<3.0.0,>=2.3.0->covsirphy) (3.10.0.0)
Requirement already satisfied: zipp>=0.5 in c:\users\anthony.tan\appdata\roaming\python\python37\site-packages (from importlib-metadata->click>=4.0->fiona>=1.8->geopandas<0.10.0,>=0.9.0->covsirphy) (3.5.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages (from Mako->alembic->optuna<3.0.0,>=2.3.0->covsirphy) (2.0.1)
Building wheels for collected packages: lightgbm
  Building wheel for lightgbm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\anthony.tan\appdata\local\programs\python\python37-32\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\anthony.tan\\AppData\\Local\\Temp\\pip-install-9ljhqpxf\\lightgbm_1dce0fe0c02344eebfaa39310c29fbbe\\setup.py'"'"'; __file__='"'"'C:\\Users\\anthony.tan\\AppData\\Local\\Temp\\pip-install-9ljhqpxf\\lightgbm_1dce0fe0c02344eebfaa39310c29fbbe\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\anthony.tan\AppData\Local\Temp\pip-wheel-5nk3kmtq'
       cwd: C:\Users\anthony.tan\AppData\Local\Temp\pip-install-9ljhqpxf\lightgbm_1dce0fe0c02344eebfaa39310c29fbbe\
  Complete output (54 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\lightgbm
  copying lightgbm\basic.py -> build\lib\lightgbm
  copying lightgbm\callback.py -> build\lib\lightgbm
  copying lightgbm\compat.py -> build\lib\lightgbm
  copying lightgbm\dask.py -> build\lib\lightgbm
  copying lightgbm\engine.py -> build\lib\lightgbm
  copying lightgbm\libpath.py -> build\lib\lightgbm
  copying lightgbm\plotting.py -> build\lib\lightgbm
  copying lightgbm\sklearn.py -> build\lib\lightgbm
  copying lightgbm\__init__.py -> build\lib\lightgbm
  running egg_info
  writing lightgbm.egg-info\PKG-INFO
  writing dependency_links to lightgbm.egg-info\dependency_links.txt
  writing requirements to lightgbm.egg-info\requires.txt
  writing top-level names to lightgbm.egg-info\top_level.txt
  reading manifest file 'lightgbm.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'build'
  warning: no files found matching '*.so' under directory 'lightgbm'
  warning: no files found matching '*.so' under directory 'compile'
  warning: no files found matching '*.dll' under directory 'compile\Release'
  warning: no files found matching '*.dll' under directory 'compile\windows\x64\DLL'
  warning: no previously-included files matching '*.py[co]' found anywhere in distribution
  warning: no previously-included files found matching 'compile\external_libs\compute\.git'
  writing manifest file 'lightgbm.egg-info\SOURCES.txt'
  copying lightgbm\VERSION.txt -> build\lib\lightgbm
  installing to build\bdist.win32\wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\anthony.tan\AppData\Local\Temp\pip-install-9ljhqpxf\lightgbm_1dce0fe0c02344eebfaa39310c29fbbe\setup.py", line 379, in <module>
      'Topic :: Scientific/Engineering :: Artificial Intelligence'])
    File "c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages\wheel\bdist_wheel.py", line 335, in run
      self.run_command('install')
    File "c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\anthony.tan\AppData\Local\Temp\pip-install-9ljhqpxf\lightgbm_1dce0fe0c02344eebfaa39310c29fbbe\setup.py", line 244, in run
      raise Exception("Cannot install LightGBM in 32-bit Python, "
  Exception: Cannot install LightGBM in 32-bit Python, please use 64-bit Python instead.
  ----------------------------------------
  ERROR: Failed building wheel for lightgbm
  Running setup.py clean for lightgbm
Failed to build lightgbm
Installing collected packages: lightgbm, japanmap, geopandas, descartes, covid19dh, country-converter, better-exceptions, covsirphy
    Running setup.py install for lightgbm ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\anthony.tan\appdata\local\programs\python\python37-32\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\anthony.tan\\AppData\\Local\\Temp\\pip-install-9ljhqpxf\\lightgbm_1dce0fe0c02344eebfaa39310c29fbbe\\setup.py'"'"'; __file__='"'"'C:\\Users\\anthony.tan\\AppData\\Local\\Temp\\pip-install-9ljhqpxf\\lightgbm_1dce0fe0c02344eebfaa39310c29fbbe\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\anthony.tan\AppData\Local\Temp\pip-record-bc482bkv\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\anthony.tan\appdata\local\programs\python\python37-32\Include\lightgbm'
         cwd: C:\Users\anthony.tan\AppData\Local\Temp\pip-install-9ljhqpxf\lightgbm_1dce0fe0c02344eebfaa39310c29fbbe\
    Complete output (16 lines):
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\anthony.tan\AppData\Local\Temp\pip-install-9ljhqpxf\lightgbm_1dce0fe0c02344eebfaa39310c29fbbe\setup.py", line 379, in <module>
        'Topic :: Scientific/Engineering :: Artificial Intelligence'])
      File "c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\anthony.tan\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\anthony.tan\AppData\Local\Temp\pip-install-9ljhqpxf\lightgbm_1dce0fe0c02344eebfaa39310c29fbbe\setup.py", line 244, in run
        raise Exception("Cannot install LightGBM in 32-bit Python, "
    Exception: Cannot install LightGBM in 32-bit Python, please use 64-bit Python instead.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\anthony.tan\appdata\local\programs\python\python37-32\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\anthony.tan\\AppData\\Local\\Temp\\pip-install-9ljhqpxf\\lightgbm_1dce0fe0c02344eebfaa39310c29fbbe\\setup.py'"'"'; __file__='"'"'C:\\Users\\anthony.tan\\AppData\\Local\\Temp\\pip-install-9ljhqpxf\\lightgbm_1dce0fe0c02344eebfaa39310c29fbbe\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\anthony.tan\AppData\Local\Temp\pip-record-bc482bkv\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\anthony.tan\appdata\local\programs\python\python37-32\Include\lightgbm' Check the logs for full command output.

```

**Comment by lisphilar** [comment]
Sorry for my late reply. This issue was resolved (as confirmed via Twitter), but documentation will be updated later if we have information to share with user community.
