### ISSUE TITLE
[New] Corona-virus related Google trends dataset

### ISSUE THREAD

**Issue by manisci** [lisphilar/covid19-sir#947]
## What dataset you need?

Corona-virus search trends over time across countries and territories.

## How will you use the dataset for your analysis?

Google searches have been shown to be one of the most accurate predictors for a surge in covid cases, considerably before they happen. The trends in google searches can also inform epidemiological modelling and governmental interventions and policies.

## (Optional) Example datasets

Source:
https://trends.google.com/trends
API:
https://github.com/GeneralMills/pytrends

**Comment by lisphilar** [comment]
Do you have any ideas regarding the output dataframe of the new data loader?
