### ISSUE TITLE
[Discuss] snl.estimate goes crazy when called from within an iiteration clause.

### ISSUE THREAD

**Issue by baluballa** [lisphilar/covid19-sir#964]
## Summary

I am trying to iterate over several locale for comparison of parameters. However running the scripts makes python go crazy. When (if) testing the script, prepare to exit python in a hard manner.

## Codes
```python
...
for place_to_check in list_df:
    CurProvince = place_to_check
    print("---------------- CHECKING {} ----------------".format(CurProvince))
    # Create instance of `Scenario` class
    snl = cs.Scenario(country="Norway", province=CurProvince)
    snl.register(jhu_data)
    num_Phases = len(snl.summary().index)
    snl.timepoints(first_date=None, last_date=None, today=None)
    # Set phase with S-R trend analysis
    snl.trend(algo="Pelt-rbf", min_size=7)
    if num_Phases > 0:
        snl.estimate(cs.SIRF, n_jobs=-1)
    else:
        print("No phases in %s", CurProvince)
        continue
...
...

```Python
import covsirphy as cs
# Dataset preparation
data_loader.read_csv('locale_data.csv',sep=";",parse_dates=True)
jhu_data = data_loader.jhu()

# Scenario analysis
snl = cs.Scenario(country="Norway", province=CurProvince)
snl.trend(algo="Pelt-rbf", min_size=7)
snl.estimate(cs.SIRF, n_jobs=-1)
```

## Outputs
Bizzare behaviour

## Environment

- CovsirPhy version: 2.22.2
- Python version: 3.9.7
- Installation: pip
- System: Windows

See attached zip file with py script and attached csv data file.

[Covid-19_Analyser.zip](https://github.com/lisphilar/covid19-sir/files/7723345/Covid-19_Analyser.zip)

**Comment by lisphilar** [comment]
Sorry for my late reply. Could your explain "Bizzare behaviour" in detail?

`num_Phases = len(snl.summary().index)` should be 0 because this is before `snl.trend(algo="Pelt-rbf", min_size=7)`, but appears not when executed.

**Comment by baluballa** [comment]
> 

Code run jumps out of the iteration, and starts over. Screen becomes overflown with characters and strange messages.

**Comment by lisphilar** [comment]
May be memory error, but could you share the screenshot? I failed in reproducing the error.

**Comment by baluballa** [comment]
Two examples. It goes so fast I can't read the messages.

![bilde](https://user-images.githubusercontent.com/7481653/146674605-9a2f2829-42ce-4cf2-ac50-4a75bf61c229.png)
Some lines regarding files structure is marked over.
![bilde](https://user-images.githubusercontent.com/7481653/146674725-998219d9-997d-4beb-942a-9fc8f18c8ffe.png)

**Comment by baluballa** [comment]
![bilde](https://user-images.githubusercontent.com/7481653/146674972-e90baf18-5256-49a1-bbfa-dd742b9b3bcc.png)

**Comment by lisphilar** [comment]
Thank you for sharing and the error message implies it is related to multiprocessing.
Could you replace `snl.estimate(cs.SIRF, n_jobs=-1)` with `snl.estimate(cs.SIRF, n_jobs=1)` to stop multiprocessing?

**Comment by baluballa** [comment]
Tested with `n_jobs=1`and got a more clean error. Not the rolling screen as I had with setting `-1`
![bilde](https://user-images.githubusercontent.com/7481653/147087188-e522a1e9-2294-4f38-925a-6b410429cd92.png)

![bilde](https://user-images.githubusercontent.com/7481653/147086408-7d42a45c-56c7-4f0a-9275-0a5fdb4507eb.png)

I have data stored in MySQL from nasjonal health authorities, and wanted to compare _parameter_ values among different provinces, using an iteration.

**Not a big issue** for me... so if you prefer to prioritze something else feel free.

Regards

Thor

**Comment by lisphilar** [comment]
The error message suggests no data was un-available when creating figure of S-R trend analysis. To find the root cause of this, could you debug and find the empty dataframe provided to plotting functions?

Actually, it is difficult to make sufficient time for CovsirPhy project now because so busy at my work. But this project is significant to find solutions to finish COVID-19 outbreak I think.
If you have time, please accelerate comminication in this project by checking and posting comments on the other issues.
(About 30 downloads of the latest version per day, https://pepy.tech/project/covsirphy, and there is a room for improvement to receive feedbacks from users sufficiently.)

**Comment by lisphilar** [comment]
Was this issue solved?

**Comment by lisphilar** [comment]
This will be closed at this time and we can reopen if necessary.
